/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HUCameraPlayerConfiguration : NSObject {
    HMCameraProfile * _cameraProfile;
    NSUUID * _clipUUID;
    HMHome * _home;
    NSUUID * _notificationUUID;
    long long  _scrubberType;
    NSDate * _startingPlaybackDate;
}

@property (nonatomic, readonly) HMCameraProfile *cameraProfile;
@property (nonatomic, readonly) NSUUID *clipUUID;
@property (nonatomic, readonly) HMHome *home;
@property (nonatomic, readonly) NSUUID *notificationUUID;
@property (nonatomic, readonly) long long scrubberType;
@property (nonatomic, retain) NSDate *startingPlaybackDate;

- (void).cxx_destruct;
- (id)cameraProfile;
- (id)clipUUID;
- (id)description;
- (id)home;
- (id)initWithHome:(id)arg1 cameraProfile:(id)arg2 scrubberType:(long long)arg3 notificationUUID:(id)arg4 clipUUID:(id)arg5;
- (bool)isConfiguredForLiveStream;
- (id)notificationUUID;
- (long long)scrubberType;
- (void)setStartingPlaybackDate:(id)arg1;
- (id)startingPlaybackDate;

@end
