/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HUCAPackageIconContentView : HUIconContentView <CAStateControllerDelegate> {
    struct CGSize { 
        double width; 
        double height; 
    }  _assetSize;
    CAPackage * _package;
    NSArray * _packageLayers;
    CALayer * _rootLayer;
    CAStateController * _stateController;
    NSString * _stateName;
}

@property (nonatomic) struct CGSize { double x1; double x2; } assetSize;
@property (nonatomic, retain) CAPackage *package;
@property (nonatomic, retain) NSArray *packageLayers;
@property (nonatomic, retain) CALayer *rootLayer;
@property (nonatomic, retain) CAStateController *stateController;
@property (nonatomic, retain) NSString *stateName;

- (void).cxx_destruct;
- (void)_applyModifiers;
- (void)_tryReclaimPackageForIconDescriptor:(id)arg1;
- (void)_updateForRTL:(bool)arg1;
- (void)_updatePackage;
- (void)_updateStateAnimated:(bool)arg1;
- (struct CGSize { double x1; double x2; })assetSize;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)layoutSubviews;
- (id)package;
- (id)packageLayers;
- (id)rootLayer;
- (void)setAssetSize:(struct CGSize { double x1; double x2; })arg1;
- (void)setPackage:(id)arg1;
- (void)setPackageLayers:(id)arg1;
- (void)setRootLayer:(id)arg1;
- (void)setState:(id)arg1;
- (void)setState:(id)arg1 animated:(bool)arg2;
- (void)setStateController:(id)arg1;
- (void)setStateName:(id)arg1;
- (struct CGSize { double x1; double x2; })sizeThatFits:(struct CGSize { double x1; double x2; })arg1;
- (id)stateController;
- (void)stateController:(id)arg1 didSetStateOfLayer:(id)arg2;
- (void)stateController:(id)arg1 transitionDidStart:(id)arg2 speed:(float)arg3;
- (void)stateController:(id)arg1 transitionDidStop:(id)arg2 completed:(bool)arg3;
- (id)stateName;
- (void)updateWithIconDescriptor:(id)arg1 displayStyle:(unsigned long long)arg2 animated:(bool)arg3;

@end
