/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HUDashboardNavigationBar : UINavigationBar <HUDashboardNavigationButtonDelegate, HUDashboardNavigationHost, HUDashboardNavigationTitleViewDelegate> {
    HFWallpaperSlice * _blurredWallpaperSlice;
    double  _buttonBlurAlpha;
    HUWallpaperView * _containingWallpaperView;
    bool  _isBackgroundVisible;
    HUNavigationBarLayoutOptions * _layoutOptions;
    NSArray * _leftDashboardNavigationButtons;
    NSArray * _rightDashboardNavigationButtons;
    HUDashboardNavigationTitleView * _titleView;
}

@property (nonatomic, retain) HFWallpaperSlice *blurredWallpaperSlice;
@property (nonatomic) double buttonBlurAlpha;
@property (nonatomic) HUWallpaperView *containingWallpaperView;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) bool isBackgroundVisible;
@property (nonatomic, copy) HUNavigationBarLayoutOptions *layoutOptions;
@property (nonatomic, retain) NSArray *leftDashboardNavigationButtons;
@property (nonatomic, retain) NSArray *rightDashboardNavigationButtons;
@property (readonly) Class superclass;
@property (nonatomic, retain) HUDashboardNavigationTitleView *titleView;

- (void).cxx_destruct;
- (id)_configuredBarButtonItemForDashboardNavigationButton:(id)arg1;
- (void)_updateAllBarButtonItemsForTopItem;
- (void)_updateLayoutMargins;
- (void)_updateLeftBarButtonItemsForTopItem;
- (void)_updateRightBarButtonItemsForTopItem;
- (void)_updateTintColor;
- (void)_updateTintColorForBarButtons:(id)arg1;
- (id)blurredWallpaperSlice;
- (double)buttonBlurAlpha;
- (id)containingWallpaperView;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (bool)isBackgroundVisible;
- (void)largeTitleHeightDidChange:(double)arg1;
- (id)layoutOptions;
- (void)layoutSubviews;
- (id)leftDashboardNavigationButtons;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })normalizedWallpaperRectForDashboardNavigationButton:(id)arg1;
- (id)popNavigationItemAnimated:(bool)arg1;
- (void)pushNavigationItem:(id)arg1 animated:(bool)arg2;
- (id)rightDashboardNavigationButtons;
- (void)setBlurredWallpaperSlice:(id)arg1;
- (void)setButtonBlurAlpha:(double)arg1;
- (void)setContainingWallpaperView:(id)arg1;
- (void)setIsBackgroundVisible:(bool)arg1;
- (void)setItems:(id)arg1 animated:(bool)arg2;
- (void)setLayoutOptions:(id)arg1;
- (void)setLeftDashboardNavigationButtons:(id)arg1;
- (void)setRightDashboardNavigationButtons:(id)arg1;
- (void)setTitleView:(id)arg1;
- (id)titleView;
- (void)traitCollectionDidChange:(id)arg1;

@end
