/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HUHomeTheaterAudioItemModule : HFItemModule {
    <HUHomeTheaterAudioItemModuleDelegate> * _delegate;
    bool  _disableAutomaticCommit;
    bool  _includeLocalDestinations;
    NSSet * _itemProviders;
    <HFMediaProfileContainer> * _mediaProfileContainer;
    HFItem * _selectedUncommittedItem;
    NSString * _tappedDestinationIdentifier;
}

@property (nonatomic) <HUHomeTheaterAudioItemModuleDelegate> *delegate;
@property (nonatomic) bool disableAutomaticCommit;
@property (nonatomic, readonly) bool includeLocalDestinations;
@property (nonatomic, readonly) <HFMediaProfileContainer> *mediaProfileContainer;
@property (nonatomic, readonly) HFItem *selectedUncommittedItem;
@property (nonatomic, retain) NSString *tappedDestinationIdentifier;

- (void).cxx_destruct;
- (void)_createItemProviders;
- (id)_updateDestinationToIdentifier:(id)arg1;
- (id)buildSectionsWithDisplayedItems:(id)arg1;
- (id)commitConfiguration;
- (id)delegate;
- (bool)disableAutomaticCommit;
- (bool)includeLocalDestinations;
- (id)initWithItemUpdater:(id)arg1 mediaProfileContainer:(id)arg2 includeLocalDestinations:(bool)arg3;
- (id)itemProviders;
- (id)mediaProfileContainer;
- (void)selectItem:(id)arg1;
- (id)selectedUncommittedItem;
- (void)setDelegate:(id)arg1;
- (void)setDisableAutomaticCommit:(bool)arg1;
- (void)setTappedDestinationIdentifier:(id)arg1;
- (id)tappedDestinationIdentifier;

@end
