/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HUHomeControlServiceContext : NSObject {
    NSURL * _defaultActionURL;
    NSString * _homeIdentifier;
    NSString * _homeName;
    <SBUIRemoteAlertHostInterface> * _remoteViewControllerProxy;
    NSString * _roomIdentifier;
    NSString * _roomName;
    unsigned long long  _serviceType;
}

@property (nonatomic, copy) NSURL *defaultActionURL;
@property (nonatomic, retain) NSString *homeIdentifier;
@property (nonatomic, copy) NSString *homeName;
@property (nonatomic, retain) <SBUIRemoteAlertHostInterface> *remoteViewControllerProxy;
@property (nonatomic, retain) NSString *roomIdentifier;
@property (nonatomic, copy) NSString *roomName;
@property (nonatomic) unsigned long long serviceType;

+ (id)_homeInfoFromDefaultActionURL:(id)arg1;

- (void).cxx_destruct;
- (id)_initWithUserInfo:(id)arg1;
- (id)defaultActionURL;
- (id)homeIdentifier;
- (id)homeName;
- (id)initWithAlertConfigurationContext:(id)arg1;
- (id)initWithServiceType:(unsigned long long)arg1 defaultActionURL:(id)arg2;
- (id)initWithServiceType:(unsigned long long)arg1 home:(id)arg2 room:(id)arg3;
- (id)initWithServiceType:(unsigned long long)arg1 homeIdentifier:(id)arg2 roomIdentifier:(id)arg3;
- (id)remoteViewControllerProxy;
- (id)roomIdentifier;
- (id)roomName;
- (unsigned long long)serviceType;
- (void)setDefaultActionURL:(id)arg1;
- (void)setHomeIdentifier:(id)arg1;
- (void)setHomeName:(id)arg1;
- (void)setRemoteViewControllerProxy:(id)arg1;
- (void)setRoomIdentifier:(id)arg1;
- (void)setRoomName:(id)arg1;
- (void)setServiceType:(unsigned long long)arg1;
- (id)userInfo;

@end
