/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HUNewUserEducationCollectionViewCellModel : HUNewUserEducationBaseViewModel

- (id)init;
- (id)randomColor;

@end
