/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HUNewUserEducationFlowLayoutModel : NSObject {
    long long  _scrollDirection;
}

@property (nonatomic, readonly) long long scrollDirection;

+ (struct CGPoint { double x1; double x2; })getTargetOffsetForProposedContentOffset:(struct CGPoint { double x1; double x2; })arg1 horizontalOffset:(double)arg2 offsetAdjustment:(double)arg3 layoutAttributes:(id)arg4;

- (id)init;
- (long long)scrollDirection;

@end
