/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HUNetworkConfigurationGroupItemManager : HFItemManager {
    HUNetworkConfigurationItemListModule * _networkConfigurationItemListModule;
}

@property (nonatomic, readonly) HUNetworkConfigurationItemListModule *networkConfigurationItemListModule;

- (void).cxx_destruct;
- (id)_buildItemModulesForHome:(id)arg1;
- (id)networkConfigurationItemListModule;

@end
