/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HUQuickControlViewControllerGroup : NSObject {
    NSSet * _alternateViewControllers;
    HUQuickControlViewController * _primaryViewController;
}

@property (nonatomic, readonly) NSSet *alternateViewControllers;
@property (nonatomic, readonly) HUQuickControlViewController *primaryViewController;

- (void).cxx_destruct;
- (id)alternateViewControllers;
- (id)initWithPrimaryViewController:(id)arg1 alternateViewControllers:(id)arg2;
- (id)primaryViewController;

@end
