/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HUQuickControlSummaryNavigationBarTitleView : _UINavigationBarTitleView {
    NSArray * _contentConstraints;
    HUQuickControlSummaryView * _summaryView;
}

@property (nonatomic, retain) NSArray *contentConstraints;
@property (nonatomic, retain) HUQuickControlSummaryView *summaryView;

- (void).cxx_destruct;
- (id)contentConstraints;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)layoutSubviews;
- (void)setContentConstraints:(id)arg1;
- (void)setSummaryView:(id)arg1;
- (id)summaryView;
- (void)transitionCompleted:(long long)arg1 willBeDisplayed:(bool)arg2;
- (void)updateConstraints;

@end
