/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HURecommendationItemModuleController : HUItemTableModuleController <HUIconSwitchCellDelegate, HUPresentationDelegate, HUTriggerEditorDelegate> {
    unsigned long long  _selectionType;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) HURecommendationItemModule *module;
@property unsigned long long selectionType;
@property (readonly) Class superclass;

- (void)_item:(id)arg1 didTurnOn:(bool)arg2;
- (void)_presentActionSetSummaryWithBuilder:(id)arg1 forRecommendation:(id)arg2;
- (void)_presentSummaryForBuilder:(id)arg1 forRecommendation:(id)arg2;
- (void)_presentTriggerSummaryWithBuilder:(id)arg1 forRecommendation:(id)arg2;
- (void)_presentViewController:(id)arg1;
- (Class)cellClassForItem:(id)arg1;
- (id)commitSelectedItems;
- (unsigned long long)didSelectItem:(id)arg1;
- (id)dismissViewController:(id)arg1;
- (id)finishPresentation:(id)arg1 animated:(bool)arg2;
- (id)initWithModule:(id)arg1 selectionType:(unsigned long long)arg2;
- (unsigned long long)selectionType;
- (void)setSelectionType:(unsigned long long)arg1;
- (void)setupCell:(id)arg1 forItem:(id)arg2;
- (void)switchCell:(id)arg1 didTurnOn:(bool)arg2;
- (void)triggerEditor:(id)arg1 didFinishWithTriggerBuilder:(id)arg2;

@end
