/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HURecommendationItem : HFItem <HUTriggerLikeItem> {
    HRERecommendation * _recommendation;
    bool  _selected;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSString *identifier;
@property (nonatomic, retain) HRERecommendation *recommendation;
@property (getter=isSelected, nonatomic) bool selected;
@property (readonly) Class superclass;
@property (nonatomic, readonly) HMTrigger *trigger;

- (void).cxx_destruct;
- (id)_subclass_updateWithOptions:(id)arg1;
- (id)identifier;
- (id)initWithRecommendation:(id)arg1;
- (bool)isSelected;
- (id)recommendation;
- (void)setRecommendation:(id)arg1;
- (void)setSelected:(bool)arg1;
- (id)trigger;

@end
