/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HUTriggerListHeadlineItem : HFStaticItem <HUItemMapsToView>

- (Class)mapsToViewClass;

@end
