/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ProximityControl.framework/ProximityControl
 */

@interface PCDisambiguationContext : NSObject <NSSecureCoding> {
    NSUserActivity * _activity;
    PCHomeKitIdentifier * _identifier;
    long long  _interactionDirection;
}

@property (nonatomic, readonly) NSUserActivity *activity;
@property (nonatomic, readonly) PCHomeKitIdentifier *identifier;
@property (nonatomic, readonly) long long interactionDirection;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)activity;
- (void)encodeWithCoder:(id)arg1;
- (id)identifier;
- (id)initWithCoder:(id)arg1;
- (long long)interactionDirection;

@end
