/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ProximityControl.framework/ProximityControl
 */

@interface PCRemoteActivityClient : NSObject <NSSecureCoding, PCActivatable> {
    NSObject<OS_dispatch_queue> * _dispatchQueue;
    id /* block */  _interruptionHandler;
    id /* block */  _invalidationHandler;
    id /* block */  _updateHandler;
    <NSXPCProxyCreating> * _xpcCnx;
}

@property (nonatomic, retain) NSObject<OS_dispatch_queue> *dispatchQueue;
@property (nonatomic, copy) id /* block */ interruptionHandler;
@property (nonatomic, copy) id /* block */ invalidationHandler;
@property (nonatomic, copy) id /* block */ updateHandler;
@property (nonatomic, retain) <NSXPCProxyCreating> *xpcCnx;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (void)_activateWithCompletion:(id /* block */)arg1;
- (void)_interrupted;
- (void)_invalidate;
- (void)_invalidated;
- (void)_xpcEnsureStarted;
- (void)_xpcEnsureStopped;
- (void)activateWithCompletion:(id /* block */)arg1;
- (void)dealloc;
- (id)dispatchQueue;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (void)interrupted;
- (id /* block */)interruptionHandler;
- (void)invalidate;
- (id /* block */)invalidationHandler;
- (void)setDispatchQueue:(id)arg1;
- (void)setInterruptionHandler:(id /* block */)arg1;
- (void)setInvalidationHandler:(id /* block */)arg1;
- (void)setUpdateHandler:(id /* block */)arg1;
- (void)setXpcCnx:(id)arg1;
- (void)startObservingDeviceWithIdentifier:(id)arg1;
- (void)stopObservingAllDevices;
- (void)stopObservingDeviceWithIdentifier:(id)arg1;
- (id /* block */)updateHandler;
- (id)xpcCnx;

@end
