/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowKit.framework/WorkflowKit
 */

@interface WFAccessResourceAvailabilityBlockRegistry : NSObject

// Image: /System/Library/PrivateFrameworks/WorkflowKit.framework/WorkflowKit

+ (id /* block */)contactAccessResourceAvailabilityBlock;
+ (void)rediscoverAvailabilityBlocksIfNeeded;
+ (id /* block */)remoteServerAccessResourceAvailabilityBlock;
+ (void)setContactAccessResourceAvailabilityBlock:(id /* block */)arg1;
+ (void)setRemoteServerAccessResourceAvailabilityBlock:(id /* block */)arg1;

// Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit

+ (void)registerAvailabilityBlocksInActionKit;

@end
