/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowKit.framework/WorkflowKit
 */

@interface WFURLParameter : WFTextInputParameter

// Image: /System/Library/PrivateFrameworks/WorkflowKit.framework/WorkflowKit

- (long long)autocapitalizationType;
- (long long)autocorrectionType;
- (long long)keyboardType;
- (Class)singleStateClass;
- (id)textContentType;

// Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor

- (id)moduleSummaryAskVariableName;

@end
