/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface _SBFolderControllerIconImageViewControllerKeepStaticAssertion : NSObject <BSDescriptionProviding, BSInvalidatable> {
    SBFolderController * _folderController;
    bool  _invalidated;
    NSIndexSet * _pageIndexesToExclude;
    NSString * _reason;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) SBFolderController *folderController;
@property (readonly) unsigned long long hash;
@property (getter=isInvalidated, nonatomic) bool invalidated;
@property (nonatomic, readonly, copy) NSIndexSet *pageIndexesToExclude;
@property (nonatomic, readonly, copy) NSString *reason;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)dealloc;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)folderController;
- (id)initWithFolderController:(id)arg1 pageIndexesToExclude:(id)arg2 reason:(id)arg3;
- (void)invalidate;
- (bool)isInvalidated;
- (id)pageIndexesToExclude;
- (id)reason;
- (void)setInvalidated:(bool)arg1;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;

@end
