/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBHAppLibraryVisualConfiguration : NSObject <BSDescriptionProviding, NSCopying> {
    struct UIEdgeInsets { 
        double top; 
        double left; 
        double bottom; 
        double right; 
    }  _appSearchTextFieldLayoutInsets;
    double  _searchContinuousCornerRadius;
}

@property (nonatomic) struct UIEdgeInsets { double x1; double x2; double x3; double x4; } appSearchTextFieldLayoutInsets;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) double searchContinuousCornerRadius;
@property (readonly) Class superclass;

- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })appSearchTextFieldLayoutInsets;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (unsigned long long)hash;
- (id)init;
- (bool)isEqual:(id)arg1;
- (double)searchContinuousCornerRadius;
- (void)setAppSearchTextFieldLayoutInsets:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg1;
- (void)setSearchContinuousCornerRadius:(double)arg1;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;

@end
