/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBHHomePullToSearchSettings : PTSettings {
    double  _fluidBehaviorDampingRatio;
    double  _fluidBehaviorResponse;
    double  _pullGestureBeganFromTopLeeway;
    double  _pullTransitionActivationThreshold;
    double  _pullTransitionDistance;
}

@property (nonatomic) double fluidBehaviorDampingRatio;
@property (nonatomic) double fluidBehaviorResponse;
@property (nonatomic) double pullGestureBeganFromTopLeeway;
@property (nonatomic) double pullTransitionActivationThreshold;
@property (nonatomic) double pullTransitionDistance;

+ (id)settingsControllerModule;

- (double)fluidBehaviorDampingRatio;
- (double)fluidBehaviorResponse;
- (double)pullGestureBeganFromTopLeeway;
- (double)pullTransitionActivationThreshold;
- (double)pullTransitionDistance;
- (void)setDefaultValues;
- (void)setFluidBehaviorDampingRatio:(double)arg1;
- (void)setFluidBehaviorResponse:(double)arg1;
- (void)setPullGestureBeganFromTopLeeway:(double)arg1;
- (void)setPullTransitionActivationThreshold:(double)arg1;
- (void)setPullTransitionDistance:(double)arg1;

@end
