/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBHLibrarySearchController : UIViewController <BSUIScrollViewDelegate, PTSettingsKeyObserver, SBHSearchBarDelegate> {
    UIView * _containerView;
    UIView * _contentContainerView;
    UIViewController<SBHLibrarySearchControllerContentViewControllerScrollViewProvider> * _contentViewController;
    NSArray * _contentViewGradientMaskLayers;
    <SBHLibrarySearchControllerDelegate> * _delegate;
    <SBIconListLayoutProvider> * _listLayoutProvider;
    SBHHomePullToSearchSettings * _pullToSearchSettings;
    UIScrollView * _scrollView;
    bool  _scrollViewBeganScrollingFromTop;
    SBFFluidBehaviorSettings * _searchAnimationSettings;
    MTMaterialView * _searchBackdropView;
    SBHSearchBar * _searchBar;
    UIView * _searchDimmingView;
    SBHSearchTextField * _searchField;
    UIView * _searchResultsContainerView;
    SBHIconLibraryTableViewController * _searchResultsController;
    NSArray * _searchResultsGradientMaskLayers;
    <SBHSearchResultsUpdating> * _searchResultsUpdater;
    long long  _searchState;
}

@property (getter=isActive, nonatomic) bool active;
@property (nonatomic, readonly) UIViewController<SBHLibrarySearchControllerContentViewControllerScrollViewProvider> *contentViewController;
@property (nonatomic, readonly) NSArray *contentViewGradientMaskLayers;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <SBHLibrarySearchControllerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) <SBIconListLayoutProvider> *listLayoutProvider;
@property (nonatomic) bool scrollViewBeganScrollingFromTop;
@property (nonatomic, retain) SBFFluidBehaviorSettings *searchAnimationSettings;
@property (nonatomic, readonly) SBHSearchBar *searchBar;
@property (nonatomic, retain) UIView *searchDimmingView;
@property (nonatomic, readonly) SBHSearchTextField *searchField;
@property (getter=isSearchFieldEditing, nonatomic, readonly) bool searchFieldEditing;
@property (nonatomic, readonly) SBHIconLibraryTableViewController *searchResultsController;
@property (nonatomic, readonly) NSArray *searchResultsGradientMaskLayers;
@property (nonatomic) <SBHSearchResultsUpdating> *searchResultsUpdater;
@property (nonatomic, readonly) long long searchState;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_calculateSearchBarFrame:(bool)arg1;
- (void)_didDismissSearch;
- (void)_didPresentSearch;
- (void)_dismissPresentation:(bool)arg1;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })_edgeInsetsForChildViewController:(id)arg1 insetsAreAbsolute:(bool*)arg2;
- (void)_layoutSearchViews;
- (void)_layoutSearchViewsWithMode:(long long)arg1 withCompletion:(id /* block */)arg2;
- (void)_performPresentation:(bool)arg1;
- (double)_rubberbandingOffsetForContentOffset:(struct CGPoint { double x1; double x2; })arg1;
- (double)_searchPresentationProgressForOffset:(double)arg1;
- (void)_setUpFeatherMaskLayerMatchMoveAnimations;
- (void)_setupSearchAnimationSettings;
- (void)_willDismissSearchAnimated:(bool)arg1;
- (void)_willPresentSearchAnimated:(bool)arg1;
- (id)contentScrollView;
- (id)contentViewController;
- (id)contentViewGradientMaskLayers;
- (id)delegate;
- (void)endEditingForSearchField;
- (id)initWithSearchResultsController:(id)arg1 contentViewController:(id)arg2;
- (bool)isActive;
- (bool)isSearchFieldEditing;
- (bool)isTransitionInProgress;
- (id)listLayoutProvider;
- (struct CGSize { double x1; double x2; })preferredContentSize;
- (void)resetSearchController:(bool)arg1 clearSearchResults:(bool)arg2 resetSearchBarTransformAndAlpha:(bool)arg3;
- (bool)scrollViewBeganScrollingFromTop;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint { double x1; double x2; })arg2 targetContentOffset:(inout struct CGPoint { double x1; double x2; }*)arg3;
- (id)searchAnimationSettings;
- (id)searchBar;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBarCancelButtonClicked:(id)arg1;
- (bool)searchBarShouldBeginEditing:(id)arg1;
- (bool)searchBarShouldEndEditing:(id)arg1;
- (bool)searchBarShouldReturn:(id)arg1;
- (void)searchBarTextDidEndEditing:(id)arg1;
- (id)searchDimmingView;
- (id)searchField;
- (id)searchResultsController;
- (id)searchResultsGradientMaskLayers;
- (id)searchResultsUpdater;
- (long long)searchState;
- (void)setActive:(bool)arg1;
- (void)setActive:(bool)arg1 animated:(bool)arg2;
- (void)setDelegate:(id)arg1;
- (void)setListLayoutProvider:(id)arg1;
- (void)setScrollViewBeganScrollingFromTop:(bool)arg1;
- (void)setSearchAnimationSettings:(id)arg1;
- (void)setSearchDimmingView:(id)arg1;
- (void)setSearchResultsUpdater:(id)arg1;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (bool)shouldAutomaticallyForwardAppearanceMethods;
- (void)viewDidAppear:(bool)arg1;
- (void)viewDidDisappear:(bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(bool)arg1;
- (void)viewWillDisappear:(bool)arg1;
- (void)viewWillLayoutSubviews;

@end
