/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBHRecentsDocumentExtensionWrappingViewController : UIViewController {
    NSMutableArray * _constraints;
    NSMapTable * _touchCancellationAssertionsToTokens;
    _UIRemoteViewController * _wrappedRemoteViewController;
}

- (void).cxx_destruct;
- (bool)_canShowWhileLocked;
- (void)_updateViewIntrinsicContentSize:(struct CGSize { double x1; double x2; })arg1;
- (id)cancelTouchesForCurrentEventInHostedContent;
- (void)dealloc;
- (id)init;
- (void)loadView;
- (void)preferredContentSizeDidChangeForChildContentContainer:(id)arg1;
- (void)setPreferredContentSize:(struct CGSize { double x1; double x2; })arg1;
- (void)wrapRemoteViewController:(id)arg1;

@end
