/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBHStackConfigurationWidgetTableViewCell : UITableViewCell {
    <SBLeafIconDataSource> * _dataSource;
    UILabel * _descriptionLabel;
    CHSAvocadoDescriptor * _descriptor;
    UIStackView * _horizontalStackView;
    UIImageView * _iconImageView;
    UILabel * _titleLabel;
    UIStackView * _verticalStackView;
}

@property (nonatomic, retain) <SBLeafIconDataSource> *dataSource;
@property (nonatomic, retain) UILabel *descriptionLabel;
@property (nonatomic, retain) CHSAvocadoDescriptor *descriptor;
@property (nonatomic, retain) UIStackView *horizontalStackView;
@property (nonatomic, retain) UIImageView *iconImageView;
@property (nonatomic, retain) UILabel *titleLabel;
@property (nonatomic, retain) UIStackView *verticalStackView;

- (void).cxx_destruct;
- (struct SBIconImageInfo { struct CGSize { double x_1_1_1; double x_1_1_2; } x1; double x2; double x3; })_iconImageInfo;
- (void)configureWithDataSource:(id)arg1 icon:(id)arg2 descriptor:(id)arg3;
- (id)dataSource;
- (id)descriptionLabel;
- (id)descriptor;
- (void)didMoveToWindow;
- (id)horizontalStackView;
- (id)iconImageView;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)setDataSource:(id)arg1;
- (void)setDescriptionLabel:(id)arg1;
- (void)setDescriptor:(id)arg1;
- (void)setHorizontalStackView:(id)arg1;
- (void)setIconImageView:(id)arg1;
- (void)setTitleLabel:(id)arg1;
- (void)setVerticalStackView:(id)arg1;
- (id)titleLabel;
- (id)verticalStackView;

@end
