/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBHWidgetConfigurationTransformView : SBFTouchPassThroughView

+ (Class)layerClass;

@end
