/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBHWidgetStackDescriptor : NSObject <SBHAddWidgetSheetGalleryItem> {
    NSArray * _largeStackDescriptors;
    NSArray * _mediumStackDescriptors;
    NSArray * _smallStackDescriptors;
}

@property (nonatomic, readonly, copy) UIColor *accentColor;
@property (nonatomic, readonly, copy) UIColor *backgroundColor;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) NSArray *largeStackDescriptors;
@property (nonatomic, retain) NSArray *mediumStackDescriptors;
@property (nonatomic, readonly, copy) UIColor *mostInterestingColor;
@property (nonatomic, readonly, copy) NSString *sbh_appName;
@property (nonatomic, readonly) unsigned long long sbh_supportedSizeClasses;
@property (nonatomic, readonly, copy) NSString *sbh_widgetDescription;
@property (nonatomic, readonly, copy) NSString *sbh_widgetName;
@property (nonatomic, retain) NSArray *smallStackDescriptors;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)accentColor;
- (id)backgroundColor;
- (id)descriptorsForSizeClass:(long long)arg1;
- (id)initWithSmallStackDescriptors:(id)arg1 mediumStackDescriptors:(id)arg2 largeStackDescriptors:(id)arg3;
- (bool)isEqual:(id)arg1;
- (id)largeStackDescriptors;
- (id)mediumStackDescriptors;
- (id)mostInterestingColor;
- (id)sbh_appName;
- (unsigned long long)sbh_supportedSizeClasses;
- (id)sbh_widgetDescription;
- (id)sbh_widgetName;
- (void)setLargeStackDescriptors:(id)arg1;
- (void)setMediumStackDescriptors:(id)arg1;
- (void)setSmallStackDescriptors:(id)arg1;
- (id)smallStackDescriptors;

@end
