/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBHWidgetFamilySegmentedControl : UIControl {
    NSMutableArray * _buttons;
    NSArray * _items;
    long long  _selectedSegmentIndex;
    UIStackView * _stackView;
}

@property (nonatomic, retain) NSMutableArray *buttons;
@property (nonatomic, copy) NSArray *items;
@property (nonatomic) long long selectedSegmentIndex;
@property (nonatomic, retain) UIStackView *stackView;

- (void).cxx_destruct;
- (id)_buttonForItem:(id)arg1;
- (void)_buttonPressed:(id)arg1;
- (void)_updateContent;
- (void)_updateSelectedStates;
- (id)buttons;
- (void)didMoveToWindow;
- (id)init;
- (id)initWithItems:(id)arg1;
- (id)items;
- (void)layoutSubviews;
- (long long)selectedSegmentIndex;
- (void)setButtons:(id)arg1;
- (void)setItems:(id)arg1;
- (void)setSelectedSegmentIndex:(long long)arg1;
- (void)setStackView:(id)arg1;
- (id)stackView;

@end
