/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBIconListFlowExtendedLayout : SBIconListFlowLayout

- (struct CGSize { double x1; double x2; })iconSpacingForOrientation:(long long)arg1;

@end
