/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBIconListGridCellInfo : NSObject <BSDescriptionProviding, NSCopying> {
    unsigned short * _extraGridCellIndexes;
    unsigned long long  _extraGridCellIndexesSize;
    unsigned short * _extraIconIndexes;
    unsigned long long  _extraIconIndexesSize;
    struct SBHIconGridSize { 
        unsigned short columns; 
        unsigned short rows; 
    }  _gridSize;
    unsigned short  _indexes;
    unsigned long long  _numberOfUsedColumns;
    unsigned long long  _numberOfUsedRows;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) struct SBHIconGridSize { unsigned short x1; unsigned short x2; } gridSize;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly, copy) NSString *layoutDescription;
@property (getter=isLayoutOutOfBounds, nonatomic, readonly) bool layoutOutOfBounds;
@property (nonatomic) unsigned long long numberOfUsedColumns;
@property (nonatomic) unsigned long long numberOfUsedRows;
@property (readonly) Class superclass;

- (void)addEmptyColumns:(unsigned long long)arg1;
- (void)addEmptyRows:(unsigned long long)arg1;
- (void)clearAllIconAndGridCellIndexes;
- (struct SBIconCoordinate { long long x1; long long x2; })coordinateForGridCellIndex:(unsigned long long)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (unsigned long long)gridCellIndexForCoordinate:(struct SBIconCoordinate { long long x1; long long x2; })arg1;
- (unsigned long long)gridCellIndexForIconIndex:(unsigned long long)arg1;
- (struct SBHIconGridRange { unsigned long long x1; struct SBHIconGridSize { unsigned short x_2_1_1; unsigned short x_2_1_2; } x2; })gridRangeForGridCellIndex:(unsigned long long)arg1;
- (struct SBHIconGridSize { unsigned short x1; unsigned short x2; })gridSize;
- (struct SBHIconGridSize { unsigned short x1; unsigned short x2; })gridSizeForGridCellIndex:(unsigned long long)arg1;
- (unsigned long long)iconIndexForGridCellIndex:(unsigned long long)arg1;
- (unsigned long long)indexOfOutOfBoundsIconInRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg1;
- (id)init;
- (bool)isLayoutOutOfBounds;
- (bool)isOutOfBoundsAtIconIndex:(unsigned long long)arg1;
- (id)layoutDescription;
- (unsigned long long)maxGridCellIndexForIconIndex:(unsigned long long)arg1;
- (unsigned long long)numberOfUsedColumns;
- (unsigned long long)numberOfUsedGridCellsInColumn:(unsigned long long)arg1;
- (unsigned long long)numberOfUsedGridCellsInColumn:(unsigned long long)arg1 rowRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg2;
- (unsigned long long)numberOfUsedGridCellsInRow:(unsigned long long)arg1;
- (unsigned long long)numberOfUsedGridCellsInRow:(unsigned long long)arg1 columnRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg2;
- (unsigned long long)numberOfUsedRows;
- (void)setGridCellIndex:(unsigned long long)arg1 forIconIndex:(unsigned long long)arg2;
- (void)setGridSize:(struct SBHIconGridSize { unsigned short x1; unsigned short x2; })arg1;
- (void)setIconIndex:(unsigned long long)arg1 forGridCellIndex:(unsigned long long)arg2;
- (void)setNumberOfUsedColumns:(unsigned long long)arg1;
- (void)setNumberOfUsedRows:(unsigned long long)arg1;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;

@end
