/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBRootFolder : SBFolder {
    <SBRootFolderDelegate> * _delegate;
    SBHIconModel * _model;
    bool  _supportsTodayList;
}

@property (nonatomic, readonly) bool containsVisibleWidgetIconExcludingTodayList;
@property (nonatomic, readonly) bool containsWidgetIconExcludingTodayList;
@property (nonatomic) <SBRootFolderDelegate> *delegate;
@property (setter=_setDock:, nonatomic, retain) SBIconListModel *dock;
@property (setter=_setFavoriteTodayList:, nonatomic, retain) SBIconListModel *favoriteTodayList;
@property (setter=_setIgnoredList:, nonatomic, retain) SBIconListModel *ignoredList;
@property (nonatomic) SBHIconModel *model;
@property (nonatomic, readonly) bool supportsBadging;
@property (nonatomic, readonly) bool supportsDock;
@property (nonatomic, readonly) bool supportsIgnoredList;
@property (nonatomic, readonly) bool supportsTodayList;
@property (setter=_setTodayList:, nonatomic, retain) SBIconListModel *todayList;

+ (bool)isRootFolderClass;

- (void).cxx_destruct;
- (bool)_compactsFirstList;
- (void)_didExplicitlyRemoveHiddenLists:(id)arg1;
- (void)_setDock:(id)arg1;
- (void)_setFavoriteTodayList:(id)arg1;
- (void)_setIgnoredList:(id)arg1;
- (void)_setTodayList:(id)arg1;
- (unsigned long long)_specialIndexOfList:(id)arg1;
- (bool)canAddIconCount:(unsigned long long)arg1 startingAtList:(id)arg2;
- (bool)canBounceIcon:(id)arg1;
- (bool)canEditDisplayName;
- (bool)canRemoveIcons;
- (bool)containsVisibleWidgetIconExcludingTodayList;
- (bool)containsWidgetIconExcludingTodayList;
- (id)delegate;
- (id)dock;
- (void)enumerateExtraListsUsingBlock:(id /* block */)arg1;
- (id)favoriteTodayList;
- (id)folderContainingIndexPath:(id)arg1 relativeIndexPath:(id*)arg2;
- (unsigned long long)hiddenIndexOfList:(id)arg1;
- (id)icons;
- (id)ignoredList;
- (unsigned long long)indexOfList:(id)arg1;
- (bool)isIconAtIndexPathInDock:(id)arg1;
- (bool)isIconAtIndexPathInDock:(id)arg1 includingDockFolders:(bool)arg2;
- (bool)isIconAtIndexPathInFavoriteTodayList:(id)arg1;
- (bool)isIconAtIndexPathInIgnoredList:(id)arg1;
- (bool)isIconAtIndexPathInTodayList:(id)arg1;
- (bool)isRootFolder;
- (bool)isValidListIndex:(unsigned long long)arg1;
- (id)listAtIndex:(unsigned long long)arg1;
- (id)model;
- (id)nodeDescriptionWithPrefix:(id)arg1;
- (id)nodeIdentifier;
- (void)removeList:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setModel:(id)arg1;
- (bool)supportsBadging;
- (bool)supportsDock;
- (bool)supportsIgnoredList;
- (bool)supportsTodayList;
- (bool)supportsTodayPage;
- (id)todayList;
- (unsigned long long)visibleIndexOfList:(id)arg1;

@end
