/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBWidgetIcon : SBLeafIcon {
    bool  _allowsExternalSuggestions;
    bool  _allowsSuggestions;
    <SBLeafIconDataSource> * _lastUserSelectedDataSource;
    unsigned long long  _stackChangeReason;
}

@property (nonatomic, retain) SBHWidget *activeWidget;
@property (nonatomic) bool allowsExternalSuggestions;
@property (nonatomic) bool allowsSuggestions;
@property (nonatomic, readonly) unsigned long long iconDataSourcesExcludingSuggestionsCount;
@property (nonatomic, retain) <SBLeafIconDataSource> *lastUserSelectedDataSource;
@property (nonatomic) unsigned long long stackChangeReason;
@property (nonatomic, readonly, copy) NSArray *widgets;

- (void).cxx_destruct;
- (id)_fallbackBestDataSource;
- (bool)_hasDataSourceThatIgnoresAllOtherDataSources;
- (id)activeWidget;
- (bool)allowsExternalSuggestions;
- (bool)allowsSuggestions;
- (bool)canBeAddedToMultiItemDrag;
- (bool)canBeReceivedByIcon;
- (bool)canReceiveGrabbedIcon;
- (id)copyWithUniqueLeafIdentifier;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (void)didAddIconDataSource:(id)arg1;
- (void)didRemoveIconDataSource:(id)arg1;
- (id)firstWidgetPassingTest:(id /* block */)arg1;
- (unsigned long long)iconDataSourcesExcludingSuggestionsCount;
- (id)initWithCHSAvocadoDescriptor:(id)arg1;
- (id)initWithCHSAvocadoDescriptors:(id)arg1;
- (id)initWithLeafIdentifier:(id)arg1 applicationBundleID:(id)arg2;
- (id)initWithUniqueLeafIdentifier;
- (id)initWithWidget:(id)arg1;
- (id)initWithWidgets:(id)arg1;
- (bool)isEqual:(id)arg1;
- (bool)isWidgetIcon;
- (bool)isWidgetStackIcon;
- (id)lastUserSelectedDataSource;
- (void)setActiveWidget:(id)arg1;
- (void)setAllowsExternalSuggestions:(bool)arg1;
- (void)setAllowsSuggestions:(bool)arg1;
- (void)setLastUserSelectedDataSource:(id)arg1;
- (void)setStackChangeReason:(unsigned long long)arg1;
- (unsigned long long)stackChangeReason;
- (unsigned long long)supportedGridSizeClasses;
- (bool)supportsConfiguration;
- (bool)supportsStackConfiguration;
- (id)widgets;

@end
