/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface SSArrayDataSourceItemsContainer : NSObject {
    NSArray * _items;
}

@property (nonatomic, copy) NSArray *items;

- (void).cxx_destruct;
- (id)initWithItems:(id)arg1;
- (id)items;
- (void)setItems:(id)arg1;

@end
