/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface SSBaseCollectionReusableView : UICollectionReusableView

+ (id)identifier;
+ (id)supplementaryViewForCollectionView:(id)arg1 kind:(id)arg2 indexPath:(id)arg3;

@end
