/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface SSBaseCollectionCell : UICollectionViewCell {
    bool  _didCompleteSetup;
}

@property (nonatomic) bool didCompleteSetup;

+ (id)cellForCollectionView:(id)arg1 indexPath:(id)arg2;
+ (id)identifier;

- (void)configureCell;
- (bool)didCompleteSetup;
- (void)setDidCompleteSetup:(bool)arg1;

@end
