/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface SSBaseTableCell : UITableViewCell

+ (id)cellForTableView:(id)arg1;
+ (long long)cellStyle;
+ (id)identifier;

- (void)configureCell;

@end
