/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface SSExpandingDataSource : SSSectionedDataSource {
    id /* block */  _collapsedSectionCountBlock;
}

@property (nonatomic, copy) id /* block */ collapsedSectionCountBlock;

- (void).cxx_destruct;
- (void)appendItems:(id)arg1 toSection:(long long)arg2;
- (id /* block */)collapsedSectionCountBlock;
- (id)expandedSectionIndexes;
- (void)insertItem:(id)arg1 atIndexPath:(id)arg2;
- (void)insertItems:(id)arg1 atIndexes:(id)arg2 inSection:(long long)arg3;
- (bool)isItemVisibleAtIndexPath:(id)arg1;
- (bool)isSectionExpandedAtIndex:(long long)arg1;
- (unsigned long long)numberOfCollapsedRowsInSection:(long long)arg1;
- (unsigned long long)numberOfItemsInSection:(long long)arg1;
- (void)performBatchUpdates:(id /* block */)arg1;
- (void)removeItemAtIndexPath:(id)arg1;
- (void)removeItemsAtIndexes:(id)arg1 inSection:(long long)arg2;
- (void)removeItemsInRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg1 inSection:(long long)arg2;
- (void)replaceItemAtIndexPath:(id)arg1 withItem:(id)arg2;
- (void)setCollapsedSectionCountBlock:(id /* block */)arg1;
- (void)setSection:(id)arg1 expanded:(bool)arg2;
- (void)setSectionAtIndex:(long long)arg1 expanded:(bool)arg2;
- (void)toggleSectionAtIndex:(long long)arg1;

@end
