/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFActionDrawerActionTableViewCell : UITableViewCell <WFModuleTitleViewDelegate> {
    WFAction * _action;
    WFActionDrawerCoordinator * _coordinator;
    WFDragController * _dragController;
    WFDragGestureRecognizer * _dragRecognizer;
    UIButton * _infoButton;
    WFModuleTitleView * _titleView;
    UIViewController * _viewController;
}

@property (nonatomic, retain) WFAction *action;
@property (nonatomic) WFActionDrawerCoordinator *coordinator;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) WFDragController *dragController;
@property (nonatomic, retain) WFDragGestureRecognizer *dragRecognizer;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) UIButton *infoButton;
@property (readonly) Class superclass;
@property (nonatomic, readonly) WFModuleTitleView *titleView;
@property (nonatomic) UIViewController *viewController;

+ (double)preferredHeight;

- (void).cxx_destruct;
- (id)action;
- (void)configureWithAction:(id)arg1 coordinator:(id)arg2 viewController:(id)arg3;
- (id)coordinator;
- (id)dragController;
- (id)dragRecognizer;
- (bool)gestureRecognizer:(id)arg1 shouldBeRequiredToFailByGestureRecognizer:(id)arg2;
- (bool)gestureRecognizerShouldBegin:(id)arg1;
- (id)infoButton;
- (void)infoButtonPressed;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (bool)isAccessibilityElement;
- (void)setAction:(id)arg1;
- (void)setCoordinator:(id)arg1;
- (void)setDragController:(id)arg1;
- (void)setDragRecognizer:(id)arg1;
- (void)setInfoButton:(id)arg1;
- (void)setViewController:(id)arg1;
- (id)titleView;
- (id)viewController;

@end
