/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFActionDrawerUtilities : NSObject

+ (id)activitySectionsForDonations:(id)arg1;
+ (id)appSectionsforActionSections:(id)arg1;
+ (id)appSectionsforDonations:(id)arg1;
+ (long long)cellTypeForIntent:(id)arg1;
+ (id)deduplicateAppSections:(id)arg1;
+ (id)localizedAppNames;
+ (id)suggestionSectionsforDonations:(id)arg1;

@end
