/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFActionDrawerResultsController : NSObject {
    WFActionRegistry * _actionRegistry;
    WFActionDrawerResults * _cachedSiriSuggestionsResults;
    HMHome * _home;
    NSObject<OS_dispatch_queue> * _searchQueue;
}

@property (nonatomic, readonly) WFActionRegistry *actionRegistry;
@property (nonatomic, readonly) WFActionDrawerResults *cachedSiriSuggestionsResults;
@property (nonatomic, readonly) HMHome *home;
@property (nonatomic, readonly) NSObject<OS_dispatch_queue> *searchQueue;

+ (id)localizedAppNames;

- (void).cxx_destruct;
- (id)actionRegistry;
- (id)actions;
- (id)actionsForCategory:(id)arg1;
- (id)cachedSiriSuggestionsResults;
- (bool)filteringForResidentCompatibleActions;
- (void)getHomeSectionsIncludingRelatedActions:(bool)arg1 completionHandler:(id /* block */)arg2;
- (void)getResultsForAppWithBundleIdentifier:(id)arg1 legacyIdentifier:(id)arg2 shouldFilterForAppsViewController:(bool)arg3 completionHandler:(id /* block */)arg4;
- (void)getResultsForCategory:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)getSiriSuggestedGroupedResultsRefreshingCache:(bool)arg1 completionHandler:(id /* block */)arg2;
- (void)getSiriSuggestedResultsForBundleIdentifier:(id)arg1 completionHandler:(id /* block */)arg2;
- (id)home;
- (id)initWithActionRegistry:(id)arg1 home:(id)arg2;
- (id)resultsForFavorites;
- (void)resultsForSearchQuery:(id)arg1 includingSiriSuggestedResults:(id)arg2 completionHandler:(id /* block */)arg3;
- (id)resultsForSuggestionsWithWorkflow:(id)arg1;
- (id)searchQueue;
- (id)suggestedCategoriesForContentClasses:(id)arg1;

@end
