/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFActionDrawerAppsDetailViewController : WFActionDrawerCompositeResultsViewController <UITableViewDataSource, UITableViewDelegate, WFActionDrawerStateConfigurable, WFActionDrawerStateRepresentable> {
    NSString * _bundleIdentifier;
    bool  _loading;
}

@property (nonatomic, readonly) NSString *bundleIdentifier;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) bool loading;
@property (nonatomic, readonly) WFActionDrawerState *state;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)bundleIdentifier;
- (unsigned long long)detailSectionForSection:(long long)arg1;
- (long long)detailSectionIndexForIndexPath:(long long)arg1;
- (id)initWithCoordinator:(id)arg1 bundleIdentifier:(id)arg2;
- (void)loadView;
- (bool)loading;
- (bool)moveToState:(id)arg1 animated:(bool)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)reloadViews;
- (void)setLoading:(bool)arg1;
- (id)state;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)viewDidLoad;

@end
