/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFActionDrawerCategoriesCollectionViewManager : NSObject <UICollectionViewDataSource, UICollectionViewDelegate, UICollectionViewDelegateFlowLayout> {
    UICollectionView * _collectionView;
    NSArray * _contentTypeCategories;
    WFActionDrawerCoordinator * _coordinator;
    WFActionDrawerCategoriesMetrics * _metrics;
    bool  _shouldUseVerticalStacking;
}

@property (nonatomic, readonly) UICollectionView *collectionView;
@property (nonatomic, readonly, copy) NSArray *contentTypeCategories;
@property (nonatomic, readonly) WFActionDrawerCoordinator *coordinator;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) WFActionDrawerCategoriesMetrics *metrics;
@property (nonatomic) bool shouldUseVerticalStacking;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_configureCell:(id)arg1 withContentTypeCategory:(id)arg2;
- (id)collectionView;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (struct CGSize { double x1; double x2; })collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (id)contentTypeCategories;
- (id)coordinator;
- (id)initWithCollectionView:(id)arg1 coordinator:(id)arg2 contentTypeCategories:(id)arg3 metrics:(id)arg4;
- (id)metrics;
- (void)setShouldUseVerticalStacking:(bool)arg1;
- (bool)shouldUseVerticalStacking;

@end
