/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFAutomationSwitchCell : UITableViewCell {
    UISwitch * _switchControl;
}

@property (nonatomic, readonly) UISwitch *switchControl;

- (void).cxx_destruct;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)prepareForReuse;
- (id)switchControl;

@end
