/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFCompactTextThumbnailViewController : WFCompactThumbnailViewController {
    NSString * _string;
    UITextView * _textView;
}

@property (nonatomic, readonly) NSString *string;
@property (nonatomic) UITextView *textView;

- (void).cxx_destruct;
- (double)contentHeightForWidth:(double)arg1;
- (id)initWithString:(id)arg1;
- (void)loadView;
- (unsigned long long)preferredContentMode;
- (void)setTextView:(id)arg1;
- (id)string;
- (id)textView;
- (void)traitCollectionDidChange:(id)arg1;

@end
