/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFCompactThumbnailViewController : UIViewController {
    <WFCompactThumbnailViewControllerDelegate> * _delegate;
}

@property (nonatomic) <WFCompactThumbnailViewControllerDelegate> *delegate;
@property (nonatomic, readonly) unsigned long long preferredContentMode;

- (void).cxx_destruct;
- (bool)_canShowWhileLocked;
- (double)contentHeightForWidth:(double)arg1;
- (id)delegate;
- (void)invalidateContentSize;
- (unsigned long long)preferredContentMode;
- (void)setDelegate:(id)arg1;

@end
