/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFCustomTableItem : WFTableItem {
    id /* block */  _configurationBlock;
    NSMapTable * _representedObjectChangeTargetSelectorTable;
}

@property (nonatomic, readonly, copy) id /* block */ configurationBlock;
@property (nonatomic, retain) id representedObject;
@property (nonatomic, readonly) NSMapTable *representedObjectChangeTargetSelectorTable;

- (void).cxx_destruct;
- (void)addRepresentedObjectChangeObserver:(id)arg1 action:(SEL)arg2;
- (id /* block */)configurationBlock;
- (void)configureCell:(id)arg1;
- (id)initWithCellClass:(Class)arg1 style:(long long)arg2 representedObject:(id)arg3 configurationBlock:(id /* block */)arg4;
- (bool)isEqual:(id)arg1;
- (id)representedObject;
- (id)representedObjectChangeTargetSelectorTable;
- (void)setRepresentedObject:(id)arg1;
- (void)setRepresentedObject:(id)arg1 updatingCell:(bool)arg2;

@end
