/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFEditAutomationWorkflowStorage : NSObject <WFWorkflowStorage> {
    WFWorkflowRecord * _lastSavedRecord;
    WFWorkflowRecord * _originalRecord;
    WFWorkflowReference * _reference;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, copy) WFWorkflowRecord *lastSavedRecord;
@property (nonatomic, copy) WFWorkflowRecord *originalRecord;
@property (nonatomic, readonly) WFWorkflowReference *reference;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)initWithReference:(id)arg1 originalRecord:(id)arg2;
- (id)lastSavedRecord;
- (id)originalRecord;
- (id)reference;
- (bool)reloadRecord:(id)arg1 error:(id*)arg2;
- (bool)saveRecord:(id)arg1 error:(id*)arg2;
- (void)setLastSavedRecord:(id)arg1;
- (void)setOriginalRecord:(id)arg1;

@end
