/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFGalleryService : NSObject {
    WFAccessResource * _accessResource;
    ICApp * _app;
    WFImage * _icon;
    NSString * _name;
}

@property (nonatomic, readonly) WFAccessResource *accessResource;
@property (nonatomic, readonly) ICApp *app;
@property (nonatomic, readonly) WFImage *icon;
@property (nonatomic, readonly) NSString *name;

+ (id)serviceWithAccessResource:(id)arg1;
+ (id)serviceWithApp:(id)arg1;
+ (id)servicesForWorkflow:(id)arg1;

- (void).cxx_destruct;
- (id)accessResource;
- (id)app;
- (id)description;
- (unsigned long long)hash;
- (id)icon;
- (bool)isEqual:(id)arg1;
- (void)loadIconWithCompletionHandler:(id /* block */)arg1;
- (id)name;

@end
