/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFSettingsFieldCell : WFSettingsCell {
    double  _offsetX;
    UITextField * _textField;
}

@property (nonatomic) double offsetX;
@property (nonatomic, readonly) UITextField *textField;

- (void).cxx_destruct;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)layoutSubviews;
- (double)offsetX;
- (void)setOffsetX:(double)arg1;
- (id)textField;

@end
