/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFShowAlertDialogViewController : WFCompactDialogViewController

- (void)loadView;

@end
