/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFTextFieldTableItem : WFCustomTableItem {
    bool  _becomeFirstResponderOnNextConfigure;
    UITextField * _lastConfiguredTextField;
    NSString * _primaryText;
    id /* block */  _textFieldSetup;
}

@property (nonatomic) bool becomeFirstResponderOnNextConfigure;
@property (nonatomic) UITextField *lastConfiguredTextField;
@property (nonatomic, readonly) NSString *primaryText;
@property (nonatomic, readonly) id /* block */ textFieldSetup;

+ (id)itemWithPrimaryText:(id)arg1 initialValue:(id)arg2 textFieldSetup:(id /* block */)arg3;

- (void).cxx_destruct;
- (void)activate;
- (void)activateNextItemIfPossible;
- (bool)becomeFirstResponderOnNextConfigure;
- (void)configureCell:(id)arg1;
- (id)lastConfiguredTextField;
- (id)primaryText;
- (void)setBecomeFirstResponderOnNextConfigure:(bool)arg1;
- (void)setLastConfiguredTextField:(id)arg1;
- (id /* block */)textFieldSetup;
- (void)textFieldTextDidChange:(id)arg1;

@end
