/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFThinWorkflowTableViewCell : WFInfoButtonTableViewCell

- (void)applyWorkflowIcon:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)setGalleryWorkflow:(id)arg1;
- (void)setWorkflow:(id)arg1;

@end
