/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFTriggerComposeViewController : WFComposeViewController {
    unsigned long long  _mode;
    <WFTriggerComposeViewControllerDelegate> * delegate;
}

@property (nonatomic) <WFTriggerComposeViewControllerDelegate> *delegate;
@property (nonatomic, readonly) unsigned long long mode;

- (void).cxx_destruct;
- (id)delegate;
- (void)didTapNext:(id)arg1;
- (void)dismissForTutorial:(bool)arg1 completionHandler:(id /* block */)arg2;
- (id)doneBarButtonItem;
- (id)emptyStateString;
- (id)initWithWorkflow:(id)arg1 mode:(unsigned long long)arg2 database:(id)arg3;
- (bool)isModalInPresentation;
- (unsigned long long)mode;
- (unsigned long long)navigationUpdateBehavior;
- (void)setDelegate:(id)arg1;
- (void)viewDidLoad;
- (void)willMoveToParentViewController:(id)arg1;

@end
