/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFWorkflowConflictViewController : UITableViewController <UINavigationControllerDelegate> {
    WFWorkflowConflict * _conflict;
    <WFWorkflowConflictViewControllerDelegate> * _delegate;
    UIBarButtonItem * _keepItem;
    WFWorkflow * _workflowBeingPreviewed;
}

@property (nonatomic, readonly) WFWorkflowConflict *conflict;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <WFWorkflowConflictViewControllerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) UIBarButtonItem *keepItem;
@property (readonly) Class superclass;
@property (nonatomic, retain) WFWorkflow *workflowBeingPreviewed;

- (void).cxx_destruct;
- (void)cancelPressed;
- (id)conflict;
- (id)delegate;
- (id)initWithConflict:(id)arg1;
- (id)keepItem;
- (void)keepPressed;
- (void)navigationController:(id)arg1 didShowViewController:(id)arg2 animated:(bool)arg3;
- (void)setDelegate:(id)arg1;
- (void)setKeepItem:(id)arg1;
- (void)setWorkflowBeingPreviewed:(id)arg1;
- (void)tableView:(id)arg1 accessoryButtonTappedForRowWithIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)updateKeepButton;
- (void)viewDidLoad;
- (id)workflowBeingPreviewed;
- (id)workflowForRow:(unsigned long long)arg1;

@end
