/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFWorkflowSettingsLayoutMetrics : NSObject {
    UITraitCollection * _traitCollection;
}

@property (nonatomic, readonly) UIFont *textFieldFont;
@property (nonatomic, readonly) struct CGSize { double x1; double x2; } tileSize;
@property (nonatomic, retain) UITraitCollection *traitCollection;
@property (nonatomic, readonly) UIFont *typeSelectionTitleFont;
@property (nonatomic, readonly) UIFont *typeSelectionTypeLabelFont;

- (void).cxx_destruct;
- (id)baseFont;
- (id)initWithTraitCollection:(id)arg1;
- (id)scaledFont;
- (double)scaledValueForValue:(double)arg1;
- (void)setTraitCollection:(id)arg1;
- (id)textFieldFont;
- (struct CGSize { double x1; double x2; })tileSize;
- (id)traitCollection;
- (id)typeSelectionTitleFont;
- (id)typeSelectionTypeLabelFont;

@end
