/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface _SBDashBoardSpotlightViewController : SBSpotlightMultiplexingViewController {
    <_SBDashBoardSpotlightViewControllerDelegate> * _delegate;
}

@property (nonatomic) <_SBDashBoardSpotlightViewControllerDelegate> *delegate;

- (void).cxx_destruct;
- (bool)_canShowWhileLocked;
- (id)delegate;
- (unsigned long long)level;
- (unsigned long long)remoteSearchViewPresentationSource;
- (void)setDelegate:(id)arg1;

@end
