/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface _SBFullScreenSwitcherLiveContentOverlayContext : NSObject {
    <SBSwitcherLiveContentOverlay> * _overlay;
    long long  _overlayType;
}

@property (nonatomic, readonly) <SBSwitcherLiveContentOverlay> *overlay;
@property (nonatomic, readonly) long long overlayType;

- (void).cxx_destruct;
- (id)initWithOverlay:(id)arg1 overlayType:(long long)arg2;
- (id)overlay;
- (long long)overlayType;

@end
