/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface _SBLoadApplicationResult : NSObject {
    NSString * _errorDescription;
    bool  _success;
    bool  _update;
}

- (void).cxx_destruct;

@end
