/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBAlertItemWindow : SBSecureMainScreenActiveInterfaceOrientationWindow {
    SBAlertLayoutPresentationVerifier * _alertLayoutPresentationVerifier;
}

@property (nonatomic) SBAlertLayoutPresentationVerifier *alertLayoutPresentationVerifier;

- (void).cxx_destruct;
- (bool)_canBecomeKeyWindow;
- (id)alertLayoutPresentationVerifier;
- (id)initWithDebugName:(id)arg1 alertLayoutPresentationVerifier:(id)arg2;
- (void)setAlertLayoutPresentationVerifier:(id)arg1;
- (void)setBounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)setCenter:(struct CGPoint { double x1; double x2; })arg1;
- (void)setFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)setTransform:(struct CGAffineTransform { double x1; double x2; double x3; double x4; double x5; double x6; })arg1;

@end
