/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBAlertImageHeaderViewController : UIViewController {
    double  _height;
    UIImage * _image;
}

- (void).cxx_destruct;
- (id)initWithImage:(id)arg1 height:(double)arg2;
- (void)loadView;

@end
