/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBApplicationIcon : SBLeafIcon {
    SBApplication * _application;
}

+ (bool)canGenerateIconsInBackground;

- (void).cxx_destruct;
- (void)_noteActiveDataSourceDidChangeAndReloadIcon:(bool)arg1;
- (id)application;
- (id)automationID;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)folderFallbackTitle;
- (id)folderTitleOptions;
- (id)iTunesCategoriesOrderedByRelevancy;
- (id)initWithApplication:(id)arg1;
- (bool)isApplicationIcon;
- (bool)isEqual:(id)arg1;
- (void)possibleUserTapBeganWithAbsoluteTime:(unsigned long long)arg1 andContinuousTime:(unsigned long long)arg2;
- (void)possibleUserTapDidCancel;
- (void)setBadge:(id)arg1;
- (id)tags;

@end
