/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBAppUnderFloatingSwitcherTransitionSwitcherModifier : SBTransitionSwitcherModifier

- (id)liveContentRasterizationAttributesForAppLayout:(id)arg1;

@end
