/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBAppClientSettingObserverContext : NSObject {
    SBApplication * _app;
    UIApplicationSceneClientSettings * _oldClientSettings;
    FBScene * _scene;
    SBDeviceApplicationSceneHandle * _sceneHandle;
    UIApplicationSceneSettings * _settings;
    FBSSceneTransitionContext * _transition;
    UIApplicationSceneClientSettings * _updatedClientSettings;
}

- (void).cxx_destruct;

@end
