/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBApplicationLaunchNotifyAirplaneModeAlertItem : SBApplicationLaunchNotifyAlertItem {
    bool  _usesCellNetwork;
}

- (void)configure:(bool)arg1 requirePasscodeForActions:(bool)arg2;
- (id)initWithApplication:(id)arg1;

@end
