/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBAssistantWindow : SBWindow {
    bool  _touchesPassThroughToSpringBoard;
}

@property (nonatomic, readonly) SBAssistantRootViewController *assistantRootViewController;
@property (nonatomic) bool touchesPassThroughToSpringBoard;

+ (bool)_isSecure;
+ (id)defaultLayoutStrategy;
+ (bool)sb_autorotates;

- (bool)_canBecomeKeyWindow;
- (id)_hitTest:(struct CGPoint { double x1; double x2; })arg1 withEvent:(id)arg2 windowServerHitTestWindow:(id)arg3;
- (id)assistantRootViewController;
- (void)dealloc;
- (id)hitTest:(struct CGPoint { double x1; double x2; })arg1 withEvent:(id)arg2;
- (id)initWithScreen:(id)arg1 layoutStrategy:(id)arg2 debugName:(id)arg3 scene:(id)arg4;
- (bool)isOpaque;
- (void)setTouchesPassThroughToSpringBoard:(bool)arg1;
- (bool)touchesPassThroughToSpringBoard;

@end
