/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBBackgroundFetchExternalRequest : NSObject {
    UIFetchContentInBackgroundAction * _action;
    SBBackgroundFetchTask * _task;
}

- (void).cxx_destruct;
- (void)dealloc;

@end
