/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBClawGestureMetricData : SBAWDMetricData {
    bool  _didPressLock;
    bool  _didPressVolumeDown;
    bool  _didPressVolumeUp;
    bool  _didTriggerSOS;
    unsigned long long  _duration;
}

@end
