/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBDashBoardSpotlightViewController : SBHomeGestureDismissableCoverSheetViewController <SBViewControllerTransitionContextDelegate, _SBDashBoardSpotlightViewControllerDelegate> {
    SBSearchBackdropView * _backdropView;
    <SBDashBoardSpotlightViewControllerDelegate> * _delegate;
    FBDisplayLayoutTransition * _displayLayoutTransition;
    UIViewController<SBUISpotlightInitiating> * _initiatingViewController;
    _UILegibilitySettings * _spotlightLegibilitySettings;
    _SBDashBoardSpotlightViewController * _spotlightViewController;
}

@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <SBDashBoardSpotlightViewControllerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) FBDisplayLayoutTransition *displayLayoutTransition;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) UIViewController<SBUISpotlightInitiating> *initiatingViewController;
@property (nonatomic) <SPUIRemoteSearchViewDelegate> *spotlightDelegate;
@property (nonatomic, retain) _UILegibilitySettings *spotlightLegibilitySettings;
@property (nonatomic, retain) _SBDashBoardSpotlightViewController *spotlightViewController;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (bool)_initiallyTransitioningToSpotlight:(id)arg1;
- (bool)_isTransitioning;
- (bool)_shouldCancelInteractiveDismissGesture:(id)arg1;
- (bool)_transitioningIntoSpotlight:(id)arg1;
- (void)aggregateBehavior:(id)arg1;
- (id)delegate;
- (id)displayLayoutElementIdentifier;
- (id)displayLayoutTransition;
- (bool)handleEvent:(id)arg1;
- (long long)homeGestureParticipantIdentifier;
- (id)init;
- (id)initiatingViewController;
- (void)performCustomTransitionToVisible:(bool)arg1 withAnimationSettings:(id)arg2 completion:(id /* block */)arg3;
- (bool)presentationCancelsTouches;
- (long long)presentationStyle;
- (long long)presentationTransition;
- (long long)presentationType;
- (unsigned long long)remoteSearchViewPresentationSourceForSpotlightViewController:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setDisplayLayoutTransition:(id)arg1;
- (void)setInitiatingViewController:(id)arg1;
- (void)setSpotlightDelegate:(id)arg1;
- (void)setSpotlightLegibilitySettings:(id)arg1;
- (void)setSpotlightViewController:(id)arg1;
- (bool)shouldAutomaticallyForwardAppearanceMethods;
- (bool)shouldDismissForHomeGestureRecognizer:(id)arg1;
- (id)spotlightDelegate;
- (id)spotlightLegibilitySettings;
- (unsigned long long)spotlightMultiplexingLevelForSpotlightViewController:(id)arg1;
- (id)spotlightViewController;
- (id)transitionContextToShowSpotlight:(bool)arg1 animated:(bool)arg2 interactive:(bool)arg3;
- (void)transitionDidFinish:(id)arg1;
- (void)transitionDidReverse:(id)arg1;
- (void)transitionWillBegin:(id)arg1;
- (void)transitionWillFinish:(id)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(bool)arg1;
- (void)viewWillLayoutSubviews;
- (bool)wouldHandleButtonEvent:(id)arg1;

@end
