/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBEmitSBEventSwitcherEventResponse : SBSwitcherModifierEventResponse {
    unsigned long long  _eventType;
    NSDictionary * _payload;
}

@property (nonatomic, readonly) unsigned long long eventType;
@property (nonatomic, readonly) NSDictionary *payload;

- (void).cxx_destruct;
- (unsigned long long)eventType;
- (id)initWithSBEventWithEventType:(unsigned long long)arg1 payload:(id)arg2;
- (id)payload;
- (long long)type;

@end
