/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBFixedLayoutModeSwitcherModifier : SBSwitcherModifier {
    long long  _updateMode;
}

- (id)animationAttributesForLayoutElement:(id)arg1;
- (id)initWithUpdateMode:(long long)arg1;

@end
