/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBHomeScreenService : NSObject <BSServiceConnectionListenerDelegate, SBSHomeScreenServiceClientToServerInterface> {
    NSMutableSet * _activeConnections;
    FBServiceClientAuthenticator * _addWidgetToTodayViewAuthenticator;
    FBServiceClientAuthenticator * _addsNewIconsToHomeScreenAuthenticator;
    FBServiceClientAuthenticator * _appLibraryRequestUpdateAuthenticator;
    FBServiceClientAuthenticator * _configurationAuthenticator;
    BSServiceConnectionListener * _connectionListener;
    FBServiceClientAuthenticator * _displayedDateAuthenticator;
    FBServiceClientAuthenticator * _homeScreenBundleIdentifiersAuthenticator;
    SBIconController * _iconController;
    FBServiceClientAuthenticator * _iconFolderPathLookupAuthenticator;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _lock;
    FBServiceClientAuthenticator * _lowDensityLayoutAuthenticator;
    FBServiceClientAuthenticator * _requestSuggestedAppAuthenticator;
    FBServiceClientAuthenticator * _resetHomeScreenLayoutAuthenticator;
    FBServiceClientAuthenticator * _showsBadgesInAppLibraryAuthenticator;
}

@property (nonatomic, readonly) NSMutableSet *activeConnections;
@property (nonatomic, readonly) FBServiceClientAuthenticator *addWidgetToTodayViewAuthenticator;
@property (nonatomic, readonly) FBServiceClientAuthenticator *addsNewIconsToHomeScreenAuthenticator;
@property (nonatomic, copy) NSNumber *addsNewIconsToHomeScreenValue;
@property (nonatomic, readonly, copy) NSArray *allHomeScreenApplicationBundleIdentifiers;
@property (nonatomic, readonly, copy) NSArray *allHomeScreenApplicationPlaceholderBundleIdentifiers;
@property (nonatomic, readonly) FBServiceClientAuthenticator *appLibraryRequestUpdateAuthenticator;
@property (nonatomic, readonly) FBServiceClientAuthenticator *configurationAuthenticator;
@property (nonatomic, readonly) BSServiceConnectionListener *connectionListener;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) FBServiceClientAuthenticator *displayedDateAuthenticator;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) FBServiceClientAuthenticator *homeScreenBundleIdentifiersAuthenticator;
@property (nonatomic, readonly) SBIconController *iconController;
@property (nonatomic, readonly) FBServiceClientAuthenticator *iconFolderPathLookupAuthenticator;
@property (nonatomic, copy) NSNumber *lowDensityIconLayoutEnabledValue;
@property (nonatomic, readonly) FBServiceClientAuthenticator *lowDensityLayoutAuthenticator;
@property (nonatomic, readonly) FBServiceClientAuthenticator *requestSuggestedAppAuthenticator;
@property (nonatomic, readonly) FBServiceClientAuthenticator *resetHomeScreenLayoutAuthenticator;
@property (nonatomic, readonly) FBServiceClientAuthenticator *showsBadgesInAppLibraryAuthenticator;
@property (nonatomic, copy) NSNumber *showsBadgesInAppLibraryValue;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_requestAppLibraryUpdate:(id)arg1 reason:(id)arg2 optionalCompletionHandler:(id /* block */)arg3;
- (id)activeConnections;
- (id)addWidgetToTodayViewAuthenticator;
- (void)addWidgetToTodayViewWithBundleIdentifier:(id)arg1;
- (id)addsNewIconsToHomeScreenAuthenticator;
- (id)addsNewIconsToHomeScreenValue;
- (id)allHomeScreenApplicationBundleIdentifiers;
- (id)allHomeScreenApplicationPlaceholderBundleIdentifiers;
- (id)appLibraryRequestUpdateAuthenticator;
- (void)changeDisplayedDateOffsetOverride:(id)arg1;
- (void)changeDisplayedDateOverride:(id)arg1;
- (id)configurationAuthenticator;
- (id)configureCategoryMapProviderToUseCategoryMapAtURL:(id)arg1;
- (void)configureDeweyEachAppHasItsOwnCategory;
- (void)configureDeweyOneCategoryWithAllApps;
- (id)connectionListener;
- (bool)debugContinuityWithBadgeType:(id)arg1;
- (id)displayedDateAuthenticator;
- (id)folderPathToIconWithBundleIdentifier:(id)arg1;
- (oneway void)forbidApplicationBundleIdentifierFromLibrary:(id)arg1 withCompletion:(id /* block */)arg2;
- (bool)hasWidgetWithBundleIdentifier:(id)arg1;
- (id)homeScreenBundleIdentifiersAuthenticator;
- (id)iconController;
- (id)iconFolderPathLookupAuthenticator;
- (void)ignoreAllApps;
- (id)initWithIconController:(id)arg1;
- (void)listener:(id)arg1 didReceiveConnection:(id)arg2 withContext:(id)arg3;
- (id)lowDensityIconLayoutEnabledValue;
- (id)lowDensityLayoutAuthenticator;
- (void)organizeAllIconsAcrossPagesWithPageCount:(id)arg1;
- (void)organizeAllIconsIntoFoldersWithPageCount:(id)arg1;
- (void)overrideBadgeValue:(id)arg1 forBundleIdentifier:(id)arg2;
- (void)refreshAppLibrary:(id)arg1 reason:(id)arg2;
- (void)reloadIcons;
- (void)removeAllWidgets;
- (void)requestAppLibraryUpdate:(id)arg1 reason:(id)arg2 completion:(id /* block */)arg3;
- (id)requestSuggestedAppAuthenticator;
- (oneway void)requestSuggestedApplicationWithBundleIdentifier:(id)arg1 assertionPort:(id)arg2 completion:(id /* block */)arg3;
- (oneway void)resetCategoriesLayoutWithCompletion:(id /* block */)arg1;
- (id)resetHomeScreenLayoutAuthenticator;
- (oneway void)resetHomeScreenLayoutWithCompletion:(id /* block */)arg1;
- (void)runDownloadingIconTest;
- (oneway void)runFloatingDockStressTestWithCompletion:(id /* block */)arg1;
- (void)runRemoveAndRestoreIconTest;
- (void)setAddsNewIconsToHomeScreenValue:(id)arg1;
- (void)setLowDensityIconLayoutEnabledValue:(id)arg1;
- (void)setShowsBadgesInAppLibraryValue:(id)arg1;
- (id)showsBadgesInAppLibraryAuthenticator;
- (id)showsBadgesInAppLibraryValue;
- (oneway void)unforbidApplicationBundleIdentifierFromLibrary:(id)arg1 withCompletion:(id /* block */)arg2;

@end
