/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBInlineGridSwitcherModifier : SBSwitcherModifier {
    NSString * _bundleIdentifier;
    double  _cardScale;
    struct CGSize { 
        double width; 
        double height; 
    }  _fixedCardSize;
    bool  _floating;
    _SBInlineGridFloorSwitcherModifier * _floorModifier;
    SBGridLayoutSwitcherModifier * _gridLayoutModifier;
    bool  _hasScrolledToInitialAppLayoutForTransitionIntoSwitcher;
    double  _initialCardScale;
    struct CGSize { 
        double width; 
        double height; 
    }  _initialCardSize;
    unsigned long long  _initialScrollAxis;
    unsigned long long  _ongoingAppLayoutRemovals;
    bool  _overlay;
    unsigned long long  _scrollAxis;
}

- (void).cxx_destruct;
- (id)appExposeAccessoryButtonsBundleIdentifier;
- (double)cardScale;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)didMoveToParentModifier:(id)arg1;
- (struct CGSize { double x1; double x2; })fixedCardSize;
- (id)gridLayoutModifier;
- (id)handleInlineTransitionEvent:(id)arg1;
- (id)handleRemovalEvent:(id)arg1;
- (id)handleTapAppLayoutEvent:(id)arg1;
- (id)handleTapOutsideToDismissEvent:(id)arg1;
- (id)initWithBundleIdentifier:(id)arg1 scrollAxis:(unsigned long long)arg2 fixedCardSize:(struct CGSize { double x1; double x2; })arg3 cardScale:(double)arg4 floating:(bool)arg5 overlay:(bool)arg6;
- (unsigned long long)numberOfRows;
- (unsigned long long)scrollAxis;
- (id)visibleAppLayouts;

@end
