/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBKeyboardBrightnessController : NSObject <SBHIDValueModifyingButtonSetArbiterDelegate> {
    SBHIDValueModifyingButtonSetArbiter * _buttonArbiter;
    KeyboardBrightnessClient * _keyboardBrightnessClient;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_adjustBacklightLevel:(bool)arg1;
- (void)_setBrightnessLevel:(float)arg1 showHUD:(bool)arg2;
- (void)buttonSetArbiter:(id)arg1 performActionForButtonPage:(unsigned short)arg2 usage:(unsigned short)arg3;
- (void)cancelBrightnessEvent;
- (void)handleBrightnessKeyPressEvent:(struct __IOHIDEvent { }*)arg1;
- (id)init;
- (void)setBrightnessLevel:(float)arg1;

@end
