/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBMedusaHostedKeyboardWindow : SBWindow {
    SBMedusaHostedKeyboardWindowLevelAssertion * _defaultWindowLevelAssertion;
    <UIScenePresenter> * _remoteHostedKeyboardScenePresenter;
    NSMutableArray * _windowLevelAssertions;
}

@property (nonatomic, retain) NSMutableArray *windowLevelAssertions;

+ (bool)_isSecure;
+ (bool)autorotates;

- (void).cxx_destruct;
- (void)_updateWindowLevel;
- (void)addWindowLevelAssertion:(id)arg1;
- (void)dealloc;
- (id)description;
- (id)hitTest:(struct CGPoint { double x1; double x2; })arg1 withEvent:(id)arg2;
- (id)initWithKeyboardScene:(id)arg1;
- (bool)isActive;
- (id)newWindowLevelAssertionWithPriority:(unsigned long long)arg1 windowLevel:(double)arg2;
- (void)removeWindowLevelAssertion:(id)arg1;
- (void)setHidden:(bool)arg1;
- (void)setWindowLevelAssertions:(id)arg1;
- (id)windowLevelAssertions;

@end
