/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBPIPSettings : PTSettings {
    SBPIPFluidTransitionsSettings * _fluidTransitionsSettings;
    SBPIPInteractionSettings * _interactionSettings;
}

@property (nonatomic, retain) SBPIPFluidTransitionsSettings *fluidTransitionsSettings;
@property (nonatomic, retain) SBPIPInteractionSettings *interactionSettings;

+ (id)settingsControllerModule;

- (void).cxx_destruct;
- (id)fluidTransitionsSettings;
- (id)interactionSettings;
- (void)setFluidTransitionsSettings:(id)arg1;
- (void)setInteractionSettings:(id)arg1;

@end
