/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBPPTRunner : NSObject <CCUIPPTHostDelegate, NCNotificationViewControllerObserving>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (id)sharedInstance;

- (id)_operationToDismissCoverSheetForTestWithName:(id)arg1;
- (id)_operationToPresentCoverSheetForTestWithName:(id)arg1;
- (void)_runCoverSheetDismissTestWithOptions:(id)arg1;
- (void)_runCoverSheetDismissToSafariTestWithOptions:(id)arg1;
- (void)_runCoverSheetPresentOverSafariTestWithOptions:(id)arg1;
- (void)_runCoverSheetPresentTestWithOptions:(id)arg1;
- (void)_runFloatingDockBringupTestWithOptions:(id)arg1;
- (void)_runFloatingDockDismissTestWithOptions:(id)arg1;
- (void)_runNotificationBannerTransitionTestWithOptions:(id)arg1;
- (void)_runNotificationClearLongLookTransitionTestWithOptions:(id)arg1;
- (void)_runNotificationReParkLongLookTransitionTestWithOptions:(id)arg1;
- (void)_runNotificationShortToLongLookTransitionTestWithOptions:(id)arg1;
- (void)_runSiriTestWithName:(id)arg1 options:(id)arg2;
- (void)_setCoverSheetPresentationManagerTransitionCallbacksForTestName:(id)arg1 operation:(id)arg2;
- (void)assistantDidAppear:(id)arg1;
- (void)assistantWillAppear:(id)arg1;
- (void)longLookDidDismissForNotificationViewController:(id)arg1;
- (void)longLookDidPresentForNotificationViewController:(id)arg1;
- (void)longLookWillDismissForNotificationViewController:(id)arg1;
- (void)longLookWillPresentForNotificationViewController:(id)arg1;
- (void)prepareForControlCenterPPTHostState:(unsigned long long)arg1 completionHandler:(id /* block */)arg2;
- (bool)runTestWithName:(id)arg1 options:(id)arg2;

@end
