/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBRecordingIndicatorManager : NSObject <PTSettingsKeyObserver, SBAppStatusBarAssertionManagerObserver, SBSensorActivityObserver, SBUIActiveOrientationObserver> {
    bool  _frontmostStatusBarOrIndicatorPartIsHidden;
    NSDate * _indicatorDisplayTime;
    bool  _indicatorIsHiddenForControlCenter;
    bool  _isIndicatorVisible;
    NSTimer * _minimumTimeOnScreenTimer;
    SBRecordingIndicatorViewController * _recordingIndicatorViewController;
    SBRecordingIndicatorViewController * _recordingIndicatorViewControllerUIKitStatusBarPortal;
    UIWindow * _recordingIndicatorWindow;
    UIWindow * _recordingIndicatorWindowUIKitStatusBarPortal;
    bool  _visibilityIsForcedByPrototypeSettings;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) bool isIndicatorVisible;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (bool)_allowStatusBarDelayForCameraApp:(id)arg1;
- (void)_updateIndicatorColorForSensorType:(long long)arg1;
- (void)_updateIndicatorStyleForSensorActivityAttributions:(id)arg1;
- (void)activeInterfaceOrientationDidChangeToOrientation:(long long)arg1 willAnimateWithDuration:(double)arg2 fromOrientation:(long long)arg3;
- (void)activeInterfaceOrientationWillChangeToOrientation:(long long)arg1;
- (void)activityDidChangeForSensorActivityDataProvider:(id)arg1;
- (void)controlCenterDidDismiss:(id)arg1;
- (void)controlCenterWillPresent:(id)arg1;
- (void)dataProviderDidUpdate:(id)arg1;
- (id)indicatorColorForSensorType:(long long)arg1;
- (id)initWithSensorActivityDataProvider:(id)arg1;
- (bool)isIndicatorVisible;
- (void)setIndicatorVisible:(bool)arg1;
- (void)setIndicatorVisible:(bool)arg1 allowStatusBarDelayForCameraApp:(bool)arg2;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (void)statusBarAssertionManager:(id)arg1 addStatusBarSettingsAssertion:(id)arg2;
- (void)statusBarAssertionManager:(id)arg1 removeStatusBarSettingsAssertion:(id)arg2;
- (void)updateRecordingIndicatorForStatusBarChanges;

@end
