/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBRecordingIndicatorView : UIView

- (id)init;
- (void)layoutSubviews;

@end
