/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBRootSettings : _UISettings {
    SBAttentionAwarenessSettings * _attentionAwarenessSettings;
    SBProximitySettings * _proximitySettings;
}

@property (retain) SBAttentionAwarenessSettings *attentionAwarenessSettings;
@property (retain) SBProximitySettings *proximitySettings;

- (void).cxx_destruct;
- (id)attentionAwarenessSettings;
- (id)proximitySettings;
- (void)setAttentionAwarenessSettings:(id)arg1;
- (void)setProximitySettings:(id)arg1;

@end
