/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBSceneLayoutElementAnimationWrapperView : UIView {
    SBApplicationSceneView * _appView;
    UIView<BSInvalidatable> * _contentView;
    SBLayoutElement * _layoutElement;
    SBOrientationTransformWrapperView * _orientedView;
}

@property (nonatomic, readonly) SBApplicationSceneView *applicationSceneViewIfExists;
@property (nonatomic, readonly) UIView<BSInvalidatable> *contentView;
@property (nonatomic, readonly) SBLayoutElement *layoutElement;

- (void).cxx_destruct;
- (bool)_shouldAnimatePropertyWithKey:(id)arg1;
- (void)addContentView:(id)arg1;
- (id)applicationSceneViewIfExists;
- (id)contentView;
- (id)description;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (id)initWithLayoutElement:(id)arg1 contentView:(id)arg2 orientation:(long long)arg3;
- (void)invalidate;
- (id)layoutElement;
- (void)layoutSubviews;
- (void)willMoveToSuperview:(id)arg1;

@end
