/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBSensorActivityDataProvider : NSObject <SBFSensorActivityDataProvider> {
    NSSet * _activeSensorActivityAttributions;
    STMediaStatusDomain * _mediaDomain;
    NSMutableSet * _observers;
    NSMutableArray * _recentAttributionExpirationTimers;
    NSMutableArray * _recentSensorActivityAttributions;
}

@property (nonatomic, copy) NSSet *activeSensorActivityAttributions;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) STMediaStatusDomain *mediaDomain;
@property (nonatomic, readonly, copy) SBSensorActivityAttribution *mostRecentSensorActivityAttribution;
@property (nonatomic, readonly, copy) NSMutableSet *observers;
@property (nonatomic, readonly, copy) NSMutableArray *recentAttributionExpirationTimers;
@property (nonatomic, readonly, copy) NSMutableArray *recentSensorActivityAttributions;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_handleMediaDomainData:(id)arg1;
- (void)_notifyObserversOfActivityChange;
- (void)_updateStateForActiveAttributions:(id)arg1;
- (id)activeSensorActivityAttributions;
- (void)addObserver:(id)arg1;
- (id)init;
- (id)initWithSystemStatusServer:(id)arg1;
- (id)mediaDomain;
- (id)mostRecentSensorActivityAttribution;
- (id)observers;
- (id)recentAttributionExpirationTimers;
- (id)recentSensorActivityAttributions;
- (void)removeObserver:(id)arg1;
- (void)setActiveSensorActivityAttributions:(id)arg1;

@end
