/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBSwitcherModifierEventResponse : SBChainableModifierEventResponse

+ (id)newEventResponse;

- (id)loggingCategory;
- (long long)type;

@end
