/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBViewMorphAnimator : NSObject <SBViewMorphAnimatorObserver> {
    BSTimer * _animationTimeoutTimer;
    bool  _automaticallyStartSourceAnimations;
    bool  _automaticallyStartTargetAnimations;
    long long  _completedSourceAnimations;
    long long  _completedTargetAnimations;
    long long  _direction;
    long long  _fromOrientation;
    bool  _invalidated;
    NSHashTable * _observers;
    id /* block */  _sourceAllAnimationsCompletionBlock;
    BSTimer * _sourceAnimationsCompletionContinueBlockTimeoutTimer;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  _sourceAppLayoutFrame;
    SBViewMorphAnimatorContentBlackCurtainView * _sourceBlackCurtainView;
    SBFFluidBehaviorSettings * _sourceClipAnimationSettings;
    SBViewMorphAnimatorContentClippingView * _sourceContentClippingView;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  _sourceContentClippingViewInitialFrame;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  _sourceContentFrame;
    bool  _sourceContentFrameWasAltered;
    UIView * _sourceContentView;
    double  _sourceCornerRadius;
    struct CGPoint { 
        double x; 
        double y; 
    }  _sourceFinalCenter;
    double  _sourceFinalScale;
    bool  _sourceScaleAndPositionEnded;
    UIView * _sourceView;
    long long  _startedSourceAnimations;
    long long  _startedTargetAnimations;
    SBFFluidBehaviorSettings * _targetClipAnimationSettings;
    SBViewMorphAnimatorContentClippingView * _targetContentClippingView;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  _targetContentClippingViewInitialFrame;
    UIView * _targetContentView;
    double  _targetCornerRadius;
    <SBViewMorphAnimatorDataSource> * _targetDataSource;
    bool  _targetExternalPlaceholderAllEnded;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  _targetFinalFrame;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  _targetSourcePinningFrame;
    UIView * _targetView;
    long long  _toOrientation;
    NSUUID * _uuid;
}

@property (nonatomic, retain) BSTimer *animationTimeoutTimer;
@property (nonatomic) bool automaticallyStartSourceAnimations;
@property (nonatomic) bool automaticallyStartTargetAnimations;
@property (nonatomic) long long completedSourceAnimations;
@property (nonatomic) long long completedTargetAnimations;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) long long direction;
@property (nonatomic) long long fromOrientation;
@property (readonly) unsigned long long hash;
@property (nonatomic) bool invalidated;
@property (nonatomic, retain) NSHashTable *observers;
@property (nonatomic, copy) id /* block */ sourceAllAnimationsCompletionBlock;
@property (nonatomic, retain) BSTimer *sourceAnimationsCompletionContinueBlockTimeoutTimer;
@property (nonatomic) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } sourceAppLayoutFrame;
@property (nonatomic, retain) SBViewMorphAnimatorContentBlackCurtainView *sourceBlackCurtainView;
@property (nonatomic, retain) SBFFluidBehaviorSettings *sourceClipAnimationSettings;
@property (nonatomic, retain) SBViewMorphAnimatorContentClippingView *sourceContentClippingView;
@property (nonatomic) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } sourceContentClippingViewInitialFrame;
@property (nonatomic, readonly) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } sourceContentFrame;
@property (nonatomic) bool sourceContentFrameWasAltered;
@property (nonatomic) UIView *sourceContentView;
@property (nonatomic, readonly) double sourceCornerRadius;
@property (nonatomic, readonly) struct CGPoint { double x1; double x2; } sourceFinalCenter;
@property (nonatomic, readonly) double sourceFinalScale;
@property (nonatomic) bool sourceScaleAndPositionEnded;
@property (nonatomic) UIView *sourceView;
@property (nonatomic) long long startedSourceAnimations;
@property (nonatomic) long long startedTargetAnimations;
@property (readonly) Class superclass;
@property (nonatomic, retain) SBFFluidBehaviorSettings *targetClipAnimationSettings;
@property (nonatomic, retain) SBViewMorphAnimatorContentClippingView *targetContentClippingView;
@property (nonatomic) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } targetContentClippingViewInitialFrame;
@property (nonatomic) UIView *targetContentView;
@property (nonatomic, readonly) double targetCornerRadius;
@property (nonatomic) <SBViewMorphAnimatorDataSource> *targetDataSource;
@property (nonatomic) bool targetExternalPlaceholderAllEnded;
@property (nonatomic, readonly) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } targetFinalFrame;
@property (nonatomic, readonly) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } targetSourcePinningFrame;
@property (nonatomic) UIView *targetView;
@property (nonatomic) long long toOrientation;
@property (nonatomic, readonly) NSUUID *uuid;

- (void).cxx_destruct;
- (void)_checkAnimationsDependencies:(id /* block */)arg1;
- (void)_continueSourceAnimationsCompletionPendingBlock;
- (void)_handleHandoffTimeout;
- (bool)_isReversed;
- (bool)_isTargetSourcePinningFrameEquivalentToSourceViewFrame;
- (void)_noteAnimatorWasCanceled;
- (void)_noteAnimatorWasInterrupted;
- (void)_noteDidEndAllAnimations;
- (void)_removeBlackCurtainView;
- (void)_removeMatchMoveAnimation;
- (void)_removeSourceClippingView;
- (void)_removeTargetClippingView;
- (void)_reset;
- (void)_resetAllAnimations;
- (struct CGPoint { double x1; double x2; })_source:(id)arg1 finalCenterWithFinalScale:(double)arg2 contentFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg3 targetFinalFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg4;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_sourceAppLayoutFrameForSourceView:(id)arg1 withTargetDataSource:(id)arg2;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_sourceContentFrameForSourceView:(id)arg1 withTargetDataSource:(id)arg2;
- (double)_sourceFinalScaleWithContentFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 targetFinalFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg2;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_targetInitialClippingBoundsWithSourceContentFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 sourceFinalScale:(double)arg2 targetViewBounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg3;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_targetSourcePinningFrameWithSourceContentFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 targetFinalFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg2;
- (void)_updateParameters;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_validatedSourceContentFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 withinSourceView:(id)arg2 withSourceFinalScale:(double)arg3;
- (void)addObserver:(id)arg1;
- (id)animationTimeoutTimer;
- (bool)automaticallyStartSourceAnimations;
- (bool)automaticallyStartTargetAnimations;
- (void)cancel:(id /* block */)arg1;
- (long long)completedSourceAnimations;
- (long long)completedTargetAnimations;
- (void)dealloc;
- (void)didEndSourceAnimations:(unsigned long long)arg1 finished:(bool)arg2 continueBlock:(id /* block */)arg3;
- (void)didEndTargetAnimations:(unsigned long long)arg1 finished:(bool)arg2 continueBlock:(id /* block */)arg3;
- (long long)direction;
- (long long)fromOrientation;
- (id)init;
- (id)initWithUUID:(id)arg1 direction:(long long)arg2;
- (void)interrupt:(id /* block */)arg1;
- (bool)invalidated;
- (void)noteSourceAnimationsDidEnd:(unsigned long long)arg1 finished:(bool)arg2 continueBlock:(id /* block */)arg3;
- (void)noteSourceAnimationsWillStart:(unsigned long long)arg1;
- (void)noteTargetAnimationsDidEnd:(unsigned long long)arg1 finished:(bool)arg2 continueBlock:(id /* block */)arg3;
- (void)noteTargetAnimationsWillStart:(unsigned long long)arg1;
- (void)noteWillRemoveTargeMatchMoveAnimationAtFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 withinSourceFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg2;
- (id)observers;
- (bool)preflightCheck;
- (void)setAnimationTimeoutTimer:(id)arg1;
- (void)setAutomaticallyStartSourceAnimations:(bool)arg1;
- (void)setAutomaticallyStartTargetAnimations:(bool)arg1;
- (void)setCompletedSourceAnimations:(long long)arg1;
- (void)setCompletedTargetAnimations:(long long)arg1;
- (void)setDirection:(long long)arg1;
- (void)setFromOrientation:(long long)arg1;
- (void)setInvalidated:(bool)arg1;
- (void)setObservers:(id)arg1;
- (void)setSourceAllAnimationsCompletionBlock:(id /* block */)arg1;
- (void)setSourceAnimationsCompletionContinueBlockTimeoutTimer:(id)arg1;
- (void)setSourceAppLayoutFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)setSourceBlackCurtainView:(id)arg1;
- (void)setSourceClipAnimationSettings:(id)arg1;
- (void)setSourceContentClippingView:(id)arg1;
- (void)setSourceContentClippingViewInitialFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)setSourceContentFrameWasAltered:(bool)arg1;
- (void)setSourceContentView:(id)arg1;
- (void)setSourceScaleAndPositionEnded:(bool)arg1;
- (void)setSourceView:(id)arg1;
- (void)setStartedSourceAnimations:(long long)arg1;
- (void)setStartedTargetAnimations:(long long)arg1;
- (void)setTargetClipAnimationSettings:(id)arg1;
- (void)setTargetContentClippingView:(id)arg1;
- (void)setTargetContentClippingViewInitialFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)setTargetContentView:(id)arg1;
- (void)setTargetDataSource:(id)arg1;
- (void)setTargetExternalPlaceholderAllEnded:(bool)arg1;
- (void)setTargetView:(id)arg1;
- (void)setToOrientation:(long long)arg1;
- (id /* block */)sourceAllAnimationsCompletionBlock;
- (id)sourceAnimationsCompletionContinueBlockTimeoutTimer;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })sourceAppLayoutFrame;
- (id)sourceBlackCurtainView;
- (id)sourceClipAnimationSettings;
- (id)sourceContentClippingView;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })sourceContentClippingViewInitialFrame;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })sourceContentFrame;
- (bool)sourceContentFrameWasAltered;
- (id)sourceContentView;
- (double)sourceCornerRadius;
- (struct CGPoint { double x1; double x2; })sourceFinalCenter;
- (double)sourceFinalScale;
- (bool)sourceScaleAndPositionEnded;
- (id)sourceView;
- (bool)startSourceAnimations:(unsigned long long)arg1;
- (bool)startTargetAnimations:(unsigned long long)arg1;
- (long long)startedSourceAnimations;
- (long long)startedTargetAnimations;
- (id)targetClipAnimationSettings;
- (id)targetContentClippingView;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })targetContentClippingViewInitialFrame;
- (id)targetContentView;
- (double)targetCornerRadius;
- (id)targetDataSource;
- (bool)targetExternalPlaceholderAllEnded;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })targetFinalFrame;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })targetSourcePinningFrame;
- (id)targetView;
- (long long)toOrientation;
- (id)uuid;
- (void)willStartSourceAnimations:(unsigned long long)arg1;
- (void)willStartTargetAnimations:(unsigned long long)arg1;

@end
