/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBWidgetMetricsServer : NSObject <BSServiceConnectionListenerDelegate, SBSWidgetMetricsServiceServerInterface> {
    FBServiceClientAuthenticator * _authenticator;
    NSMutableArray * _connections;
    BSServiceConnectionListener * _listener;
    <SBSWidgetMetricsProviding> * _metricsProvider;
    NSObject<OS_dispatch_queue> * _queue;
}

@property (nonatomic, readonly) FBServiceClientAuthenticator *authenticator;
@property (nonatomic, readonly, copy) NSMutableArray *connections;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) BSServiceConnectionListener *listener;
@property (nonatomic, readonly) <SBSWidgetMetricsProviding> *metricsProvider;
@property (nonatomic, readonly) NSObject<OS_dispatch_queue> *queue;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)authenticator;
- (id)connections;
- (void)dealloc;
- (id)init;
- (id)initWithMetricsProvider:(id)arg1;
- (id)listener;
- (void)listener:(id)arg1 didReceiveConnection:(id)arg2 withContext:(id)arg3;
- (id)metricsProvider;
- (id)previewMetricsSpecificationForBundleIdentifier:(id)arg1;
- (id)previewMetricsSpecificationForDeviceContext:(id)arg1 displayContext:(id)arg2 bundleIdentifier:(id)arg3;
- (id)queue;
- (id)systemMetricsForWidget:(id)arg1;

@end
