/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface CLAccount : NSObject <NSCoding, NSCopying> {
    bool  _alphaUser;
    NSURL * _domain;
    NSURL * _domainHomePage;
    NSString * _email;
    CLSocket * _socket;
    NSDate * _subscriptionExpiresAt;
    long long  _type;
    bool  _uploadsArePrivate;
}

@property (getter=isAlphaUser, nonatomic) bool alphaUser;
@property (nonatomic, retain) NSURL *domain;
@property (nonatomic, retain) NSURL *domainHomePage;
@property (nonatomic, copy) NSString *email;
@property (nonatomic, retain) CLSocket *socket;
@property (nonatomic, retain) NSDate *subscriptionExpiresAt;
@property (nonatomic) long long type;
@property (nonatomic) bool uploadsArePrivate;

+ (id)accountWithEmail:(id)arg1;

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)domain;
- (id)domainHomePage;
- (id)email;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithEmail:(id)arg1;
- (bool)isAlphaUser;
- (void)setAlphaUser:(bool)arg1;
- (void)setDomain:(id)arg1;
- (void)setDomainHomePage:(id)arg1;
- (void)setEmail:(id)arg1;
- (void)setSocket:(id)arg1;
- (void)setSubscriptionExpiresAt:(id)arg1;
- (void)setType:(long long)arg1;
- (void)setUploadsArePrivate:(bool)arg1;
- (id)socket;
- (id)subscriptionExpiresAt;
- (long long)type;
- (bool)uploadsArePrivate;

@end
