/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface CLWebItem : NSObject <NSCoding, NSCopying> {
    NSURL * _URL;
    NSURL * _contentURL;
    NSDate * _createdAt;
    NSDate * _deletedAt;
    NSURL * _href;
    UIImage * _icon;
    NSURL * _iconURL;
    NSString * _mimeType;
    NSString * _name;
    bool  _private;
    NSURL * _remoteURL;
    bool  _trashed;
    long long  _type;
    NSDate * _updatedAt;
    long long  _viewCount;
}

@property (nonatomic, retain) NSURL *URL;
@property (nonatomic, retain) NSURL *contentURL;
@property (nonatomic, retain) NSDate *createdAt;
@property (nonatomic, retain) NSDate *deletedAt;
@property (nonatomic, retain) NSURL *href;
@property (nonatomic, copy) UIImage *icon;
@property (nonatomic, retain) NSURL *iconURL;
@property (nonatomic, copy) NSString *mimeType;
@property (nonatomic, copy) NSString *name;
@property (getter=isPrivate, nonatomic) bool private;
@property (nonatomic, retain) NSURL *remoteURL;
@property (getter=isTrashed, nonatomic) bool trashed;
@property (nonatomic) long long type;
@property (nonatomic, retain) NSDate *updatedAt;
@property (nonatomic) long long viewCount;

+ (id)webItem;
+ (id)webItemWithName:(id)arg1;
+ (id)webItemWithName:(id)arg1 type:(long long)arg2 viewCount:(long long)arg3;

- (id)URL;
- (id)contentURL;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)createdAt;
- (void)dealloc;
- (id)deletedAt;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)href;
- (id)icon;
- (id)iconURL;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithName:(id)arg1;
- (id)initWithName:(id)arg1 type:(long long)arg2 viewCount:(long long)arg3;
- (bool)isPrivate;
- (bool)isTrashed;
- (id)mimeType;
- (id)name;
- (id)remoteURL;
- (void)setContentURL:(id)arg1;
- (void)setCreatedAt:(id)arg1;
- (void)setDeletedAt:(id)arg1;
- (void)setHref:(id)arg1;
- (void)setIcon:(id)arg1;
- (void)setIconURL:(id)arg1;
- (void)setMimeType:(id)arg1;
- (void)setName:(id)arg1;
- (void)setPrivate:(bool)arg1;
- (void)setRemoteURL:(id)arg1;
- (void)setTrashed:(bool)arg1;
- (void)setType:(long long)arg1;
- (void)setURL:(id)arg1;
- (void)setUpdatedAt:(id)arg1;
- (void)setViewCount:(long long)arg1;
- (long long)type;
- (id)updatedAt;
- (long long)viewCount;

@end
