/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFCustomDateFormatParameter : WFTextInputParameter

- (id)defaultSerializedRepresentation;
- (id)placeholder;

@end
