/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFDropboxAccessResource : WFAccountAccessResource

- (Class)accountClass;
- (id)associatedAppIdentifier;
- (id)initWithDefinition:(id)arg1;
- (void)makeAvailableAtGlobalLevelWithUserInterface:(id)arg1 completionHandler:(id /* block */)arg2;

@end
