/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFEvernoteAccessResource : WFAccessResource

// Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit

+ (id)evernoteCallbackScheme;
+ (id)evernoteSession;

- (id)associatedAppIdentifier;
- (bool)canLogOut;
- (void)dealloc;
- (unsigned long long)globalLevelStatus;
- (id)initWithDefinition:(id)arg1;
- (void)logOut;
- (id)protectedResourceDescription;
- (id)resourceName;
- (id)username;

// Image: /System/Library/PrivateFrameworks/ActionKitUI.framework/ActionKitUI

- (void)makeAvailableAtGlobalLevelWithUserInterface:(id)arg1 completionHandler:(id /* block */)arg2;

@end
