/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFFitnessWorkoutTypePickerParameter : WFEnumerationParameter {
    NSArray * _possibleStates;
}

- (void).cxx_destruct;
- (id)defaultSerializedRepresentation;
- (id)localizedLabelForPossibleState:(id)arg1;
- (id)localizedPlaceholder;
- (id)possibleStates;
- (Class)singleStateClass;

@end
