/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFGetPlaylistAction : WFAction

- (void)runWithInput:(id)arg1 error:(id*)arg2;

@end
