/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFGetHalfwayPointAction : WFAction

- (void)getPlacemarkFromCollection:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)runAsynchronouslyWithInput:(id)arg1;

@end
