/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFHandlePaymentIntentAction : WFHandleSystemIntentAction {
    WFImage * _icon;
}

- (void).cxx_destruct;
- (id)amountAboveMaximumErrorWithAmount:(id)arg1 sending:(bool)arg2;
- (id)amountBelowMinimumErrorWithAmount:(id)arg1 sending:(bool)arg2;
- (id)credentialsUnverifiedError;
- (id)currencyUnsupportedErrorWithAmount:(id)arg1;
- (id)errorFromConfirmResponse:(id)arg1 intent:(id)arg2;
- (id)errorFromHandleResponse:(id)arg1 intent:(id)arg2;
- (id)errorFromPaymentsResponse:(id)arg1 intent:(id)arg2;
- (id)errorFromResolutionResult:(id)arg1 forSlot:(id)arg2 onIntent:(id)arg3;
- (id)icon;
- (id)insufficientFundsError;
- (id)localizedDisplayableAppNameForBundleIdentifier:(id)arg1;
- (id)localizedKeyParameterDisplayName;
- (id)localizedPaymentServiceName;
- (id)minimumSupportedClientVersion;
- (id)noBankAccountError;
- (id)noRecipientAccountError:(bool)arg1;
- (bool)opensInApp;
- (void)resolveSlot:(id)arg1 withProcessedValue:(id)arg2 parameter:(id)arg3 input:(id)arg4 completion:(id /* block */)arg5;
- (id)showsWhenRunIfApplicable;

@end
