/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFImgurAccessResource : WFAccountAccessResource <WFActionEventObserver> {
    WFImgurUploadAction * _action;
    bool  _usesAccount;
}

@property (nonatomic) WFImgurUploadAction *action;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (nonatomic) bool usesAccount;

- (void).cxx_destruct;
- (Class)accountClass;
- (id)action;
- (void)action:(id)arg1 parameterStateDidChangeForKey:(id)arg2;
- (unsigned long long)globalLevelStatus;
- (void)setAction:(id)arg1;
- (void)setUsesAccount:(bool)arg1;
- (bool)usesAccount;

@end
