/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFMarkdownFromRichTextAction : WFAction

+ (bool)outputIsExemptFromTaintTrackingInheritance;

- (void)runAsynchronouslyWithInput:(id)arg1;

@end
