/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFMicrosoftTranslateSessionManager : NSObject {
    NSString * _apiKey;
    NSURL * _baseURL;
    NSURLSession * _session;
}

@property (nonatomic, copy) NSString *apiKey;
@property (nonatomic, readonly) NSURL *baseURL;
@property (nonatomic, readonly) NSURLSession *session;

- (void).cxx_destruct;
- (id)apiKey;
- (id)baseURL;
- (void)detectLanguagesOfStrings:(id)arg1 completion:(id /* block */)arg2;
- (void)getAccessTokenWithCompletion:(id /* block */)arg1;
- (void)getAvailableLanguages:(id /* block */)arg1;
- (id)init;
- (id)initWithSession:(id)arg1;
- (id)initWithSessionConfiguration:(id)arg1;
- (void)sendRequestWithURL:(id)arg1 queryParameters:(id)arg2 requestBody:(id)arg3 completion:(id /* block */)arg4;
- (id)session;
- (void)setApiKey:(id)arg1;
- (void)translateStrings:(id)arg1 fromLanguage:(id)arg2 intoLanguage:(id)arg3 completion:(id /* block */)arg4;

@end
