/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFNetworkInterface : NSObject {
    NSString * _interfaceName;
}

@property (nonatomic, readonly) NSString *BSSID;
@property (nonatomic, readonly) NSString *IPv4Address;
@property (nonatomic, readonly) NSString *IPv6Address;
@property (nonatomic, readonly) NSString *SSID;
@property (nonatomic, readonly) NSString *interfaceName;

+ (id)activeNetworkInterface;
+ (id)defaultNetworkInterfaces;
+ (id)networkInterfaceWithInterface:(id)arg1;
+ (id)wifiNetworkInterfaces;

- (void).cxx_destruct;
- (id)BSSID;
- (id)IPv4Address;
- (id)IPv6Address;
- (id)SSID;
- (struct __WiFiNetwork { }*)currentWiFiNetwork;
- (id)initWithInterface:(id)arg1;
- (id)interfaceName;
- (id)ipAddressForFamily:(unsigned char)arg1;

@end
