/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFOpenAppAction : WFAction

- (void)runAsynchronouslyWithInput:(id)arg1;
- (id)selectedApp;

@end
