/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFPlayPodcastAction : WFAction

- (id)contentNotFoundError;
- (id)errorPlayingPodcast:(unsigned int)arg1;
- (id)genericPlayPodcastFailedError;
- (id)getPlaybackURLForContentItem:(id)arg1;
- (id)localizedKeyParameterDisplayName;
- (void)playQueue:(struct _MRSystemAppPlaybackQueue { }*)arg1 onPlayerPath:(void*)arg2 completion:(id /* block */)arg3;
- (void)runAsynchronouslyWithInput:(id)arg1;
- (id)serializedParametersForDonatedIntent:(id)arg1 allowDroppingUnconfigurableValues:(bool)arg2;

@end
