/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFQuantityTypePickerParameter : WFEnumerationParameter {
    NSArray * _possibleStates;
}

@property (nonatomic, readonly) NSArray *possibleStates;

- (void).cxx_destruct;
- (id)localizedLabelForPossibleState:(id)arg1;
- (id)possibleStates;
- (Class)singleStateClass;

@end
