/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFRemoteServerAccessResourcePerWorkflowStateEntry : WFGranularAccessResourcePerWorkflowStateEntry

+ (id)valueKey;
+ (Class)valueTypeClass;

- (id)initWithURL:(id)arg1;

@end
