/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFRemoteServerAccessResourcePerWorkflowState : WFGranularAccessResourcePerWorkflowState

+ (Class)entryTypeClass;

- (id)initWithURLs:(id)arg1;

@end
