/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFSetFlashlightValueResolutionResult : INDoubleResolutionResult

+ (id)unsupportedForReason:(long long)arg1;

@end
