/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFSettingsClient : NSObject

+ (void)createClientWithCompletionHandler:(id /* block */)arg1;

@end
