/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFSetPlaybackDestinationAction : WFAction

- (id)errorFromRoutePickerError:(id)arg1;
- (id)errorUserInfoForRoutePickerErrorCode:(long long)arg1;
- (id)routeDescriptor;
- (void)runAsynchronouslyWithInput:(id)arg1;
- (id)subcategoryForCategory:(id)arg1;

@end
