/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFSearchLocalBusinessesAction : WFAction {
    MKLocalSearch * _localSearch;
}

@property (nonatomic, retain) MKLocalSearch *localSearch;

- (void).cxx_destruct;
- (void)cancel;
- (id)localSearch;
- (void)runAsynchronouslyWithInput:(id)arg1;
- (void)runSearchWithLocation:(id)arg1;
- (void)setLocalSearch:(id)arg1;
- (bool)shouldUseMetricSystem;

@end
