/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFSetDictionaryValueAction : WFAction

- (void)finishWithInput:(id)arg1 key:(id)arg2 value:(id)arg3;
- (void)runAsynchronouslyWithInput:(id)arg1;

@end
