/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFShowResultAction : WFAction

- (bool)getInputContentFromVariablesInParameterState:(id)arg1 context:(id)arg2 completionHandler:(id /* block */)arg3;
- (void)runAsynchronouslyWithInput:(id)arg1;

@end
