/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFSocialAction : WFShareExtensionAction

@property (nonatomic, readonly) NSString *postPrefix;

+ (id)userInterfaceProtocol;

- (void)convertAnimatedImagesToVideoWithInput:(id)arg1 completionHandler:(id /* block */)arg2;
- (bool)convertsAnimatedImagesToVideo;
- (id)postPrefix;
- (void)runAsynchronouslyWithInput:(id)arg1;
- (void)runWithoutUserInterfaceWithInput:(id)arg1;

@end
