/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFStorageServiceAction : WFAction

@property (nonatomic, readonly) <WFFileStorageService> *selectedStorageService;
@property (nonatomic, readonly) bool showsFilePicker;

- (id)filePathKey;
- (id)filenamePlaceholderText;
- (void)initializeParameters;
- (id)keywords;
- (id)outputContentClasses;
- (id)prioritizedParameterKeysForRemoteExecution;
- (id)requiredResources;
- (bool)requiresRemoteExecution;
- (void)runAsynchronouslyWithInput:(id)arg1;
- (void)runAsynchronouslyWithInput:(id)arg1 storageService:(id)arg2;
- (id)selectedStorageService;
- (void)selectedStorageServiceChanged;
- (bool)setParameterState:(id)arg1 forKey:(id)arg2;
- (id)showPickerKey;
- (bool)showsFilePicker;
- (bool)showsSettingsWhenResourcesUnavailable;
- (id)targetContentAttribution;
- (void)updatePathPrefix;

@end
