/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFSubscribeToPodcastAction : WFAction

- (id)contentNotFoundError;
- (id)errorSubscribingToPodcast:(unsigned int)arg1;
- (id)genericSubscribeFailedError;
- (void)runAsynchronouslyWithInput:(id)arg1;
- (void)subscribeToPodcast:(id)arg1 completion:(id /* block */)arg2;

@end
