/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFTextMatchResolutionResult : INObjectResolutionResult

+ (id)confirmationRequiredWithTextMatchToConfirm:(id)arg1;
+ (id)disambiguationWithTextMatchsToDisambiguate:(id)arg1;
+ (id)successWithResolvedTextMatch:(id)arg1;

@end
