/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFTrimVideoAction : WFAction

+ (id)userInterfaceProtocol;

- (void)runWithRemoteUserInterface:(id)arg1 input:(id)arg2;

@end
