/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFTrelloList : WFTrelloObject

+ (id)listWithName:(id)arg1;
+ (bool)supportsSecureCoding;

@end
