/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFWaitToReturnAction : WFAction <WFApplicationStateObserver>

- (void)applicationContext:(id)arg1 applicationStateDidChange:(long long)arg2;
- (void)finishRunningWithError:(id)arg1;
- (void)runAsynchronouslyWithInput:(id)arg1;

@end
