/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFWebAuthenticationSessionPresentationContext : NSObject <ASWebAuthenticationPresentationContextProviding> {
    <WFUserInterfaceHost> * _userInterface;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (nonatomic, readonly) <WFUserInterfaceHost> *userInterface;

- (void).cxx_destruct;
- (id)initWithUserInterface:(id)arg1;
- (id)presentationAnchorForWebAuthenticationSession:(id)arg1;
- (id)userInterface;

@end
