/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFWunderlistAccount : WFOAuth2Account

+ (id)clientID;
+ (id)clientSecret;
+ (id)localizedServiceName;
+ (id)redirectURI;
+ (id)serviceID;
+ (id)sessionManager;

@end
