/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFWunderlistList : MTLModel <MTLJSONSerializing, NSSecureCoding> {
    NSDate * _createdAt;
    long long  _listId;
    long long  _revision;
    NSString * _title;
}

@property (nonatomic, readonly) NSDate *createdAt;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly, copy) NSDictionary *dictionaryValue;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) long long listId;
@property (nonatomic, readonly) long long revision;
@property (readonly) Class superclass;
@property (nonatomic, readonly) NSString *title;

+ (id)JSONKeyPathsByPropertyKey;
+ (id)createdAtJSONTransformer;
+ (void)initialize;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)createdAt;
- (long long)listId;
- (long long)revision;
- (id)title;

@end
