/* Generated by RuntimeBrowser.
 */

@protocol CCUIControlCenterSystemAgent <NSObject>

@required

- (bool)isOrientationLocked;
- (bool)isRingerMuted;
- (bool)isUILocked;
- (void)lockOrientation;
- (void)setRingerMuted:(bool)arg1;
- (void)unlockOrientation;

@end
