/* Generated by RuntimeBrowser.
 */

@protocol CKTransactionalComponentDataSourceStateModifying <NSObject>

@required

- (CKTransactionalComponentDataSourceChange *)changeFromState:(CKTransactionalComponentDataSourceState *)arg1;

@end
