/* Generated by RuntimeBrowser.
 */

@protocol CSAdjunctListItemProviding <NSObject>

@required

- (SBSLockScreenContentAction *)action;
- (void)conformsToCSAdjunctListItemProviding;
- (UIViewController<CSAdjunctItemHosting> *)contentHost;
- (NSString *)identifier;
- (UIView *)platterView;
- (void)setContentHost:(UIViewController<CSAdjunctItemHosting> *)arg1;
- (void)setPlatterView:(UIView *)arg1;

@end
