/* Generated by RuntimeBrowser.
 */

@protocol CSCoverSheetViewControlling <CSAppearanceProviding, CSBehaviorProviding, CSPresentationProviding, CSEventHandling, CSCoverSheetParticipating, SBFIdleTimerBehaviorProviding>

@required

- (void)conformsToCSCoverSheetViewControlling;
- (long long)presentationAltitude;
- (long long)presentationPriority;
- (long long)presentationStyle;
- (long long)presentationTransition;
- (long long)presentationType;
- (<CSCoverSheetViewPresenting> *)presenter;
- (void)setPresenter:(id <CSCoverSheetViewPresenting>)arg1;

@end
