/* Generated by RuntimeBrowser.
 */

@protocol CSDateViewScrolling <NSObject>

@required

- (double)clippingOffset;
- (double)topContentInset;
- (void)updateAppearanceForHidden:(bool)arg1 offset:(struct CGPoint { double x1; double x2; })arg2;

@end
