/* Generated by RuntimeBrowser.
 */

@protocol CSPersistentContentLayoutProviding

@required

- (double)bottomContentInset;
- (double)dateBaselineToListY;
- (double)listMinY;
- (double)timeLabelBaselineY;
- (double)timeLabelOffsetForScrollPercent:(double)arg1;
- (double)timeToSubtitleLabelBaselineDifferenceY;
- (double)windowedAccessoryInset;

@end
