/* Generated by RuntimeBrowser.
 */

@protocol CSWallpaperOverlayHosting <NSObject>

@required

- (UIView<SBUIWallpaperOverlay> *)relinquishHostingOfWallpaperOverlay;
- (void)startHostingWallpaperOverlay:(UIView<SBUIWallpaperOverlay> *)arg1;

@end
