/* Generated by RuntimeBrowser.
 */

@protocol FHSSnapshotViewDelegate <NSObject>

@required

- (void)didDeselectView:(FHSViewSnapshot *)arg1;
- (void)didLongPressView:(FHSViewSnapshot *)arg1;
- (void)didSelectView:(FHSViewSnapshot *)arg1;

@end
