/* Generated by RuntimeBrowser.
 */

@protocol FLEXTableViewFiltering <FLEXSearchResultsUpdating>

@required

- (NSArray *)allSections;
- (NSArray *)makeSections;
- (NSArray *)nonemptySections;
- (NSArray *)sections;
- (void)setAllSections:(NSArray *)arg1;
- (void)setSections:(NSArray *)arg1;

@end
