/* Generated by RuntimeBrowser.
 */

@protocol FLEXFileBrowserSearchOperationDelegate <NSObject>

@required

- (void)fileBrowserSearchOperationResult:(NSArray *)arg1 size:(unsigned long long)arg2;

@end
