/* Generated by RuntimeBrowser.
 */

@protocol FLEXCollection <NSObject, NSFastEnumeration>

@required

- (id)copy;
- (unsigned long long)count;
- (id)mutableCopy;

@optional

- (NSArray *)allKeys;
- (NSArray *)allObjects;
- (id)objectAtIndexedSubscript:(unsigned long long)arg1;
- (id)objectForKeyedSubscript:(id)arg1;

@end
