/* Generated by RuntimeBrowser.
 */

@protocol FLEXObjectExplorerItem <NSObject>

@required

- (FLEXObjectExplorerDefaults *)defaults;
- (bool)isCallable;
- (bool)isEditable;
- (void)setDefaults:(FLEXObjectExplorerDefaults *)arg1;

@end
