/* Generated by RuntimeBrowser.
 */

@protocol FLEXDatabaseManager <NSObject>

@required

+ (id)managerForDatabase:(NSString *)arg1;

- (NSArray *)queryAllColumnsOfTable:(NSString *)arg1;
- (NSArray *)queryAllDataInTable:(NSString *)arg1;
- (NSArray *)queryAllTables;

@optional

- (FLEXSQLResult *)executeStatement:(NSString *)arg1;

@end
