/* Generated by RuntimeBrowser.
 */

@protocol HFSetupPairingPopup <NSObject>

@required

- (id)initWithPopupDelegate:(id <HFSetupPairingPopupDelegate>)arg1 setupAccessoryDescription:(HMSetupAccessoryDescription *)arg2;
- (<HFSetupPairingPopupDelegate> *)popupDelegate;
- (unsigned long long)popupType;
- (HMSetupAccessoryDescription *)setupAccessoryDescription;

@end
