/* Generated by RuntimeBrowser.
 */

@protocol HUBackgroundEffectViewGrouping <NSObject>

@required

- (void)backgroundEffectAddCaptureDependent:(UIVisualEffectView *)arg1;
- (void)backgroundEffectRemoveCaptureDependent:(UIVisualEffectView *)arg1;
- (UIVisualEffect *)sharedEffect;

@end
