/* Generated by RuntimeBrowser.
 */

@protocol HUContainedMediaAccessoriesGridViewControllerDelegate <NSObject>

@optional

- (UIViewController<HUDetailsPresentationDelegateHost> *)detailsViewControllerForContainedMediaAccessoryGridViewController:(HUContainedMediaAccessoriesGridViewController *)arg1 item:(HFItem *)arg2;

@end
