/* Generated by RuntimeBrowser.
 */

@protocol HUDashboardNavigationViewDelegate <NSObject>

@required

- (void)dashboardNavigationView:(HUDashboardNavigationView *)arg1 didTapHomeAppButton:(HUDashboardNavigationButton *)arg2;
- (void)dashboardNavigationView:(HUDashboardNavigationView *)arg1 didTapLargeTitleButton:(UIButton *)arg2;

@end
