/* Generated by RuntimeBrowser.
 */

@protocol NCNotificationManagementSuggestionDelegate <NSObject>

@required

- (void)notificationManagementContentProvider:(NCNotificationManagementContentProvider *)arg1 hasUpdatedContentForRequest:(NCNotificationRequest *)arg2;
- (void)notificationManagementContentProvider:(NCNotificationManagementContentProvider *)arg1 keepNotificationsForSectionIdentifierForNotificationRequest:(NCNotificationRequest *)arg2;

@end
