/* Generated by RuntimeBrowser.
 */

@protocol NCNotificationListViewScrollDelegate <NSObject>

@required

- (void)notificationListDidScroll:(NCNotificationListView *)arg1;
- (void)notificationListViewWillEndDragging:(NCNotificationListView *)arg1 withTargetContentOffset:(inout struct CGPoint { double x1; double x2; }*)arg2;
- (void)notificationListWillBeginDragging:(NCNotificationListView *)arg1;

@end
