/* Generated by RuntimeBrowser.
 */

@protocol PLExpandedPlatterViewDelegate <UIScrollViewDelegate>

@required

- (bool)associatedViewControllerDidAppearForExpandedPlatterView:(PLExpandedPlatterView *)arg1;

@end
