/* Generated by RuntimeBrowser.
 */

@protocol SBApplicationServerMultiwindowDelegate <SBApplicationServerDelegate>

@required

- (void)applicationServer:(SBApplicationServer *)arg1 client:(id <FBSServiceFacilityClientHandle>)arg2 showAllWindowsForBundleIdentifier:(NSString *)arg3;

@end
