/* Generated by RuntimeBrowser.
 */

@protocol SBAppSwitcherPageContentView <NSObject>

@required

- (bool)contentRequiresGroupOpacity;
- (double)cornerRadius;
- (void)invalidate;
- (bool)isActive;
- (bool)isVisible;
- (long long)orientation;
- (void)setActive:(bool)arg1;
- (void)setCornerRadius:(double)arg1;
- (void)setOrientation:(long long)arg1;
- (void)setVisible:(bool)arg1;

@optional

- (bool)hasSceneOverlayView;
- (void)setShouldUseBrightMaterial:(bool)arg1;
- (void)setShowingIconOverlayView:(bool)arg1;

@end
