/* Generated by RuntimeBrowser.
 */

@protocol SBApplicationSceneIdentityProviding <NSObject>

@required

- (FBSSceneIdentity *)newSceneIdentityForApplication:(SBApplication *)arg1;
- (FBSSceneIdentity *)sceneIdentityForApplication:(SBApplication *)arg1;
- (FBSSceneIdentity *)sceneIdentityForApplication:(SBApplication *)arg1 targetContentIdentifier:(NSString *)arg2;
- (FBSSceneIdentity *)sceneIdentityForApplication:(SBApplication *)arg1 uniqueIdentifier:(NSString *)arg2;
- (FBSSceneIdentity *)sceneIdentityForApplication:(SBApplication *)arg1 uniqueIdentifier:(NSString *)arg2 targetContentIdentifier:(NSString *)arg3;

@end
