/* Generated by RuntimeBrowser.
 */

@protocol SBDashBoardSpotlightViewControllerDelegate

@required

- (long long)homeGestureParticipantIdentifierForSpotlightViewController:(SBDashBoardSpotlightViewController *)arg1;
- (unsigned long long)remoteSearchViewPresentationSourceForSpotlightViewController:(SBDashBoardSpotlightViewController *)arg1;
- (unsigned long long)spotlightMultiplexingLevelForSpotlightViewController:(SBDashBoardSpotlightViewController *)arg1;

@end
