/* Generated by RuntimeBrowser.
 */

@protocol SBElasticAudioVolumeViewControllerDelegate <NSObject>

@required

- (void)elasticVolumeViewControllerNeedsDismissal:(SBElasticVolumeViewController *)arg1;

@end
