/* Generated by RuntimeBrowser.
 */

@protocol SBFluidSwitcherItemContainerReusable <NSObject>

@required

- (void)conformsToProtocolSBFluidSwitcherItemContainerReusable;
- (void)prepareForReuse;

@end
