/* Generated by RuntimeBrowser.
 */

@protocol SBFluidSwitcherItemContainerDelegate <NSObject>

@required

- (bool)canSelectContainer:(SBFluidSwitcherItemContainer *)arg1 numberOfTaps:(long long)arg2;
- (void)didSelectContainer:(SBFluidSwitcherItemContainer *)arg1;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })frameForPageViewOfContainer:(SBFluidSwitcherItemContainer *)arg1 fullyPresented:(bool)arg2;
- (long long)homeScreenInterfaceOrientation;
- (void)killContainer:(SBFluidSwitcherItemContainer *)arg1 forReason:(long long)arg2;
- (void)scrollViewKillingProgressUpdated:(double)arg1 ofContainer:(SBFluidSwitcherItemContainer *)arg2;
- (long long)switcherInterfaceOrientation;

@end
