/* Generated by RuntimeBrowser.
 */

@protocol SBFOverlayObserving

@required

- (void)overlayController:(id <SBFOverlayControlling>)arg1 didChangePresentationProgress:(double)arg2 fromLeading:(bool)arg3;
- (void)overlayController:(id <SBFOverlayControlling>)arg1 visibilityDidChange:(bool)arg2;
- (void)overlayControllerDidBeginChangingPresentationProgress:(id <SBFOverlayControlling>)arg1;

@end
