/* Generated by RuntimeBrowser.
 */

@protocol SBFWallpaperViewInternalObserver <NSObject>

@required

- (void)wallpaperView:(SBFWallpaperView *)arg1 didChangeZoomFactor:(double)arg2;
- (void)wallpaperViewDidChangeWantsRasterization:(SBFWallpaperView *)arg1;
- (void)wallpaperViewDidInvalidateBlurs:(SBFWallpaperView *)arg1;

@end
