/* Generated by RuntimeBrowser.
 */

@protocol SBHAddWidgetSheetGalleryItem <NSObject>

@required

- (UIColor *)accentColor;
- (UIColor *)backgroundColor;
- (UIColor *)mostInterestingColor;
- (NSString *)sbh_appName;
- (unsigned long long)sbh_supportedSizeClasses;
- (NSString *)sbh_widgetDescription;
- (NSString *)sbh_widgetName;

@end
