/* Generated by RuntimeBrowser.
 */

@protocol SBHIconViewConfigurationInteraction <NSObject>

@required

- (void)beginConfiguration;
- (<NSCopying><NSSecureCoding> *)configuration;
- (<SBHIconViewConfigurationInteractionDelegate> *)delegate;
- (void)endConfiguration;
- (void)endConfigurationImmediately;
- (void)setDelegate:(id <SBHIconViewConfigurationInteractionDelegate>)arg1;

@end
