/* Generated by RuntimeBrowser.
 */

@protocol SBHStackConfigurationInteractionDelegate <SBHIconViewConfigurationInteractionDelegate>

@required

- (SBHWidgetConfigurationInteraction *)widgetConfigurationInteractionForDataSource:(id <SBLeafIconDataSource>)arg1;

@end
