/* Generated by RuntimeBrowser.
 */

@protocol SBIconDragPreview

@required

- (unsigned long long)dragState;
- (void)draggingSourceCancelAnimationCompleted;
- (void)draggingSourceDroppedWithOperation:(unsigned long long)arg1;
- (void)dropDestinationAnimationCompleted;
- (SBIcon *)icon;
- (bool)iconAllowsLabelArea;
- (bool)iconCanShowCloseBox;
- (double)iconContentScale;
- (bool)iconIsEditing;
- (bool)isFlocked;
- (void)setDragState:(unsigned long long)arg1;
- (void)setFlocked:(bool)arg1;
- (void)setIcon:(SBIcon *)arg1;
- (void)setIconAllowsLabelArea:(bool)arg1;
- (void)setIconCanShowCloseBox:(bool)arg1;
- (void)setIconContentScale:(double)arg1;
- (void)setIconIsEditing:(bool)arg1;
- (void)setIconIsEditing:(bool)arg1 animated:(bool)arg2;
- (void)updateDestinationIconLocation:(NSString *)arg1 allowsLabelArea:(bool)arg2 animated:(bool)arg3;

@end
