/* Generated by RuntimeBrowser.
 */

@protocol SBIconViewCustomImageViewControlling <SBCrossfadingIconImageSource>

@required

- (struct SBIconImageInfo { struct CGSize { double x_1_1_1; double x_1_1_2; } x1; double x2; double x3; })iconImageInfo;
- (bool)isEditing;
- (void)setEditing:(bool)arg1;
- (void)setEditing:(bool)arg1 animated:(bool)arg2;
- (void)setIconImageInfo:(struct SBIconImageInfo { struct CGSize { double x_1_1_1; double x_1_1_2; } x1; double x2; double x3; })arg1;

@optional

- (void)addCustomImageViewControllerObserver:(id <SBIconViewCustomImageViewControllerObserving>)arg1;
- (NSArray *)applicationShortcutItems;
- (bool)automaticallyUpdatesVisiblySettled;
- (id /* block */)backgroundViewProvider:(void *)arg1; // needs 1 arg types, found 4: id /* block */, void*, id, SEL
- (double)brightness;
- (<BSInvalidatable> *)cancelTouchesForCurrentEventInHostedContent;
- (void)didSelectApplicationShortcutItem:(SBSApplicationShortcutItem *)arg1;
- (<BSInvalidatable> *)disableImageUpdatesForReason:(NSString *)arg1;
- (SBIcon *)icon;
- (unsigned long long)imageViewAlignment;
- (bool)isBackgroundBlurEnabled;
- (bool)isDropping;
- (bool)isOverlapping;
- (bool)isPrivateModeEnabled;
- (bool)isShowingContextMenu;
- (bool)isUserInteractionEnabled;
- (bool)isVisiblySettled;
- (_UILegibilitySettings *)legibilitySettings;
- (unsigned long long)pauseReasons;
- (unsigned long long)presentationMode;
- (void)removeCustomImageViewControllerObserver:(id <SBIconViewCustomImageViewControllerObserving>)arg1;
- (void)setAutomaticallyUpdatesVisiblySettled:(bool)arg1;
- (void)setBackgroundBlurEnabled:(bool)arg1;
- (void)setBackgroundViewProvider:(void *)arg1; // needs 1 arg types, found 5: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, UIView *, id /* block */, void*
- (void)setBrightness:(double)arg1;
- (void)setDropping:(bool)arg1;
- (void)setImageViewAlignment:(unsigned long long)arg1;
- (void)setLegibilitySettings:(_UILegibilitySettings *)arg1;
- (void)setOverlapping:(bool)arg1;
- (void)setPauseReasons:(unsigned long long)arg1;
- (void)setPresentationMode:(unsigned long long)arg1;
- (void)setPrivateModeEnabled:(bool)arg1;
- (void)setShowingContextMenu:(bool)arg1;
- (void)setUserInteractionEnabled:(bool)arg1;
- (void)setVisiblySettled:(bool)arg1;
- (UIView *)snapshotView;
- (<SBLeafIconDataSource> *)visiblyActiveDataSource;
- (bool)wantsCaptureOnlyBackgroundView;
- (bool)wantsLabelHidden;
- (void)willShowContextMenuAtLocation:(struct CGPoint { double x1; double x2; })arg1;

@end
