/* Generated by RuntimeBrowser.
 */

@protocol SBLockScreenCustomActionStoring <NSObject>

@required

- (SBFLockScreenActionContext *)_customLockScreenActionContext;
- (void)setCustomLockScreenActionContext:(SBFLockScreenActionContext *)arg1;

@end
