/* Generated by RuntimeBrowser.
 */

@protocol SBLockScreenBacklightControlling <NSObject>

@required

- (double)backlightLevel;
- (bool)isInScreenOffMode;
- (void)setBacklightLevel:(double)arg1;
- (void)setInScreenOffMode:(bool)arg1;
- (void)setInScreenOffMode:(bool)arg1 forAutoUnlock:(bool)arg2 fromUnlockSource:(int)arg3;
- (bool)shouldDisableALS;
- (void)startLockScreenFadeInAnimationForSource:(int)arg1;

@end
