/* Generated by RuntimeBrowser.
 */

@protocol SBSRemoteContentHostInterface

@required

- (void)didChangeStyle;
- (void)getContentBoundsWithReplyBlock:(void *)arg1; // needs 1 arg types, found 6: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSObject<OS_xpc_object> *, void*

@end
