/* Generated by RuntimeBrowser.
 */

@protocol SBSystemPointerInteractionDelegate <NSObject>

@required

- (bool)shouldBeginPointerInteractionAtLocation:(struct CGPoint { double x1; double x2; })arg1 forView:(UIView *)arg2;

@optional

- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })pointerInteractionHitTestInsetsForView:(UIView *)arg1;
- (UIPointerRegion *)regionAtLocation:(struct CGPoint { double x1; double x2; })arg1 forView:(UIView *)arg2;
- (UIPointerStyle *)styleForRegion:(UIPointerRegion *)arg1 forView:(UIView *)arg2;

@end
