/* Generated by RuntimeBrowser.
 */

@protocol SBWallpaperPresenting <NSObject>

@required

- (void)addObserver:(id <SBWallpaperObserver>)arg1 forVariant:(long long)arg2;
- (void)beginDelayingHomescreenStyleChangesForReason:(NSString *)arg1;
- (<BSInvalidatable> *)beginRequiringWithReason:(NSString *)arg1;
- (void)cancelInProcessAnimations;
- (struct { long long x1; long long x2; double x3; })currentHomescreenStyleTransitionState;
- (void)endDelayingHomescreenStyleChangesForReason:(NSString *)arg1 animationFactory:(BSUIAnimationFactory *)arg2;
- (double)homescreenWallpaperScale;
- (<SBFIrisWallpaperView> *)irisWallpaperView;
- (double)lockscreenWallpaperScale;
- (double)minimumHomescreenWallpaperScale;
- (double)minimumLockscreenWallpaperScale;
- (UIView<_SBFakeBlur> *)newFakeBlurViewForVariant:(long long)arg1 style:(long long)arg2 transformOptions:(unsigned long long)arg3;
- (void)preheatWallpaperForVariant:(long long)arg1;
- (void)removeObserver:(id <SBWallpaperObserver>)arg1 forVariant:(long long)arg2;
- (bool)removeWallpaperStyleForPriority:(long long)arg1 forVariant:(long long)arg2 withAnimationFactory:(BSUIAnimationFactory *)arg3;
- (void)setAlpha:(double)arg1 forWallpaperVariant:(long long)arg2;
- (void)setDisallowsRasterization:(bool)arg1 forVariant:(long long)arg2 withReason:(NSString *)arg3;
- (<SBWallpaperScaleInvalidating> *)setHomescreenWallpaperScale:(double)arg1 withAnimationFactory:(BSUIAnimationFactory *)arg2;
- (void)setLockscreenOnlyWallpaperAlpha:(double)arg1;
- (void)setLockscreenWallpaperContentsRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)setLockscreenWallpaperScale:(double)arg1;
- (void)setLockscreenWallpaperScale:(double)arg1 withAnimationFactory:(BSUIAnimationFactory *)arg2;
- (void)setVariant:(long long)arg1;
- (void)setVariant:(void *)arg1 withOutAnimationFactory:(void *)arg2 inAnimationFactory:(void *)arg3 completion:(void *)arg4; // needs 4 arg types, found 8: long long, BSUIAnimationFactory *, BSUIAnimationFactory *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, void*
- (void)setWallpaperHidden:(bool)arg1 variant:(long long)arg2 reason:(NSString *)arg3;
- (void)setWallpaperPresentingDelegate:(id <SBWallpaperPresentingDelegate>)arg1;
- (bool)setWallpaperStyle:(long long)arg1 forPriority:(long long)arg2 forVariant:(long long)arg3 withAnimationFactory:(BSUIAnimationFactory *)arg4;
- (bool)setWallpaperStyleTransitionState:(struct { long long x1; long long x2; double x3; })arg1 forPriority:(long long)arg2 forVariant:(long long)arg3 withAnimationFactory:(BSUIAnimationFactory *)arg4;
- (<BSInvalidatable> *)suspendColorSamplingForReason:(NSString *)arg1;
- (<BSInvalidatable> *)suspendWallpaperAnimationForReason:(NSString *)arg1;
- (void)updateIrisWallpaperForInteractiveMode;
- (bool)updateIrisWallpaperForStaticMode;
- (void)updateWallpaperForLocations:(void *)arg1 wallpaperMode:(void *)arg2 withCompletion:(void *)arg3; // needs 3 arg types, found 7: long long, long long, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, void*
- (void)updateWallpaperForLocations:(void *)arg1 withCompletion:(void *)arg2; // needs 2 arg types, found 6: long long, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, void*
- (long long)variant;
- (<SBWallpaperPresentingDelegate> *)wallpaperPresentingDelegate;

@optional

- (void)noteDidRotateFromInterfaceOrientation:(long long)arg1;
- (void)noteWillAnimateToInterfaceOrientation:(long long)arg1;

@end
