/* Generated by RuntimeBrowser.
 */

@protocol SearchUIFeedbackDelegateInternal <SearchUIFeedbackDelegate>

@optional

- (NSString *)queryString;
- (void)removeRowModel:(SearchUIRowModel *)arg1;
- (void)resignTextField;
- (SearchUICommandEnvironment *)searchUICommandEnvironment;

@end
