/* Generated by RuntimeBrowser.
 */

@protocol SiriPresentation <BSInvalidatable>

@required

- (void)dismiss;
- (void)dismissWithOptions:(SiriDismissalOptions *)arg1;
- (long long)identifier;
- (void)invalidate;
- (bool)isEnabled;
- (void)setSiriPresentationControllerDelegate:(id <SiriPresentationControllerDelegate>)arg1;
- (<SiriPresentationControllerDelegate> *)siriPresentationControllerDelegate;

@end
