/* Generated by RuntimeBrowser.
 */

@protocol TFBetaLaunchHandleActivationDelegate <NSObject>

@required

- (void)betaLaunchHandle:(TFBetaLaunchHandle *)arg1 activateIfNeededEndedWithResult:(bool)arg2;

@end
