/* Generated by RuntimeBrowser.
 */

@protocol TLKDescriptionViewDelegate <NSObject>

@optional

- (void)didPressFootnoteButton;
- (void)didPressMoreButton;
- (void)didPressTrailingFootnoteButton;

@end
