/* Generated by RuntimeBrowser.
 */

@protocol UIDragInteractionDelegate_ForWebKitOnly <UIDragInteractionDelegate_Private>

@optional

- (bool)_dragInteraction:(void *)arg1 item:(void *)arg2 shouldDelaySetDownAnimationWithCompletion:(void *)arg3; // needs 3 arg types, found 7: UIDragInteraction *, UIDragItem *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, void*
- (void)_dragInteraction:(void *)arg1 itemsForAddingToSession:(void *)arg2 withTouchAtPoint:(void *)arg3 completion:(void *)arg4; // needs 4 arg types, found 9: UIDragInteraction *, <UIDragSession> *, struct CGPoint { double x1; double x2; }, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSArray *, void*

@end
