/* Generated by RuntimeBrowser.
 */

@protocol WFActionDrawerCoordinatorDelegate <NSObject>

@required

- (void)actionDrawerCoordinator:(WFActionDrawerCoordinator *)arg1 didAppendAction:(WFAction *)arg2;
- (WFAction *)actionDrawerCoordinator:(WFActionDrawerCoordinator *)arg1 replacementActionForDescriptionOfAction:(WFAction *)arg2;

@end
