/* Generated by RuntimeBrowser.
 */

@protocol WFActionUserInterfaceListenerDelegate <NSObject>

@required

- (void)actionUserInterfaceListener:(WFActionUserInterfaceListener *)arg1 showViewInPlatter:(UIView *)arg2 attribution:(WFDialogAttribution *)arg3;

@end
