/* Generated by RuntimeBrowser.
 */

@protocol WFCollectionViewDelegateModulesLayout <UICollectionViewDelegate>

@optional

- (bool)collectionView:(UICollectionView *)arg1 layout:(UICollectionViewLayout *)arg2 itemAtIndexPath:(NSIndexPath *)arg3 isConnectedToItemAtIndexPath:(NSIndexPath *)arg4;
- (bool)collectionView:(UICollectionView *)arg1 layout:(UICollectionViewLayout *)arg2 shouldHideItemAtIndexPath:(NSIndexPath *)arg3;
- (struct CGSize { double x1; double x2; })collectionView:(UICollectionView *)arg1 layout:(UICollectionViewLayout *)arg2 sizeForFooterInSection:(long long)arg3;
- (struct CGSize { double x1; double x2; })collectionView:(UICollectionView *)arg1 layout:(UICollectionViewLayout *)arg2 sizeForHeaderInSection:(long long)arg3;
- (struct CGSize { double x1; double x2; })collectionView:(UICollectionView *)arg1 layout:(UICollectionViewLayout *)arg2 sizeForItemAtIndexPath:(NSIndexPath *)arg3;
- (double)collectionView:(UICollectionView *)arg1 layout:(UICollectionViewLayout *)arg2 verticalOffsetForItemAtIndexPath:(NSIndexPath *)arg3;

@end
