/* Generated by RuntimeBrowser.
 */

@protocol WFDragCoordinator <NSObject>

@required

- (UIView *)containerView;
- (<WFModuleDelegate> *)moduleDelegate;
- (NSArray *)participatingViewControllers;
- (NSArray *)scrollViewsAffectingDrag;

@end
