/* Generated by RuntimeBrowser.
 */

@protocol WFGetFileActionUserInterface <WFRemoteUserInterface>

@required

- (void)showWithServiceName:(void *)arg1 directoryPath:(void *)arg2 options:(void *)arg3 completionHandler:(void *)arg4; // needs 4 arg types, found 11: NSString *, NSString *, unsigned long long, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSArray *, WFContentAttributionSet *, NSError *, void*

@end
