/* Generated by RuntimeBrowser.
 */

@protocol WFModulesCollectionViewDelegate <NSObject>

@required

- (UIContextMenuConfiguration *)collectionView:(UICollectionView *)arg1 contextMenuConfigurationForItemAtIndexPath:(NSIndexPath *)arg2 point:(struct CGPoint { double x1; double x2; })arg3;
- (bool)collectionView:(UICollectionView *)arg1 layout:(UICollectionViewLayout *)arg2 shouldHideItemAtIndexPath:(NSIndexPath *)arg3;
- (void)collectionView:(UICollectionView *)arg1 willDisplayCell:(UICollectionViewCell *)arg2 forItemAtIndexPath:(NSIndexPath *)arg3;

@end
