/* Generated by RuntimeBrowser.
 */

@protocol WFTakePhotoActionUserInterface <WFRemoteUserInterface>

@required

- (void)showWithPhotoCount:(void *)arg1 device:(void *)arg2 completionHandler:(void *)arg3; // needs 3 arg types, found 9: unsigned long long, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSData *, NSError *, void*

@end
