/* Generated by RuntimeBrowser.
 */

@protocol WFTextTokenField <WFTextField>

@required

- (void)beginEditingWithContext:(WFVariableEditingContext *)arg1;
- (struct _NSRange { unsigned long long x1; unsigned long long x2; })selectedRange;
- (void)setSelectedRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg1;
- (void)setVariableString:(WFVariableString *)arg1;
- (WFVariableString *)variableString;

@end
