/* Generated by RuntimeBrowser.
 */

@protocol WFTimeTriggerDayOfWeekCellDelegate

@required

- (void)dayOfWeekPickerCell:(WFTimeTriggerDayOfWeekCell *)arg1 didChangeSelectedRecurrences:(NSSet *)arg2;

@end
