/* Generated by RuntimeBrowser.
 */

@protocol WFTriggerMultiSelectCellDelegate <NSObject>

@required

- (void)cell:(WFTriggerMultiSelectCell *)arg1 didSelectOptionWithLeftViewSelected:(bool)arg2 rightViewSelected:(bool)arg3;

@end
