/* Generated by RuntimeBrowser.
 */

@protocol WFVariableConfigurationViewControllerDelegate <NSObject>

@required

- (void)configurationViewController:(WFVariableConfigurationViewController *)arg1 didUpdateVariable:(WFVariable *)arg2;
- (void)configurationViewController:(void *)arg1 presentPromptWithTitle:(void *)arg2 message:(void *)arg3 fieldConfigurationHandler:(void *)arg4 commitHandler:(void *)arg5; // needs 5 arg types, found 15: WFVariableConfigurationViewController *, NSString *, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, <WFAlertTextField> *, void*, id /* block */, void*, void, id /* block */, NSString *, void*

@end
