/* Generated by RuntimeBrowser.
 */

@protocol WFVariableConfigurationOptionsViewControllerDelegate <NSObject>

@required

- (void)optionsViewController:(WFVariableConfigurationOptionsViewController *)arg1 didSelectOption:(WFVariableConfigurationOption *)arg2;

@end
