/* Generated by RuntimeBrowser.
 */

@protocol WFVariableConfigurationAccessoryViewDelegate <NSObject>

@required

- (void)accessoryViewDidDelete:(WFVariableConfigurationAccessoryView *)arg1;
- (void)accessoryViewDidDismiss:(WFVariableConfigurationAccessoryView *)arg1;
- (void)accessoryViewDidRename:(WFVariableConfigurationAccessoryView *)arg1;
- (void)accessoryViewDidReturnToKeyboard:(WFVariableConfigurationAccessoryView *)arg1;
- (void)accessoryViewDidRevealAction:(WFVariableConfigurationAccessoryView *)arg1;

@end
