/* Generated by RuntimeBrowser.
 */

@protocol WFWorkflowWizardNameSuggestionCellDelegate <NSObject>

@required

- (void)workflowWizardNameSuggestionCellDidSelectSuggestedPhrase:(NSString *)arg1;

@end
