/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AXSpringBoardServerInstance.framework/AXSpringBoardServerInstance
 */

@interface __AXSpringBoardServerSideAppManager : NSObject {
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  __CGRect__;
}

@end
