/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AXSpringBoardServerInstance.framework/AXSpringBoardServerInstance
 */

@interface __AXSB_UIScreenSafeCategory_super : UIAccessibilitySafeCategory

@end
