/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AXSpringBoardServerInstance.framework/AXSpringBoardServerInstance
 */

@interface __AXSBServerUIApplication_super : UIAccessibilitySafeCategory

@end
