/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AXSpringBoardServerInstance.framework/AXSpringBoardServerInstance
 */

@interface AXSB_SBMainDisplaySceneManagerSafeCategory : __AXSB_SBMainDisplaySceneManagerSafeCategory_super

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;

- (void)_userInterfaceStyleArbiterStyleChanged:(id)arg1;

@end
