/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AXSpringBoardServerInstance.framework/AXSpringBoardServerInstance
 */

@interface AXTripleClickAlertController : UIAlertController

+ (bool)_allowInteractiveSheetDismissal;

- (bool)_canShowWhileLocked;

@end
