/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CarPlaySupport.framework/CarPlaySupport
 */

@interface CPSGridTemplateView : UIView {
    NSArray * _gridButtons;
}

- (void).cxx_destruct;
- (unsigned long long)buttonViewCountThatFits:(double)arg1 buttonPadding:(double)arg2;
- (id)initWithGridButtons:(id)arg1;
- (void)layoutSubviews;

@end
