/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CarPlaySupport.framework/CarPlaySupport
 */

@interface CPSInformationTemplateFocusableView : UIView

- (bool)canBecomeFocused;
- (bool)isUserInteractionEnabled;

@end
