/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthHearingDaemon.framework/HealthHearingDaemon
 */

@interface HDAudioAnalyticsHeadphoneSettingsResult : NSObject {
    NSString * _haenRetention;
    bool  _hasHAENEnabled;
    bool  _hasHAENRequired;
    bool  _hasIncludeOtherHeadphonesEnabled;
    bool  _hasMeasureLevelsEnabled;
}

@property (nonatomic, retain) NSString *haenRetention;
@property (nonatomic) bool hasHAENEnabled;
@property (nonatomic) bool hasHAENRequired;
@property (nonatomic) bool hasIncludeOtherHeadphonesEnabled;
@property (nonatomic) bool hasMeasureLevelsEnabled;

- (void).cxx_destruct;
- (id)haenRetention;
- (bool)hasHAENEnabled;
- (bool)hasHAENRequired;
- (bool)hasIncludeOtherHeadphonesEnabled;
- (bool)hasMeasureLevelsEnabled;
- (id)initWithHAENRequired:(bool)arg1 hasHAENEnabled:(bool)arg2 hasMeasureLevelsEnabled:(bool)arg3 hasIncludeOtherHeadphonesEnabled:(bool)arg4 haenRetention:(id)arg5;
- (void)setHaenRetention:(id)arg1;
- (void)setHasHAENEnabled:(bool)arg1;
- (void)setHasHAENRequired:(bool)arg1;
- (void)setHasIncludeOtherHeadphonesEnabled:(bool)arg1;
- (void)setHasMeasureLevelsEnabled:(bool)arg1;

@end
