/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppPredictionUI.framework/AppPredictionUI
 */

@interface APUIActionPlatterView : UIView <CRKCardPresentationDelegate, CRKCardViewControllerDelegate> {
    <APUIActionFeedbackDelegate> * _actionFeedbackDelegate;
    ATXAction * _atxAction;
    CRKCardPresentation * _cardPresentation;
    UIViewController * _currentCardViewController;
    long long  _displayContext;
    unsigned long long  _displayType;
    NSLayoutConstraint * _heightConstraint;
    UIViewController * _parentViewController;
    PLPlatterView * _platterView;
    APUIShortLookViewController * _shortLookViewController;
    UITapGestureRecognizer * _tapRecognizer;
}

@property (nonatomic) <APUIActionFeedbackDelegate> *actionFeedbackDelegate;
@property (nonatomic, retain) CRKCardPresentation *cardPresentation;
@property (nonatomic, readonly) <CRKCardViewControllerDelegate> *cardViewControllerDelegate;
@property (nonatomic, retain) UIViewController *currentCardViewController;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) long long displayContext;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_tapRecognized:(id)arg1;
- (id)actionFeedbackDelegate;
- (id)cardPresentation;
- (long long)cardPresentation:(id)arg1 compareCardSectionViewProviderOne:(id)arg2 providerTwo:(id)arg3;
- (void)cardViewControllerBoundsDidChange:(id)arg1;
- (id)cardViewControllerDelegate;
- (void)cardViewControllerDidLoad:(id)arg1;
- (id)currentCardViewController;
- (long long)displayContext;
- (id)initWithATXAction:(id)arg1 parentViewController:(id)arg2;
- (id)initWithATXAction:(id)arg1 parentViewController:(id)arg2 displayType:(unsigned long long)arg3;
- (void)layoutSubviews;
- (void)setActionFeedbackDelegate:(id)arg1;
- (void)setCardPresentation:(id)arg1;
- (void)setCurrentCardViewController:(id)arg1;
- (void)setDisplayContext:(long long)arg1;

@end
