/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpotlightUI.framework/SpotlightUI
 */

@interface SPUISearchBarTransitionContext : UIApplicationSceneTransitionContext

@property (nonatomic) bool searchBarDidFocus;

- (bool)searchBarDidFocus;
- (void)setSearchBarDidFocus:(bool)arg1;

@end
