/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpotlightUI.framework/SpotlightUI
 */

@interface SPUIRemoteSearchViewController : SPUISpotlightRemoteViewController {
    <SPUIRemoteSearchViewDelegate> * _delegate;
    id /* block */  _didFinishDismissingSpotlightHandler;
    double  _distanceToTopOfIcons;
    UIView * _dummyTransitionView;
    id /* block */  _finishedPresentingSpotlightHandler;
    double  _revealProgress;
    unsigned int  _searchHeaderContextID;
    unsigned long long  _searchHeaderLayerRenderID;
    unsigned long long  _source;
    id /* block */  _willBeginDismissingSpotlightHandler;
    id /* block */  _willStartPresetingSpotlightHandler;
}

@property (nonatomic) <SPUIRemoteSearchViewDelegate> *delegate;
@property (nonatomic, copy) id /* block */ didFinishDismissingSpotlightHandler;
@property (nonatomic) double distanceToTopOfIcons;
@property (nonatomic, retain) UIView *dummyTransitionView;
@property (nonatomic, copy) id /* block */ finishedPresentingSpotlightHandler;
@property (nonatomic) double revealProgress;
@property (nonatomic) unsigned int searchHeaderContextID;
@property (nonatomic) unsigned long long searchHeaderLayerRenderID;
@property (nonatomic) unsigned long long source;
@property (nonatomic, copy) id /* block */ willBeginDismissingSpotlightHandler;
@property (nonatomic, copy) id /* block */ willStartPresetingSpotlightHandler;

- (void).cxx_destruct;
- (id)delegate;
- (id /* block */)didFinishDismissingSpotlightHandler;
- (void)didInvalidateSceneWhenForeground;
- (double)distanceToTopOfIcons;
- (id)dummyTransitionView;
- (void)finishCompletionHandlerIfNeeded;
- (id /* block */)finishedPresentingSpotlightHandler;
- (id)init;
- (bool)prewarmSceneInTheBackground;
- (double)revealProgress;
- (void)scene:(id)arg1 didUpdateClientSettingsWithDiff:(id)arg2 oldClientSettings:(id)arg3 transitionContext:(id)arg4;
- (void)sceneContentStateDidChange:(id)arg1;
- (void)sceneDidInvalidate:(id)arg1;
- (id)sceneSpecification;
- (unsigned int)searchHeaderContextID;
- (unsigned long long)searchHeaderLayerRenderID;
- (void)setDelegate:(id)arg1;
- (void)setDidFinishDismissingSpotlightHandler:(id /* block */)arg1;
- (void)setDistanceToTopOfIcons:(double)arg1;
- (void)setDummyTransitionView:(id)arg1;
- (void)setFinishedPresentingSpotlightHandler:(id /* block */)arg1;
- (void)setRevealProgress:(double)arg1;
- (void)setSearchHeaderContextID:(unsigned int)arg1;
- (void)setSearchHeaderLayerRenderID:(unsigned long long)arg1;
- (void)setSource:(unsigned long long)arg1;
- (void)setWillBeginDismissingSpotlightHandler:(id /* block */)arg1;
- (void)setWillStartPresetingSpotlightHandler:(id /* block */)arg1;
- (unsigned long long)source;
- (void)updateIntent:(unsigned long long)arg1;
- (void)updateSceneSettingsWithBlock:(id /* block */)arg1;
- (void)viewDidAppear:(bool)arg1;
- (void)viewDidDisappear:(bool)arg1;
- (void)viewWillAppear:(bool)arg1;
- (void)viewWillDisappear:(bool)arg1;
- (id /* block */)willBeginDismissingSpotlightHandler;
- (id /* block */)willStartPresetingSpotlightHandler;

@end
