/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDLogEventMessageEventsAnalyzer : HMDLogEventAnalyzer {
    HMDEventCountersManager * _eventCountersManager;
    HMDEventFlagsManager * _eventFlagsManager;
}

@property (nonatomic, retain) HMDEventCountersManager *eventCountersManager;
@property (nonatomic, retain) HMDEventFlagsManager *eventFlagsManager;

- (void).cxx_destruct;
- (void)_handleRemoteMessageLogEvent:(id)arg1;
- (void)_handleXPCMessageCounterLogEvent:(id)arg1;
- (id)eventCountersManager;
- (id)eventFlagsManager;
- (id)eventNameForRemoteMessageLogEvent:(id)arg1;
- (id)initWithSupportedEventTypes:(id)arg1 context:(id)arg2;
- (id)initWithSupportedEventTypes:(id)arg1 context:(id)arg2 eventCountersManager:(id)arg3 eventFlagsManager:(id)arg4;
- (id)messageDirectionForRemoteMessageCounterRequestGroup:(id)arg1;
- (void)processLogEvent:(id)arg1;
- (void)setEventCountersManager:(id)arg1;
- (void)setEventFlagsManager:(id)arg1;
- (void)submitAggregateCountersForRemoteMessageCounterRequestGroup:(id)arg1;
- (void)submitAggregateCountersForXPCMessageCounterRequestGroup:(id)arg1;
- (void)submitAggregateCountersLogEventIfNeeded;
- (id)transportTypeForRemoteMessageCounterRequestGroup:(id)arg1;

@end
