/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface CKAppliedAnimationContext : NSObject {
    NSString * _key;
    CALayer * _targetLayer;
}

@property (nonatomic, readonly, copy) NSString *key;
@property (nonatomic, readonly) CALayer *targetLayer;

- (void).cxx_destruct;
- (id)initWithTargetLayer:(id)arg1 key:(id)arg2;
- (id)key;
- (id)targetLayer;

@end
