/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface CKComponentGestureActionForwarder : NSObject

+ (id)sharedInstance;

- (void)handleGesture:(id)arg1;

@end
