/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface CKComponentContextValue : NSObject {
    NSMutableDictionary * _dictionary;
    <CKComponentContextDynamicLookup> * _dynamicLookup;
}

- (void).cxx_destruct;

@end
