/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface CKComponentHierarchyDebugHelper : NSObject

+ (id)componentHierarchyDescription;
+ (id)componentHierarchyDescriptionForView:(id)arg1 searchUpwards:(bool)arg2;
+ (id)componentHierarchyDescriptionForView:(id)arg1 searchUpwards:(bool)arg2 showViews:(bool)arg3;

@end
