/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface CKComponentDebugController : NSObject

+ (bool)debugMode;
+ (void)reflowComponents;
+ (void)registerReflowListener:(id)arg1;
+ (void)setDebugMode:(bool)arg1;

@end
