/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface CKComponentBoundsAnimationCollectionViewContext : NSObject {
    UICollectionView * _collectionView;
    NSDictionary * _decorationElementIndexPathsToOriginalLayoutAttributes;
    NSDictionary * _decorationElementIndexPathsToSnapshotViews;
    NSDictionary * _indexPathsToOriginalLayoutAttributes;
    NSDictionary * _indexPathsToSnapshotViews;
    struct vector<unsigned long, std::__1::allocator<unsigned long> > { 
        unsigned long long *__begin_; 
        unsigned long long *__end_; 
        struct __compressed_pair<unsigned long *, std::__1::allocator<unsigned long> > { 
            unsigned long long *__value_; 
        } __end_cap_; 
    }  _numberOfItemsInSection;
    long long  _numberOfSections;
    NSDictionary * _supplementaryElementIndexPathsToOriginalLayoutAttributes;
    NSDictionary * _supplementaryElementIndexPathsToSnapshotViews;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)applyBoundsAnimationToCollectionView:(const struct CKComponentBoundsAnimation { double x1; double x2; unsigned long long x3; unsigned long long x4; double x5; double x6; }*)arg1;
- (id)initWithCollectionView:(id)arg1;

@end
