/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface CKTextKitRenderer : NSObject {
    struct CKTextKitAttributes { 
        NSAttributedString *attributedString; 
        NSAttributedString *truncationAttributedString; 
        NSCharacterSet *avoidTailTruncationSet; 
        long long lineBreakMode; 
        unsigned long long maximumNumberOfLines; 
        struct CGSize { 
            double width; 
            double height; 
        } shadowOffset; 
        UIColor *shadowColor; 
        double shadowOpacity; 
        double shadowRadius; 
        int (*layoutManagerFactory)(); 
    }  _attributes;
    struct CGSize { 
        double width; 
        double height; 
    }  _calculatedSize;
    struct CGSize { 
        double width; 
        double height; 
    }  _constrainedSize;
    CKTextKitContext * _context;
    CKTextKitShadower * _shadower;
    UITraitCollection * _traitCollection;
    <CKTextKitTruncating> * _truncater;
    double  _verticalOffset;
}

@property (nonatomic, readonly) struct CKTextKitAttributes { id x1; id x2; id x3; long long x4; unsigned long long x5; struct CGSize { double x_6_1_1; double x_6_1_2; } x6; id x7; double x8; double x9; int (*x10)(); } attributes;
@property (nonatomic, readonly) struct CGSize { double x1; double x2; } constrainedSize;
@property (nonatomic, readonly) CKTextKitContext *context;
@property (nonatomic, readonly) CKTextKitShadower *shadower;
@property (nonatomic, retain) UITraitCollection *traitCollection;
@property (nonatomic, readonly) <CKTextKitTruncating> *truncater;

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)_calculateSize;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_internalRectForGlyphAtIndex:(unsigned long long)arg1 measureOption:(unsigned long long)arg2 layoutManager:(id)arg3 textContainer:(id)arg4 textStorage:(id)arg5;
- (struct CKTextKitAttributes { id x1; id x2; id x3; long long x4; unsigned long long x5; struct CGSize { double x_6_1_1; double x_6_1_2; } x6; id x7; double x8; double x9; int (*x10)(); })attributes;
- (struct CGSize { double x1; double x2; })constrainedSize;
- (id)context;
- (void)drawInContext:(struct CGContext { }*)arg1 bounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg2;
- (void)enumerateTextIndexesAtPosition:(struct CGPoint { double x1; double x2; })arg1 usingBlock:(id /* block */)arg2;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })frameForTextRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg1;
- (id)initWithTextKitAttributes:(const struct CKTextKitAttributes { id x1; id x2; id x3; long long x4; unsigned long long x5; struct CGSize { double x_6_1_1; double x_6_1_2; } x6; id x7; double x8; double x9; int (*x10)(); }*)arg1 constrainedSize:(struct CGSize { double x1; double x2; })arg2;
- (unsigned long long)lineCount;
- (unsigned long long)nearestTextIndexAtPosition:(struct CGPoint { double x1; double x2; })arg1;
- (id)rectsForTextRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg1 measureOption:(unsigned long long)arg2;
- (void)setTraitCollection:(id)arg1;
- (id)shadower;
- (struct CGSize { double x1; double x2; })size;
- (id)textCheckingResultAtPoint:(struct CGPoint { double x1; double x2; })arg1;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })trailingRect;
- (id)traitCollection;
- (id)truncater;
- (struct vector<_NSRange, std::__1::allocator<_NSRange> > { struct _NSRange {} *x1; struct _NSRange {} *x2; struct __compressed_pair<_NSRange *, std::__1::allocator<_NSRange> > { struct _NSRange {} *x_3_1_1; } x3; })visibleRanges;

@end
