/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface CKTransactionalComponentDataSourceAppliedChanges : NSObject {
    NSSet * _insertedIndexPaths;
    NSIndexSet * _insertedSections;
    NSDictionary * _movedIndexPaths;
    NSSet * _removedIndexPaths;
    NSIndexSet * _removedSections;
    NSSet * _updatedIndexPaths;
    NSDictionary * _userInfo;
}

@property (nonatomic, readonly, copy) NSSet *insertedIndexPaths;
@property (nonatomic, readonly, copy) NSIndexSet *insertedSections;
@property (nonatomic, readonly, copy) NSDictionary *movedIndexPaths;
@property (nonatomic, readonly, copy) NSSet *removedIndexPaths;
@property (nonatomic, readonly, copy) NSIndexSet *removedSections;
@property (nonatomic, readonly, copy) NSSet *updatedIndexPaths;
@property (nonatomic, readonly, copy) NSDictionary *userInfo;

- (void).cxx_destruct;
- (id)description;
- (unsigned long long)hash;
- (id)init;
- (id)initWithUpdatedIndexPaths:(id)arg1 removedIndexPaths:(id)arg2 removedSections:(id)arg3 movedIndexPaths:(id)arg4 insertedSections:(id)arg5 insertedIndexPaths:(id)arg6 userInfo:(id)arg7;
- (id)insertedIndexPaths;
- (id)insertedSections;
- (bool)isEqual:(id)arg1;
- (id)movedIndexPaths;
- (id)newIndexPathForPreviousIndexPath:(id)arg1;
- (id)removedIndexPaths;
- (id)removedSections;
- (id)updatedIndexPaths;
- (id)userInfo;

@end
