/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface CKTransactionalComponentDataSourceChange : NSObject {
    CKTransactionalComponentDataSourceAppliedChanges * _appliedChanges;
    CKTransactionalComponentDataSourceState * _state;
}

@property (nonatomic, readonly) CKTransactionalComponentDataSourceAppliedChanges *appliedChanges;
@property (nonatomic, readonly) CKTransactionalComponentDataSourceState *state;

- (void).cxx_destruct;
- (id)appliedChanges;
- (id)initWithState:(id)arg1 appliedChanges:(id)arg2;
- (id)state;

@end
