/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface CKTransactionalComponentDataSourceChangesetModification : NSObject <CKTransactionalComponentDataSourceStateModifying> {
    CKTransactionalComponentDataSourceChangeset * _changeset;
    <CKComponentStateListener> * _stateListener;
    NSDictionary * _userInfo;
}

@property (nonatomic, readonly) CKTransactionalComponentDataSourceChangeset *changeset;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)changeFromState:(id)arg1;
- (id)changeset;
- (id)description;
- (id)initWithChangeset:(id)arg1 stateListener:(id)arg2 userInfo:(id)arg3;

@end
