/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface CKTransactionalComponentDataSourceListenerAnnouncer : CKComponentAnnouncerBase <CKTransactionalComponentDataSourceListener>

- (void)addListener:(id)arg1;
- (void)removeListener:(id)arg1;
- (void)transactionalComponentDataSource:(id)arg1 didModifyPreviousState:(id)arg2 byApplyingChanges:(id)arg3;

@end
