/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface POPPlaceholderAnimatableProperty : POPAnimatableProperty {
    NSString * name;
    id /* block */  readBlock;
    double  threshold;
    id /* block */  writeBlock;
}

- (void).cxx_destruct;
- (id)name;
- (id /* block */)readBlock;
- (double)threshold;
- (id /* block */)writeBlock;

@end
