/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface WFActionCustomView : UIView {
    WFAction * _action;
    <WFComponentNavigationContext> * _navigationContext;
}

@property (nonatomic) WFAction *action;
@property (nonatomic) <WFComponentNavigationContext> *navigationContext;

+ (double)preferredHeightForAction:(id)arg1;

- (void).cxx_destruct;
- (id)action;
- (void)didEnterReusePool;
- (id)navigationContext;
- (void)setAction:(id)arg1;
- (void)setNavigationContext:(id)arg1;
- (void)willLeaveReusePool;

@end
