/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface WFActivityIndicatorComponent : CKComponent

+ (id)newWithStyle:(long long)arg1 color:(id)arg2 animating:(bool)arg3;

@end
