/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface WFArrayParameterComponent : WFParameterComponent {
    WFArrayParameter * _parameter;
    WFArrayParameterState * _state;
    id /* block */  _updateBlock;
}

@property (nonatomic, readonly) WFArrayParameter *parameter;

+ (id)newWithParameter:(id)arg1 state:(id)arg2 updateBlock:(id /* block */)arg3 options:(struct WFParameterComponentOptions { bool x1; bool x2; bool x3; id x4; id x5; bool x6; id x7; id x8; })arg4 variableProvider:(id)arg5 variableUIDelegate:(id)arg6 navigationContext:(id)arg7 labelsToAlignTo:(id)arg8;
+ (bool)standaloneVariablesAsContentItems;
+ (Class)stateClass;

- (void).cxx_destruct;
- (void)arrayEditor:(id)arg1 confirmDeletion:(id)arg2;
- (void)notifyParameterObserverWithValues:(id)arg1 updateItem:(id)arg2;
- (id)parameter;
- (id /* block */)updateBlock;

@end
