/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface WFArrayEditorView : WFListEditorView

+ (Class)cellClass;

- (void)insertNewItemOfType:(long long)arg1;

@end
