/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface WFContentArrayParameterComponent : WFArrayParameterComponent

+ (bool)standaloneVariablesAsContentItems;
+ (Class)stateClass;

@end
