/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface WFContentClassesToolbar : UICollectionReusableView {
    WFModuleAppearance * _appearance;
    NSLayoutConstraint * _chevronHiddenConstraint;
    UIImageView * _chevronImageView;
    NSLayoutConstraint * _chevronVisibleConstraint;
    NSArray * _contentClasses;
    UIView * _contentView;
    <WFContentClassesToolbarDelegate> * _delegate;
    bool  _highlighted;
    bool  _toolbarDisabled;
    UILabel * _typesLabel;
    WFWorkflow * _workflow;
}

@property (nonatomic, retain) WFModuleAppearance *appearance;
@property (nonatomic, readonly) NSLayoutConstraint *chevronHiddenConstraint;
@property (nonatomic) UIImageView *chevronImageView;
@property (nonatomic, readonly) NSLayoutConstraint *chevronVisibleConstraint;
@property (nonatomic, copy) NSArray *contentClasses;
@property (nonatomic) UIView *contentView;
@property (nonatomic) <WFContentClassesToolbarDelegate> *delegate;
@property (nonatomic) bool highlighted;
@property (nonatomic) bool toolbarDisabled;
@property (nonatomic) UILabel *typesLabel;
@property (nonatomic, retain) WFWorkflow *workflow;

+ (struct NSDirectionalEdgeInsets { double x1; double x2; double x3; double x4; })contentViewInsets;
+ (id)headingFont;
+ (double)preferredHeight;

- (void).cxx_destruct;
- (bool)accessibilityActivate;
- (bool)accessibilityElementsHidden;
- (id)accessibilityHint;
- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;
- (id)appearance;
- (id)chevronHiddenConstraint;
- (id)chevronImageView;
- (id)chevronVisibleConstraint;
- (id)contentClasses;
- (id)contentView;
- (void)dealloc;
- (id)delegate;
- (void)fadeOutHighlight;
- (void)highlight;
- (bool)highlighted;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (bool)isAccessibilityElement;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
- (void)setAppearance:(id)arg1;
- (void)setChevronImageView:(id)arg1;
- (void)setContentClasses:(id)arg1;
- (void)setContentView:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setHighlighted:(bool)arg1;
- (void)setToolbarDisabled:(bool)arg1;
- (void)setTypesLabel:(id)arg1;
- (void)setWorkflow:(id)arg1;
- (bool)toolbarDisabled;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (id)typesLabel;
- (void)typesLabelTapped;
- (void)unhighlight;
- (void)updateAppearance;
- (void)updateTypesLabel;
- (id)workflow;

@end
