/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface WFDateFieldParameterComponent : WFTextInputParameterComponent

+ (struct WFCompressionResistance { int x1; double x2; })compressionResistance;

@end
