/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface WFDatePickerButtonComponentController : CKComponentController

- (void)didMount;

@end
