/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface WFDragGestureRecognizer : UIGestureRecognizer {
    double  _allowableMovement;
    NSMutableSet * _allowedClassHeirarchies;
    struct WFDragVelocitySample { 
        struct CGPoint { 
            double x; 
            double y; 
        } start; 
        struct CGPoint { 
            double x; 
            double y; 
        } end; 
        double dt; 
    }  _currentVelocitySample;
    NSMutableDictionary * _dragDirections;
    NSMutableSet * _ignoredClassHeirarchies;
    double  _lastTouchTimestamp;
    double  _minimumPressDuration;
    NSMutableSet * _observedScrollViews;
    struct WFDragVelocitySample { 
        struct CGPoint { 
            double x; 
            double y; 
        } start; 
        struct CGPoint { 
            double x; 
            double y; 
        } end; 
        double dt; 
    }  _previousVelocitySample;
    struct CGPoint { 
        double x; 
        double y; 
    }  _start;
    NSPointerArray * _touches;
}

@property (nonatomic) double allowableMovement;
@property (nonatomic) double minimumPressDuration;

- (void).cxx_destruct;
- (void)acceptViewsWithClassHeirarchy:(Class)arg1;
- (void)addTouches:(id)arg1;
- (double)allowableMovement;
- (void)dealloc;
- (void)ignoreViewsWithClassHeirarchy:(Class)arg1;
- (id)initWithTarget:(id)arg1 action:(SEL)arg2;
- (struct CGPoint { double x1; double x2; })locationInView:(id)arg1;
- (struct CGPoint { double x1; double x2; })locationOfTouch:(unsigned long long)arg1 inView:(id)arg2;
- (void)longPressTimeoutTriggered;
- (double)minimumPressDuration;
- (unsigned long long)numberOfTouches;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
- (void)removeTouches:(id)arg1;
- (void)reset;
- (void)setAllowableMovement:(double)arg1;
- (void)setMinimumPressDuration:(double)arg1;
- (void)setPermittedDragDirections:(unsigned long long)arg1 forHorizontalSizeClass:(long long)arg2;
- (bool)shouldRequireFailureOfGestureRecognizer:(id)arg1;
- (void)startObservingScrollView:(id)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (struct CGPoint { double x1; double x2; })velocityInView:(id)arg1;

@end
