/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface WFEnumerationParameterComponentController : CKComponentController <WFEnumerationTextTokenChooserPresenter, WFParameterValuePickerViewControllerDelegate> {
    WFEnumerationValuePicker * _enumValuePicker;
    UISegmentedControl * _segmentedControl;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)completeEditing;
- (void)didUnmount;
- (void)didUpdateComponent;
- (void)loadDynamicEnumerationValuesWithCompletionHandler:(id /* block */)arg1;
- (void)presentEnumerationValuePickerWithInitialCollection:(id)arg1;
- (void)presentTokenChooser:(id)arg1;
- (void)presentValuePicker:(id)arg1;
- (void)willUnmount;

@end
