/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface WFListEditingContext : NSObject {
    bool  _key;
    bool  _nested;
    WFListEditorUpdateItem * _updateItem;
    WFVariableEditingContext * _variableContext;
}

@property (nonatomic) bool key;
@property (nonatomic) bool nested;
@property (nonatomic, retain) WFListEditorUpdateItem *updateItem;
@property (nonatomic, retain) WFVariableEditingContext *variableContext;

- (void).cxx_destruct;
- (bool)key;
- (bool)nested;
- (void)setKey:(bool)arg1;
- (void)setNested:(bool)arg1;
- (void)setUpdateItem:(id)arg1;
- (void)setVariableContext:(id)arg1;
- (id)updateItem;
- (id)variableContext;

@end
