/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface WFMaskedShadowComponent : CKCompositeComponent

+ (id)newWithOptions:(struct WFMaskedShadowComponentOptions { double x1; id x2; id x3; struct CGSize { double x_4_1_1; double x_4_1_2; } x4; double x5; double x6; id x7; double x8; id x9; })arg1 component:(id)arg2;

@end
