/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface WFMaterialStylableTableViewCell : UITableViewCell {
    MTVisualStylingProvider * _fillProvider;
    UIView * _highlightedBackgroundView;
    UIColor * _overridingBackgroundColor;
}

@property (nonatomic, retain) MTVisualStylingProvider *fillProvider;
@property (nonatomic, retain) UIView *highlightedBackgroundView;
@property (nonatomic, retain) UIColor *overridingBackgroundColor;

- (void).cxx_destruct;
- (id)fillProvider;
- (id)highlightedBackgroundView;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (id)overridingBackgroundColor;
- (void)setFillProvider:(id)arg1;
- (void)setHighlightedBackgroundView:(id)arg1;
- (void)setOverridingBackgroundColor:(id)arg1;

@end
