/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface WFModuleSummaryBasedParameterComponentController : CKComponentController <WFModuleSummaryEditorDelegate> {
    WFModuleSummaryEditor * _currentEditor;
}

@property (nonatomic, retain) WFModuleSummaryEditor *currentEditor;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)buttonTapped:(id)arg1;
- (id)currentEditor;
- (void)parameterLayoutTapped:(id)arg1;
- (void)setCurrentEditor:(id)arg1;
- (void)summaryEditor:(id)arg1 didCommitParameterState:(id)arg2;
- (void)summaryEditorDidFinish:(id)arg1 returnToKeyboard:(bool)arg2 withTextAttachmentToEdit:(id)arg3;
- (void)summaryEditorDidRequestTextEntry:(id)arg1;

@end
