/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface WFModuleOutputInnerComponent : CKCompositeComponent {
    WFModuleOutputModel * _model;
}

@property (nonatomic, readonly) WFModuleOutputModel *model;

+ (id)newWithModel:(id)arg1;

- (void).cxx_destruct;
- (void)buttonTapped;
- (id)model;

@end
