/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface WFModuleSummaryBasedParameterComponent : WFParameterComponent {
    WFSlotTemplateSlot * _buttonSlot;
    <WFComponentNavigationContext> * _navigationContext;
    WFParameter * _parameter;
    <WFParameterState> * _state;
    WFModuleSummaryBasedParameterComponentStateWriter * _stateWriter;
    <WFVariableProvider> * _variableProvider;
    <WFVariableUIDelegate> * _variableUIDelegate;
}

@property (nonatomic, readonly) WFSlotTemplateSlot *buttonSlot;
@property (nonatomic, readonly) <WFComponentNavigationContext> *navigationContext;
@property (nonatomic, readonly) <WFParameterState> *state;
@property (nonatomic, readonly) WFModuleSummaryBasedParameterComponentStateWriter *stateWriter;
@property (nonatomic, readonly) <WFVariableProvider> *variableProvider;
@property (nonatomic, readonly) <WFVariableUIDelegate> *variableUIDelegate;

+ (id)newWithParameter:(id)arg1 state:(id)arg2 updateBlock:(id /* block */)arg3 options:(struct WFParameterComponentOptions { bool x1; bool x2; bool x3; id x4; id x5; bool x6; id x7; id x8; })arg4 variableProvider:(id)arg5 variableUIDelegate:(id)arg6 navigationContext:(id)arg7 labelsToAlignTo:(id)arg8;
+ (id)singleButtonSlotForParameter:(id)arg1 state:(id)arg2;

- (void).cxx_destruct;
- (id)buttonSlot;
- (id)navigationContext;
- (id)parameter;
- (id)state;
- (id)stateWriter;
- (id)variableProvider;
- (id)variableUIDelegate;

@end
