/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface WFModuleComponentController : CKComponentController {
    <NSObject> * _inputVariableState;
}

- (void).cxx_destruct;
- (void)didMount;
- (void)didUpdateComponent;
- (void)loadIconIfNecessary;
- (void)willUpdateComponent;

@end
