/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface WFModuleConfigurationComponent : CKCompositeComponent

+ (id)newWithModel:(id)arg1 navigationContext:(id)arg2;

- (void)showMoreToggled:(id)arg1 withExpandedValue:(bool)arg2;

@end
