/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface WFModuleParameterStackComponent : CKCompositeComponent

+ (id)newWithChildren:(const struct vector<CKComponent *, std::__1::allocator<CKComponent *> > { id *x1; id *x2; struct __compressed_pair<CKComponent *__strong *, std::__1::allocator<CKComponent *> > { id *x_3_1_1; } x3; }*)arg1 backgroundColor:(id)arg2;

@end
