/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface WFMultipleValueEditorViewController : UIViewController {
    WFMultipleValueEditorView * _editorView;
    <WFComponentNavigationContext> * _navigationContext;
}

@property (nonatomic, readonly) WFMultipleValueEditorView *editorView;
@property (nonatomic, retain) <WFComponentNavigationContext> *navigationContext;

+ (Class)editorViewClass;

- (void).cxx_destruct;
- (void)done;
- (id)editorView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)navigationContext;
- (void)setNavigationContext:(id)arg1;

@end
