/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface WFMultipleValueAddNewItemTableViewCell : WFMaterialStylableTableViewCell {
    UIColor * _titleColor;
}

@property (nonatomic, retain) UIColor *titleColor;

- (void).cxx_destruct;
- (void)setTitleColor:(id)arg1;
- (void)tintColorDidChange;
- (id)titleColor;
- (void)updateTitleColor;

@end
