/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface WFMultipleValueEditorViewCellContext : NSObject {
    WFMultipleValueEditorViewCell * _cell;
}

@property (nonatomic) WFMultipleValueEditorViewCell *cell;
@property (nonatomic, readonly) <WFComponentNavigationContext> *navigationContext;
@property (nonatomic, readonly) <WFVariableProvider> *variableProvider;
@property (nonatomic, readonly) <WFVariableUIDelegate> *variableUIDelegate;

- (void).cxx_destruct;
- (id)cell;
- (id)navigationContext;
- (void)setCell:(id)arg1;
- (id)variableProvider;
- (id)variableUIDelegate;

@end
