/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface WFNumberFieldComponent : CKStatefulViewComponent {
    struct WFNumberFieldAttributes { 
        bool editable; 
        NSString *placeholder; 
        long long textAlignment; 
        bool becomeFirstResponder; 
        NSString *text; 
        bool allowsDecimalNumbers; 
        bool allowsNegatingNumbers; 
        <WFVariableProvider> *variableProvider; 
        <WFVariableUIDelegate> *variableUIDelegate; 
        NSSet *allowedVariableTypes; 
        bool variablesDisabled; 
        long long keyboardAppearance; 
    }  _attributes;
    struct CKTypedComponentAction<> { 
        unsigned long long _variant; 
        id _target; 
        CKComponentScopeHandle *_scopeHandle; 
        SEL _selector; 
    }  _doneAction;
    id /* block */  _updateBlock;
    id /* block */  _variableBlock;
}

@property (nonatomic, readonly) struct WFNumberFieldAttributes { bool x1; id x2; long long x3; bool x4; id x5; bool x6; bool x7; id x8; id x9; id x10; bool x11; long long x12; } attributes;
@property (nonatomic, readonly) struct CKTypedComponentAction<> { unsigned long long x1; id x2; id x3; SEL x4; } doneAction;
@property (nonatomic, readonly) id /* block */ updateBlock;
@property (nonatomic, readonly) id /* block */ variableBlock;

+ (id)newWithAttributes:(const struct WFNumberFieldAttributes { bool x1; id x2; long long x3; bool x4; id x5; bool x6; bool x7; id x8; id x9; id x10; bool x11; long long x12; }*)arg1 updateBlock:(id /* block */)arg2 variableBlock:(id /* block */)arg3 doneAction:(struct CKTypedComponentAction<> { unsigned long long x1; id x2; id x3; SEL x4; })arg4 size:(const struct CKComponentSize { struct CKRelativeDimension { int x_1_1_1; double x_1_1_2; } x1; struct CKRelativeDimension { int x_2_1_1; double x_2_1_2; } x2; struct CKRelativeDimension { int x_3_1_1; double x_3_1_2; } x3; struct CKRelativeDimension { int x_4_1_1; double x_4_1_2; } x4; struct CKRelativeDimension { int x_5_1_1; double x_5_1_2; } x5; struct CKRelativeDimension { int x_6_1_1; double x_6_1_2; } x6; }*)arg5;

- (id).cxx_construct;
- (void).cxx_destruct;
- (struct WFNumberFieldAttributes { bool x1; id x2; long long x3; bool x4; id x5; bool x6; bool x7; id x8; id x9; id x10; bool x11; long long x12; })attributes;
- (struct CKTypedComponentAction<> { unsigned long long x1; id x2; id x3; SEL x4; })doneAction;
- (id /* block */)updateBlock;
- (id /* block */)variableBlock;

@end
