/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface WFNumberPickerButtonComponent : CKCompositeComponent {
    bool  _becomeFirstResponder;
    WFCustomButtonComponent * _buttonComponent;
    id /* block */  _updateBlock;
    id /* block */  _variableBlock;
}

@property (nonatomic, readonly) bool becomeFirstResponder;
@property (nonatomic, readonly) WFCustomButtonComponent *buttonComponent;
@property (nonatomic, readonly) id /* block */ updateBlock;
@property (nonatomic, readonly) id /* block */ variableBlock;

+ (id)newWithAttributes:(const struct WFNumberPickerAttributes { bool x1; id x2; id x3; id x4; unsigned long long x5; struct _NSRange { unsigned long long x_6_1_1; unsigned long long x_6_1_2; } x6; bool x7; id x8; id x9; id x10; }*)arg1 identifier:(id)arg2 updateBlock:(id /* block */)arg3 variableBlock:(id /* block */)arg4;

- (void).cxx_destruct;
- (bool)becomeFirstResponder;
- (id)buttonComponent;
- (id /* block */)updateBlock;
- (id /* block */)variableBlock;

@end
