/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface WFNumberFieldParameterSummaryEditor : WFModuleSummaryEditor <WFVariableUIDelegate> {
    bool  _hasChangedText;
    bool  _isPickingMagicVariable;
    <WFParameterState> * _stagedState;
    WFVariableInputCoordinator * _variableCoordinator;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) bool hasChangedText;
@property (readonly) unsigned long long hash;
@property (nonatomic) bool isPickingMagicVariable;
@property (nonatomic, retain) <WFParameterState> *stagedState;
@property (readonly) Class superclass;
@property (nonatomic, retain) WFVariableInputCoordinator *variableCoordinator;

- (void).cxx_destruct;
- (void)beginEditingSlotWithIdentifier:(id)arg1 sourceViewController:(id)arg2 sourceView:(id)arg3 sourceRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg4;
- (void)cancelEditingWithCompletionHandler:(id /* block */)arg1;
- (bool)hasChangedText;
- (bool)isPickingMagicVariable;
- (void)negateText;
- (void)revealAction:(id)arg1 fromSourceView:(id)arg2 preScrollHandler:(id /* block */)arg3 goBackHandler:(id /* block */)arg4 scrolledAwayHandler:(id /* block */)arg5;
- (void)setHasChangedText:(bool)arg1;
- (void)setIsPickingMagicVariable:(bool)arg1;
- (void)setStagedState:(id)arg1;
- (void)setVariableCoordinator:(id)arg1;
- (void)setVariableProvider:(id)arg1;
- (void)setVariableUIDelegate:(id)arg1;
- (void)showActionOutputPickerFromSourceResponder:(id)arg1 allowExtensionInput:(bool)arg2 variableProvider:(id)arg3 completionHandler:(id /* block */)arg4;
- (void)sourceViewTintColorDidChange;
- (id)stagedState;
- (id)stateByReplacingVariableFromInitialState:(id)arg1 withVariable:(id)arg2;
- (id)stateForEnteredText:(id)arg1;
- (id)stateForVariable:(id)arg1;
- (void)textEntryDidFinish;
- (bool)textEntryShouldChangeText:(id)arg1;
- (void)textEntryTextDidChange:(id)arg1;
- (void)textEntryWillBegin:(id)arg1 allowMultipleLines:(bool*)arg2;
- (id)variableCoordinator;

@end
