/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface WFNumericPageControl : UIView <WFAdjustableLabelDelegate> {
    long long  _currentPage;
    <WFNumericPageControlDelegate> * _delegate;
    UIColor * _deselectedPageTintColor;
    long long  _numberOfPages;
    UIPageControl * _pageControl;
    UILabel * _pageLabel;
    UIColor * _selectedPageTintColor;
    bool  _usesBoldText;
}

@property (nonatomic) long long currentPage;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <WFNumericPageControlDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) UIColor *deselectedPageTintColor;
@property (readonly) unsigned long long hash;
@property (nonatomic) long long numberOfPages;
@property (nonatomic) UIPageControl *pageControl;
@property (nonatomic) UILabel *pageLabel;
@property (nonatomic, retain) UIColor *selectedPageTintColor;
@property (readonly) Class superclass;
@property (nonatomic) bool usesBoldText;

- (void).cxx_destruct;
- (void)adjustableLabelRequestedDecrement:(id)arg1;
- (void)adjustableLabelRequestedIncrement:(id)arg1;
- (long long)currentPage;
- (id)delegate;
- (id)deselectedPageTintColor;
- (struct CGSize { double x1; double x2; })intrinsicContentSize;
- (void)layoutSubviews;
- (long long)numberOfPages;
- (id)pageControl;
- (void)pageControlValueChanged:(id)arg1;
- (id)pageLabel;
- (id)selectedPageTintColor;
- (void)setCurrentPage:(long long)arg1;
- (void)setDelegate:(id)arg1;
- (void)setDeselectedPageTintColor:(id)arg1;
- (void)setNumberOfPages:(long long)arg1;
- (void)setPageControl:(id)arg1;
- (void)setPageLabel:(id)arg1;
- (void)setSelectedPageTintColor:(id)arg1;
- (void)setUsesBoldText:(bool)arg1;
- (void)updateControls;
- (bool)usesBoldText;

@end
