/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface WFParameterValuePickerTableViewCellConfiguration : NSObject <UIContentConfiguration> {
    double  _cornerRadius;
    bool  _forceImageScaling;
    UIImage * _image;
    NSString * _secondaryText;
    UIColor * _secondaryTextColor;
    UIFont * _secondaryTextFont;
    NSString * _text;
    UIColor * _textColor;
    UIFont * _textFont;
}

@property (nonatomic) double cornerRadius;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) bool forceImageScaling;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) UIImage *image;
@property (nonatomic, copy) NSString *secondaryText;
@property (nonatomic, copy) UIColor *secondaryTextColor;
@property (nonatomic, retain) UIFont *secondaryTextFont;
@property (readonly) Class superclass;
@property (nonatomic, copy) NSString *text;
@property (nonatomic, copy) UIColor *textColor;
@property (nonatomic, retain) UIFont *textFont;

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (double)cornerRadius;
- (bool)forceImageScaling;
- (unsigned long long)hash;
- (id)image;
- (bool)isEqual:(id)arg1;
- (id)makeContentView;
- (id)secondaryText;
- (id)secondaryTextColor;
- (id)secondaryTextFont;
- (void)setCornerRadius:(double)arg1;
- (void)setForceImageScaling:(bool)arg1;
- (void)setImage:(id)arg1;
- (void)setSecondaryText:(id)arg1;
- (void)setSecondaryTextColor:(id)arg1;
- (void)setSecondaryTextFont:(id)arg1;
- (void)setText:(id)arg1;
- (void)setTextColor:(id)arg1;
- (void)setTextFont:(id)arg1;
- (id)text;
- (id)textColor;
- (id)textFont;
- (id)updatedConfigurationForState:(id)arg1;

@end
