/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface WFParameterEditorHostingCellContext : NSObject {
    WFModuleAppearance * _appearance;
    WFParameterEditorHostingCell * _cell;
    <WFComponentNavigationContext> * _navigationContext;
    UITraitCollection * _traitCollection;
}

@property (nonatomic, retain) WFModuleAppearance *appearance;
@property (nonatomic) WFParameterEditorHostingCell *cell;
@property (nonatomic, retain) <WFComponentNavigationContext> *navigationContext;
@property (nonatomic, retain) UITraitCollection *traitCollection;

- (void).cxx_destruct;
- (id)appearance;
- (id)cell;
- (id)navigationContext;
- (void)setAppearance:(id)arg1;
- (void)setCell:(id)arg1;
- (void)setNavigationContext:(id)arg1;
- (void)setTraitCollection:(id)arg1;
- (id)traitCollection;

@end
