/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface WFSwiftUIParameterHostingComponentController : CKStatefulViewComponentController {
    WFParameterHostingView * _viewForSizing;
}

+ (void)configureStatefulView:(id)arg1 forComponent:(id)arg2;
+ (void)configureStatefulView:(id)arg1 forComponent:(id)arg2 forSizing:(bool)arg3;
+ (id)newStatefulView:(id)arg1;

- (void).cxx_destruct;
- (struct CGSize { double x1; double x2; })sizeThatFits:(struct CGSize { double x1; double x2; })arg1 forComponent:(id)arg2;
- (void)willRelinquishStatefulView:(id)arg1;

@end
