/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface WFTextTokenChooser : NSObject {
    NSArray * _additionalButtons;
    NSSet * _allowedVariableTypes;
    NSArray * _auxiliaryButtons;
    id /* block */  _cancelHandler;
    id /* block */  _choiceHandler;
    long long  _maximumSelectableItemsCount;
    NSString * _message;
    NSString * _noChoicesMessage;
    bool  _prefersItemPickerSheetPresentation;
    WFAlert * _presentedAlert;
    NSIndexSet * _selectedButtonIndexes;
    WFVariable * _selectedVariable;
    bool  _showsClearButton;
    bool  _showsDoneButton;
    NSString * _title;
    <WFUIKitUserInterface> * _userInterface;
}

@property (nonatomic, copy) NSArray *additionalButtons;
@property (nonatomic, copy) NSSet *allowedVariableTypes;
@property (nonatomic, copy) NSArray *auxiliaryButtons;
@property (nonatomic, copy) id /* block */ cancelHandler;
@property (nonatomic, copy) id /* block */ choiceHandler;
@property (nonatomic) long long maximumSelectableItemsCount;
@property (nonatomic, copy) NSString *message;
@property (nonatomic, copy) NSString *noChoicesMessage;
@property (nonatomic) bool prefersItemPickerSheetPresentation;
@property (nonatomic, retain) WFAlert *presentedAlert;
@property (nonatomic, retain) NSIndexSet *selectedButtonIndexes;
@property (nonatomic, retain) WFVariable *selectedVariable;
@property (nonatomic) bool showsClearButton;
@property (nonatomic) bool showsDoneButton;
@property (nonatomic, copy) NSString *title;
@property (nonatomic) <WFUIKitUserInterface> *userInterface;

- (void).cxx_destruct;
- (id)additionalButtons;
- (id)alertButtonForVariable:(id)arg1 selected:(bool)arg2;
- (id)allowedVariableTypes;
- (id)auxiliaryButtons;
- (id /* block */)cancelHandler;
- (id /* block */)choiceHandler;
- (void)dismissWithCompletionHandler:(id /* block */)arg1;
- (id)init;
- (long long)maximumSelectableItemsCount;
- (id)message;
- (id)noChoicesMessage;
- (bool)prefersItemPickerSheetPresentation;
- (void)presentWithVariableProvider:(id)arg1 variableUIDelegate:(id)arg2 userInterface:(id)arg3 fromSource:(id)arg4;
- (id)presentedAlert;
- (id)selectedButtonIndexes;
- (id)selectedVariable;
- (void)setAdditionalButtons:(id)arg1;
- (void)setAllowedVariableTypes:(id)arg1;
- (void)setAuxiliaryButtons:(id)arg1;
- (void)setCancelHandler:(id /* block */)arg1;
- (void)setChoiceHandler:(id /* block */)arg1;
- (void)setMaximumSelectableItemsCount:(long long)arg1;
- (void)setMessage:(id)arg1;
- (void)setNoChoicesMessage:(id)arg1;
- (void)setPrefersItemPickerSheetPresentation:(bool)arg1;
- (void)setPresentedAlert:(id)arg1;
- (void)setSelectedButtonIndexes:(id)arg1;
- (void)setSelectedVariable:(id)arg1;
- (void)setShowsClearButton:(bool)arg1;
- (void)setShowsDoneButton:(bool)arg1;
- (void)setTitle:(id)arg1;
- (void)setUserInterface:(id)arg1;
- (bool)showsClearButton;
- (bool)showsDoneButton;
- (id)title;
- (void)updateButtonsInAlert:(id)arg1;
- (id)userInterface;

@end
