/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface WFVariableConfigurationCell : UITableViewCell {
    unsigned long long  _accessory;
    UIImageView * _disclosureImageView;
    CAShapeLayer * _maskLayer;
    unsigned long long  _roundedCorners;
    bool  _roundsCorners;
    UIView * _separatorView;
    bool  _showsSeparator;
    <WFVariableConfigurationCellSizingDelegate> * _sizingDelegate;
    NSString * _titleText;
    NSString * _valueText;
}

@property (nonatomic) unsigned long long accessory;
@property (nonatomic, readonly) UIImageView *disclosureImageView;
@property (nonatomic, readonly) CAShapeLayer *maskLayer;
@property (nonatomic) unsigned long long roundedCorners;
@property (nonatomic) bool roundsCorners;
@property (nonatomic, readonly) UIView *separatorView;
@property (nonatomic) bool showsSeparator;
@property (nonatomic) <WFVariableConfigurationCellSizingDelegate> *sizingDelegate;
@property (nonatomic, copy) NSString *titleText;
@property (nonatomic, copy) NSString *valueText;

+ (long long)cellStyle;

- (void).cxx_destruct;
- (unsigned long long)accessory;
- (id)disclosureImageView;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)layoutSubviews;
- (id)maskLayer;
- (unsigned long long)roundedCorners;
- (bool)roundsCorners;
- (id)separatorView;
- (void)setAccessory:(unsigned long long)arg1;
- (void)setFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)setRoundedCorners:(unsigned long long)arg1;
- (void)setRoundsCorners:(bool)arg1;
- (void)setShowsSeparator:(bool)arg1;
- (void)setSizingDelegate:(id)arg1;
- (void)setTitleText:(id)arg1;
- (void)setValueText:(id)arg1;
- (bool)showsSeparator;
- (id)sizingDelegate;
- (id)titleText;
- (void)updateMask;
- (id)valueText;

@end
