/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface WFVariableConfigurationSubtitleCell : WFVariableConfigurationCell

+ (long long)cellStyle;

@end
