/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface WFVariableConfigurationOptionsViewController : UITableViewController {
    WFVariableConfigurationOption * _defaultOption;
    <WFVariableConfigurationOptionsViewControllerDelegate> * _delegate;
    NSArray * _options;
    long long  _selectedOptionIndex;
    NSString * _userIdentifier;
}

@property (nonatomic, readonly) WFVariableConfigurationOption *defaultOption;
@property (nonatomic) <WFVariableConfigurationOptionsViewControllerDelegate> *delegate;
@property (nonatomic, readonly) NSArray *options;
@property (nonatomic) long long selectedOptionIndex;
@property (nonatomic, readonly, copy) NSString *userIdentifier;

- (void).cxx_destruct;
- (id)defaultOption;
- (id)delegate;
- (id)initWithTitle:(id)arg1 userIdentifier:(id)arg2 options:(id)arg3 defaultOption:(id)arg4 selectedOption:(id)arg5;
- (id)options;
- (long long)selectedOptionIndex;
- (void)setDelegate:(id)arg1;
- (void)setSelectedOptionIndex:(long long)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)userIdentifier;
- (void)viewDidLoad;

@end
