/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface WFVariableInputCoordinator : NSObject <WFVariableObserver, WFVariableShortcutsBarDelegate, WFVariableShortcutsTrayDelegate, WFVariableSuggesterDelegate> {
    NSSet * _allowedVariableTypes;
    id /* block */  _customButtonBlock;
    NSString * _customButtonTitle;
    UIView * _inputViewWhenTrayCollapsed;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  _previousFrame;
    UIResponder<WFInputViewMutable> * _responder;
    WFVariableShortcutsBar * _shortcutsBar;
    WFVariableShortcutsTray * _shortcutsTray;
    bool  _showsDoneButton;
    UIColor * _tintColor;
    bool  _undocked;
    id /* block */  _variableBlock;
    <WFVariableProvider> * _variableProvider;
    WFVariableSuggester * _variableSuggester;
    <WFVariableTypingContext> * _variableTypingContext;
    <WFVariableUIDelegate> * _variableUIDelegate;
}

@property (nonatomic, copy) NSSet *allowedVariableTypes;
@property (nonatomic, copy) id /* block */ customButtonBlock;
@property (nonatomic, copy) NSString *customButtonTitle;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) UIView *inputViewWhenTrayCollapsed;
@property (nonatomic) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } previousFrame;
@property (nonatomic) UIResponder<WFInputViewMutable> *responder;
@property (nonatomic, retain) WFVariableShortcutsBar *shortcutsBar;
@property (nonatomic, retain) WFVariableShortcutsTray *shortcutsTray;
@property (nonatomic) bool showsDoneButton;
@property (readonly) Class superclass;
@property (nonatomic, retain) UIColor *tintColor;
@property (nonatomic) bool undocked;
@property (nonatomic, copy) id /* block */ variableBlock;
@property (nonatomic) <WFVariableProvider> *variableProvider;
@property (nonatomic, retain) WFVariableSuggester *variableSuggester;
@property (nonatomic) <WFVariableTypingContext> *variableTypingContext;
@property (nonatomic) <WFVariableUIDelegate> *variableUIDelegate;

- (void).cxx_destruct;
- (id)allowedVariableTypes;
- (void)availableVariablesDidChange;
- (void)collapseTrayAnimated:(bool)arg1;
- (id /* block */)customButtonBlock;
- (id)customButtonTitle;
- (void)dealloc;
- (id)init;
- (id)inputViewWhenTrayCollapsed;
- (void)keyboardWillChangeFrame:(id)arg1;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })previousFrame;
- (void)reloadCurrentVariables;
- (id)responder;
- (void)revealTray;
- (void)setAllowedVariableTypes:(id)arg1;
- (void)setCustomButtonBlock:(id /* block */)arg1;
- (void)setCustomButtonTitle:(id)arg1;
- (void)setInputViewWhenTrayCollapsed:(id)arg1;
- (void)setPreviousFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)setResponder:(id)arg1;
- (void)setShortcutsBar:(id)arg1;
- (void)setShortcutsTray:(id)arg1;
- (void)setShowsDoneButton:(bool)arg1;
- (void)setTintColor:(id)arg1;
- (void)setUndocked:(bool)arg1;
- (void)setVariableBlock:(id /* block */)arg1;
- (void)setVariableProvider:(id)arg1;
- (void)setVariableSuggester:(id)arg1;
- (void)setVariableTypingContext:(id)arg1;
- (void)setVariableUIDelegate:(id)arg1;
- (id)shortcutsBar;
- (void)shortcutsBar:(id)arg1 didSelectVariable:(id)arg2;
- (void)shortcutsBarDidDismiss:(id)arg1;
- (void)shortcutsBarDidOpenTray:(id)arg1;
- (void)shortcutsBarDidSelectCustomButton:(id)arg1;
- (void)shortcutsBarDidSelectMagicVariable:(id)arg1;
- (id)shortcutsTray;
- (void)showActionOutputPicker;
- (bool)showsDoneButton;
- (bool)showsMagicVariables;
- (bool)showsUserDefinedVariables;
- (id)specialVariables;
- (id)tintColor;
- (bool)undocked;
- (void)updateInputViews;
- (id /* block */)variableBlock;
- (id)variableProvider;
- (void)variableShortcutsTray:(id)arg1 didSelectVariable:(id)arg2;
- (void)variableShortcutsTrayDidSelectMagicVariable:(id)arg1;
- (id)variableSuggester;
- (void)variableSuggesterSuggestionsDidChange:(id)arg1;
- (id)variableTypingContext;
- (id)variableUIDelegate;

@end
