/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface WFVariableConfigurationViewController : UIViewController <UITableViewDataSource, UITableViewDelegate, WFVariableConfigurationCellSizingDelegate, WFVariableConfigurationHeaderViewDelegate, WFVariableConfigurationOptionsViewControllerDelegate, WFVariableDelegate, WFVariableObserver> {
    NSOrderedSet * _classesForVisibleAggrandizements;
    WFCoercionVariableAggrandizement * _coercionAggrandizement;
    WFDateFormatVariableAggrandizement * _dateFormatAggrandizement;
    <WFVariableConfigurationViewControllerDelegate> * _delegate;
    WFDictionaryValueVariableAggrandizement * _dictionaryValueAggrandizement;
    WFVariableConfigurationHeaderView * _headerView;
    WFVariableConfigurationInfoView * _infoView;
    NSArray * _properties;
    WFPropertyVariableAggrandizement * _propertyAggrandizement;
    bool  _propertyListExpanded;
    unsigned long long  _resultType;
    UITableView * _tableView;
    WFUnitVariableAggrandizement * _unitAggrandizement;
    bool  _userExplicitlySelectedDefaultProperty;
    WFVariable * _variable;
}

@property (nonatomic, retain) NSOrderedSet *classesForVisibleAggrandizements;
@property (nonatomic, retain) WFCoercionVariableAggrandizement *coercionAggrandizement;
@property (nonatomic, retain) WFDateFormatVariableAggrandizement *dateFormatAggrandizement;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <WFVariableConfigurationViewControllerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) WFDictionaryValueVariableAggrandizement *dictionaryValueAggrandizement;
@property (readonly) unsigned long long hash;
@property (nonatomic) WFVariableConfigurationHeaderView *headerView;
@property (nonatomic) WFVariableConfigurationInfoView *infoView;
@property (nonatomic, retain) NSArray *properties;
@property (nonatomic, retain) WFPropertyVariableAggrandizement *propertyAggrandizement;
@property (nonatomic) bool propertyListExpanded;
@property (nonatomic) unsigned long long resultType;
@property (readonly) Class superclass;
@property (nonatomic) UITableView *tableView;
@property (nonatomic, retain) WFUnitVariableAggrandizement *unitAggrandizement;
@property (nonatomic) bool userExplicitlySelectedDefaultProperty;
@property (nonatomic, readonly) WFVariable *variable;

+ (id)defaultPropertyForContentClass:(Class)arg1 resultType:(unsigned long long)arg2;
+ (bool)shouldShowOnInsertionOfVariable:(id)arg1;

- (void).cxx_destruct;
- (void)availableVariablesDidChange;
- (id)classesForVisibleAggrandizements;
- (id)coercionAggrandizement;
- (id)currentPropertyMeasurementUnitType;
- (id)dateFormatAggrandizement;
- (void)dealloc;
- (id)delegate;
- (id)dictionaryValueAggrandizement;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })frameForConfigurationCell:(id)arg1 withProposedFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg2;
- (void)generateUpdatedVariable;
- (bool)hasMeasurementUnit;
- (id)headerView;
- (void)headerViewTypeTapped:(id)arg1;
- (id)infoView;
- (id)initWithVariable:(id)arg1;
- (void)loadView;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)optionsViewController:(id)arg1 didSelectOption:(id)arg2;
- (Class)postCoercionContentClass;
- (id)properties;
- (id)propertyAggrandizement;
- (bool)propertyListExpanded;
- (unsigned long long)resultType;
- (void)setClassesForVisibleAggrandizements:(id)arg1;
- (void)setCoercionAggrandizement:(id)arg1;
- (void)setDateFormatAggrandizement:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setDictionaryValueAggrandizement:(id)arg1;
- (void)setHeaderView:(id)arg1;
- (void)setInfoView:(id)arg1;
- (void)setProperties:(id)arg1;
- (void)setPropertyAggrandizement:(id)arg1;
- (void)setPropertyListExpanded:(bool)arg1;
- (void)setResultType:(unsigned long long)arg1;
- (void)setTableView:(id)arg1;
- (void)setUnitAggrandizement:(id)arg1;
- (void)setUserExplicitlySelectedDefaultProperty:(bool)arg1;
- (id)tableView;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)unitAggrandizement;
- (void)updateHeaderView;
- (void)updateVisibleAggrandizements;
- (bool)userExplicitlySelectedDefaultProperty;
- (id)variable;
- (void)variableContentClassesDidChange;
- (void)variableDidChange:(id)arg1;
- (bool)variableSupportsCoercionAggrandizement;
- (void)viewWillAppear:(bool)arg1;
- (void)viewWillDisappear:(bool)arg1;

@end
