/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsCore.framework/NewsCore
 */

@interface FCChannelUpsellConfig : NSObject {
    NSString * _channelID;
    FCEmailSignupConfig * _emailSignupConfiguration;
    long long  _quiescenceInterval;
    NSDictionary * _triggersByMethod;
}

@property (nonatomic, copy) NSString *channelID;
@property (nonatomic, retain) FCEmailSignupConfig *emailSignupConfiguration;
@property (nonatomic) long long quiescenceInterval;
@property (nonatomic, retain) NSDictionary *triggersByMethod;

- (void).cxx_destruct;
- (id)channelID;
- (id)emailSignupConfiguration;
- (id)initWithConfigDictionary:(id)arg1;
- (long long)quiescenceInterval;
- (void)setChannelID:(id)arg1;
- (void)setEmailSignupConfiguration:(id)arg1;
- (void)setQuiescenceInterval:(long long)arg1;
- (void)setTriggersByMethod:(id)arg1;
- (id)triggersByMethod;

@end
