/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpotlightUIInternal.framework/SpotlightUIInternal
 */

@interface SPUIHeaderBlurView : UIVisualEffectView {
    UIColor * _baseTintColor;
    bool  _useInPlaceFilteredBlur;
}

@property (retain) UIColor *baseTintColor;
@property (nonatomic) bool useInPlaceFilteredBlur;

+ (double)backgroundViewBlurAlphaForProgress:(double)arg1 isDarkBackground:(bool)arg2;

- (void).cxx_destruct;
- (id)baseTintColor;
- (id)init;
- (void)setBaseTintColor:(id)arg1;
- (void)setTintColor:(id)arg1;
- (void)setUseInPlaceFilteredBlur:(bool)arg1;
- (void)updateEffect;
- (bool)useInPlaceFilteredBlur;

@end
