/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpotlightUIInternal.framework/SpotlightUIInternal
 */

@interface SPUINavigationBar : UINavigationBar {
    SearchUISeparatorView * _topDividerView;
}

@property (retain) SearchUISeparatorView *topDividerView;

+ (bool)_supportsCanvasView;

- (void).cxx_destruct;
- (void)_dynamicUserInterfaceTraitDidChange;
- (id)_popNavigationItemWithTransition:(int)arg1;
- (void)didAddSubview:(id)arg1;
- (void)didMoveToWindow;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (bool)isLocked;
- (void)performShowSeparator:(bool)arg1 animated:(bool)arg2;
- (void)pushNavigationItem:(id)arg1;
- (void)setTopDividerView:(id)arg1;
- (void)showSeparator:(bool)arg1 animated:(bool)arg2;
- (void)tlk_updateForAppearance:(id)arg1;
- (id)topDividerView;
- (void)updateBackgroundViewVisibility;

@end
