/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpotlightUIInternal.framework/SpotlightUIInternal
 */

@interface SPUIGradientMaskView : UIView

@property (nonatomic, retain) CAGradientLayer *layer;

+ (Class)layerClass;

- (id)init;

@end
