/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpotlightUIInternal.framework/SpotlightUIInternal
 */

@interface SPUIBoxView : NUIContainerBoxView

+ (Class)layerClass;

@end
