/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpotlightUIInternal.framework/SpotlightUIInternal
 */

@interface SPUIResultCompletion : SPUICompletion

+ (bool)supportsResult:(id)arg1 cardSection:(id)arg2;

- (bool)completionResultIsPotentiallyPunchout;

@end
