/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKitUI.framework/ActionKitUI
 */

@interface WFAccountListViewController : WFActionSettingsViewController <UITableViewDataSource, UITableViewDelegate, WFAccountLoginViewControllerDelegate> {
    Class  _accountClass;
    NSArray * _accounts;
    UITableView * _tableView;
}

@property (nonatomic, readonly) Class accountClass;
@property (nonatomic, copy) NSArray *accounts;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (nonatomic, readonly) UITableView *tableView;

- (void).cxx_destruct;
- (Class)accountClass;
- (id)accounts;
- (id)initWithAction:(id)arg1 definition:(id)arg2;
- (void)loadView;
- (void)loginViewController:(id)arg1 didLoginWithAccount:(id)arg2;
- (void)loginViewControllerDidCancel:(id)arg1;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)setAccounts:(id)arg1;
- (id)tableView;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (bool)tableView:(id)arg1 shouldIndentWhileEditingRowAtIndexPath:(id)arg2;
- (void)viewWillAppear:(bool)arg1;

@end
