/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKitUI.framework/ActionKitUI
 */

@interface WFShowWebPageActionUIKitUserInterface : WFActionUserInterface <SFSafariViewControllerDelegate, WFShowWebPageActionUserInterface, WFWebViewControllerDelegate> {
    id /* block */  _completionHandler;
}

@property (nonatomic, copy) id /* block */ completionHandler;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)cancelPresentationWithCompletionHandler:(id /* block */)arg1;
- (id /* block */)completionHandler;
- (void)finishWithError:(id)arg1;
- (void)safariViewControllerDidFinish:(id)arg1;
- (void)setCompletionHandler:(id /* block */)arg1;
- (void)showRichText:(id)arg1 completion:(id /* block */)arg2;
- (void)showURL:(id)arg1 readerView:(bool)arg2 completion:(id /* block */)arg3;
- (void)webViewControllerDidFinish:(id)arg1;

@end
