/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKitUI.framework/ActionKitUI
 */

@interface WFSSHKeyConfigurationViewController : UITableViewController <WFSSHKeyGenerationViewControllerDelegate> {
    WFItemBasedTableSection * _actionsSection;
    WFBasicTableItem * _bitsItem;
    WFBasicTableItem * _commentItem;
    WFTableDataSource * _dataSource;
    <WFSSHKeyConfigurationViewControllerDelegate> * _delegate;
    WFBasicTableItem * _exportItem;
    WFBasicTableItem * _generateItem;
    WFItemBasedTableSection * _keyInfoSection;
    WFSSHKeyPair * _keyPair;
    WFBasicTableItem * _md5HashItem;
    WFBasicTableItem * _sha256HashItem;
    WFBasicTableItem * _typeItem;
}

@property (nonatomic, readonly) WFItemBasedTableSection *actionsSection;
@property (nonatomic, readonly) WFBasicTableItem *bitsItem;
@property (nonatomic, readonly) WFBasicTableItem *commentItem;
@property (nonatomic, readonly) WFTableDataSource *dataSource;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <WFSSHKeyConfigurationViewControllerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) WFBasicTableItem *exportItem;
@property (nonatomic, readonly) WFBasicTableItem *generateItem;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) WFItemBasedTableSection *keyInfoSection;
@property (nonatomic, retain) WFSSHKeyPair *keyPair;
@property (nonatomic, readonly) WFBasicTableItem *md5HashItem;
@property (nonatomic, readonly) WFBasicTableItem *sha256HashItem;
@property (readonly) Class superclass;
@property (nonatomic, readonly) WFBasicTableItem *typeItem;

- (void).cxx_destruct;
- (id)actionsSection;
- (id)bitsItem;
- (id)commentItem;
- (id)dataSource;
- (id)delegate;
- (void)donePressed:(id)arg1;
- (id)exportItem;
- (id)generateItem;
- (id)init;
- (void)keyGenerationViewController:(id)arg1 didFinishWithKeyPair:(id)arg2;
- (id)keyInfoSection;
- (id)keyPair;
- (id)localizedDisplayNameForType:(unsigned long long)arg1;
- (id)md5HashItem;
- (id)publicKey;
- (void)setDelegate:(id)arg1;
- (void)setKeyPair:(id)arg1;
- (id)sha256HashItem;
- (void)showHashWithType:(unsigned long long)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)truncatedHash:(id)arg1;
- (id)typeItem;
- (void)updateVisibleItems;
- (void)viewDidLoad;

@end
