/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUIDomainIndicatorImageView : SearchUIImageView

- (void)_dynamicUserInterfaceTraitDidChange;
- (void)didMoveToWindow;
- (void)tlk_updateForAppearance:(id)arg1;

@end
