/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUITableView : UITableView {
    <SearchUITableViewSizingDelegate> * _sizingDelegate;
}

@property <SearchUITableViewSizingDelegate> *sizingDelegate;

- (void).cxx_destruct;
- (void)_dynamicUserInterfaceTraitDidChange;
- (void)didMoveToWindow;
- (id)init;
- (void)safeAreaInsetsDidChange;
- (void)setContentSize:(struct CGSize { double x1; double x2; })arg1;
- (void)setSizingDelegate:(id)arg1;
- (id)sizingDelegate;
- (void)tlk_updateForAppearance:(id)arg1;

@end
