/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUIActionDomainIndicatorViewController : SearchUIAccessoryViewController

@property (nonatomic, retain) SearchUIImageView *view;

+ (bool)supportsRowModel:(id)arg1;

- (id)setupView;
- (unsigned long long)type;
- (void)updateWithRowModel:(id)arg1;

@end
