/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUIDetailedRowModel : SearchUICardSectionRowModel {
    SFActionItem * _action;
    NSString * _applicationBundleIdentifier;
    NSArray * _details;
    SFImage * _fallbackImage;
    SFRichText * _footnote;
    NSString * _footnoteButtonText;
    bool  _isLocalApplicationResult;
    SFButton * _leadingButton;
    SFImage * _leadingImage;
    MKSearchFoundationResult * _mapsResult;
    NSString * _nearbyBusinessesString;
    bool  _preventThumbnailImageScaling;
    SFFormattedText * _secondaryTitle;
    SFImage * _secondaryTitleImage;
    bool  _secondaryTitleIsDetached;
    SFRichText * _title;
    SFFormattedText * _trailingBottomText;
    SFFormattedText * _trailingMiddleText;
    SFFormattedText * _trailingTopText;
    bool  _truncateTitleMiddle;
    bool  _useCompactDisplay;
}

@property (retain) SFActionItem *action;
@property (retain) NSString *applicationBundleIdentifier;
@property (nonatomic, retain) NSArray *details;
@property (retain) SFImage *fallbackImage;
@property (retain) SFRichText *footnote;
@property (retain) NSString *footnoteButtonText;
@property bool isLocalApplicationResult;
@property (retain) SFButton *leadingButton;
@property (nonatomic, retain) SFImage *leadingImage;
@property (retain) MKSearchFoundationResult *mapsResult;
@property (retain) NSString *nearbyBusinessesString;
@property bool preventThumbnailImageScaling;
@property (retain) SFFormattedText *secondaryTitle;
@property (retain) SFImage *secondaryTitleImage;
@property bool secondaryTitleIsDetached;
@property (retain) SFRichText *title;
@property (retain) SFFormattedText *trailingBottomText;
@property (retain) SFFormattedText *trailingMiddleText;
@property (retain) SFFormattedText *trailingTopText;
@property bool truncateTitleMiddle;
@property bool useCompactDisplay;

+ (bool)urlIsDraggable:(id)arg1;

- (void).cxx_destruct;
- (id)action;
- (id)applicationBundleIdentifier;
- (id)contactIdentifiers;
- (Class)customCardSectionViewClass;
- (id)descriptionText;
- (id)details;
- (id)dragAppBundleID;
- (id)dragSubtitle;
- (id)dragText;
- (id)dragTitle;
- (id)dragURL;
- (id)fallbackImage;
- (void)fillOutPropertiesForCardSection:(id)arg1;
- (id)footnote;
- (id)footnoteButtonText;
- (bool)hasLeadingImage;
- (id)initWithResult:(id)arg1 cardSection:(id)arg2 isInline:(bool)arg3 queryId:(unsigned long long)arg4;
- (id)initWithResult:(id)arg1 suggestion:(id)arg2 queryId:(unsigned long long)arg3;
- (bool)isContact;
- (bool)isDraggable;
- (bool)isLocalApplicationResult;
- (bool)isTappable;
- (id)leadingButton;
- (id)leadingImage;
- (id)mapsResult;
- (id)nearbyBusinessesString;
- (id)populatedMapsCardSectionIfApplicable;
- (bool)preventThumbnailImageScaling;
- (id)punchouts;
- (id)richTextFromText:(id)arg1;
- (id)secondaryTitle;
- (id)secondaryTitleImage;
- (bool)secondaryTitleIsDetached;
- (int)separatorStyle;
- (void)setAction:(id)arg1;
- (void)setApplicationBundleIdentifier:(id)arg1;
- (void)setDetails:(id)arg1;
- (void)setFallbackImage:(id)arg1;
- (void)setFootnote:(id)arg1;
- (void)setFootnoteButtonText:(id)arg1;
- (void)setIsLocalApplicationResult:(bool)arg1;
- (void)setLeadingButton:(id)arg1;
- (void)setLeadingImage:(id)arg1;
- (void)setMapsResult:(id)arg1;
- (void)setNearbyBusinessesString:(id)arg1;
- (void)setPreventThumbnailImageScaling:(bool)arg1;
- (void)setSecondaryTitle:(id)arg1;
- (void)setSecondaryTitleImage:(id)arg1;
- (void)setSecondaryTitleIsDetached:(bool)arg1;
- (void)setTitle:(id)arg1;
- (void)setTrailingBottomText:(id)arg1;
- (void)setTrailingMiddleText:(id)arg1;
- (void)setTrailingTopText:(id)arg1;
- (void)setTruncateTitleMiddle:(bool)arg1;
- (void)setUseCompactDisplay:(bool)arg1;
- (id)title;
- (id)trailingBottomText;
- (id)trailingMiddleText;
- (id)trailingTopText;
- (bool)truncateTitleMiddle;
- (bool)useCompactDisplay;

@end
