/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUILabel : TLKLabel {
    SFText * _sfText;
}

@property (nonatomic, retain) SFText *sfText;

- (void).cxx_destruct;
- (void)setSfText:(id)arg1;
- (id)sfText;

@end
