/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUITableHeaderView : UITableViewHeaderFooterView <NUIContainerViewDelegate> {
    <SearchUITableHeaderViewDelegate> * _delegate;
    <SFFeedbackListener> * _feedbackListener;
    TLKTextButton * _headerOptionButton;
    unsigned long long  _headerType;
    bool  _isExpanded;
    SFResultSection * _section;
    bool  _shouldUseInsetRoundedSections;
    TLKStackView * _stackView;
    TLKLabel * _titleLabel;
}

@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <SearchUITableHeaderViewDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic) <SFFeedbackListener> *feedbackListener;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) TLKTextButton *headerOptionButton;
@property (nonatomic) unsigned long long headerType;
@property (nonatomic) bool isExpanded;
@property (nonatomic, retain) SFResultSection *section;
@property (nonatomic) bool shouldUseInsetRoundedSections;
@property (nonatomic, retain) TLKStackView *stackView;
@property (readonly) Class superclass;
@property (readonly) NSString *title;
@property (nonatomic, retain) TLKLabel *titleLabel;

+ (id)reuseIdentifier;

- (void).cxx_destruct;
- (void)_dynamicUserInterfaceTraitDidChange;
- (id)delegate;
- (void)didMoveToWindow;
- (id)feedbackListener;
- (id)headerOptionButton;
- (unsigned long long)headerType;
- (id)init;
- (bool)isExpanded;
- (bool)isSuggestedAppsHeader;
- (void)layoutSubviews;
- (void)moreButtonPressed;
- (id)moreResultsPunchout;
- (id)section;
- (void)setDelegate:(id)arg1;
- (void)setFeedbackListener:(id)arg1;
- (void)setFloating:(bool)arg1;
- (void)setHeaderOptionButton:(id)arg1;
- (void)setHeaderType:(unsigned long long)arg1;
- (void)setIsExpanded:(bool)arg1;
- (void)setSection:(id)arg1;
- (void)setShouldUseInsetRoundedSections:(bool)arg1;
- (void)setStackView:(id)arg1;
- (void)setTitleLabel:(id)arg1;
- (bool)shouldUseInsetRoundedSections;
- (struct CGSize { double x1; double x2; })sizeThatFits:(struct CGSize { double x1; double x2; })arg1;
- (id)stackView;
- (bool)supportsShowMoreInApp;
- (id)title;
- (id)titleLabel;
- (void)tlk_updateForAppearance:(id)arg1;
- (void)updateHeaderButtonVisibilityAnimated:(bool)arg1;
- (void)updateWithSection:(id)arg1 isExpanded:(bool)arg2 usesInsetRoundedSection:(bool)arg3;

@end
