/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUICenteredResultRowModel : SearchUIRowModel

- (Class)cellViewClass;
- (bool)isTappable;
- (id)nextCard;
- (id)punchouts;

@end
