/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUISymbolImage : SearchUIImage

+ (id)chevronImage;
+ (id)systemImageName:(id)arg1 withConfiguration:(id)arg2;

- (int)defaultCornerRoundingStyle;
- (unsigned long long)hash;
- (id)initWithSymbolName:(id)arg1;
- (id)initWithSymbolName:(id)arg1 font:(id)arg2;
- (id)initWithSymbolName:(id)arg1 font:(id)arg2 scale:(long long)arg3;
- (id)initWithSymbolName:(id)arg1 pointSize:(double)arg2;
- (id)initWithSymbolName:(id)arg1 scale:(long long)arg2;
- (id)initWithSymbolName:(id)arg1 textStyle:(id)arg2;
- (id)initWithSymbolName:(id)arg1 textStyle:(id)arg2 scale:(long long)arg3;
- (id)initWithSymbolName:(id)arg1 textStyle:(id)arg2 scale:(long long)arg3 font:(id)arg4;
- (bool)isEqual:(id)arg1;

@end
