/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUICardSectionRowModel : SearchUIRowModel {
    Class  _customCardSectionViewClass;
    bool  _isInline;
}

@property (readonly) Class customCardSectionViewClass;
@property (nonatomic) bool isInline;

- (void).cxx_destruct;
- (id)accessibilityIdentifier;
- (bool)anyInlineCardSectionsHaveNextCards;
- (bool)anyInlineCardSectionsHavePunchouts;
- (Class)cardSectionViewClass;
- (Class)cellViewClass;
- (Class)customCardSectionViewClass;
- (id)description;
- (id)dragSubtitle;
- (id)dragText;
- (id)dragTitle;
- (id)dragURL;
- (id)fallbackCardSectionForCompactResult;
- (bool)fillsBackgroundWithContent;
- (bool)hasLeadingImage;
- (id)initWithResult:(id)arg1 cardSection:(id)arg2 isInline:(bool)arg3 queryId:(unsigned long long)arg4;
- (bool)isDraggable;
- (bool)isInline;
- (bool)isQuerySuggestion;
- (bool)isTappable;
- (id)nextCard;
- (bool)prefersNoSeparatorAbove;
- (id)punchouts;
- (id)reuseIdentifier;
- (int)separatorStyle;
- (void)setIsInline:(bool)arg1;
- (bool)supportsCustomUserReportRequestAfforance;

@end
