/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUIPeekCommand : SearchUICommand {
    UIViewController * _viewController;
}

@property (nonatomic, retain) UIViewController *viewController;

+ (id)urlMatchingScheme:(id)arg1 inPunchout:(id)arg2;

- (void).cxx_destruct;
- (id /* block */)actionProvider;
- (id)generateViewController;
- (void)setViewController:(id)arg1;
- (id)viewController;

@end
