/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUIStockGraphSectionRowModel : SearchUICardSectionRowModel {
    int  _potentialGraphColor;
}

@property int potentialGraphColor;

- (int)potentialGraphColor;
- (void)setPotentialGraphColor:(int)arg1;

@end
