/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUINowPlayingCardSectionView : SearchUICardSectionView

@property (nonatomic, retain) TLKStackView *contentView;

- (id)initWithRowModel:(id)arg1 feedbackDelegate:(id)arg2;
- (id)setupContentView;

@end
