/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUIContactCardCommand : SearchUITapCommand

+ (bool)supportsRowModel:(id)arg1 environment:(id)arg2;

- (unsigned long long)destination;
- (id)setupViewController;

@end
