/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUIThumbnailViewController : SearchUILeadingViewController

@property (nonatomic, retain) SearchUIImageView *view;

+ (bool)rowModelHasSuggestionThumbnail:(id)arg1;
+ (bool)supportsRowModel:(id)arg1;

- (void)applyImageConstraints;
- (void)forceVerticalCenteringOfContents;
- (void)setUsesCompactWidth:(bool)arg1;
- (id)setupView;
- (bool)shouldVerticallyCenter;
- (unsigned long long)type;
- (void)updateWithRowModel:(id)arg1;

@end
