/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUIAppStoreButtonViewController : SearchUIAccessoryViewController {
    bool  _appIsInstalled;
    TLKStoreButton * _appStoreButton;
}

@property (nonatomic) bool appIsInstalled;
@property (nonatomic, retain) TLKStoreButton *appStoreButton;

+ (bool)supportsRowModel:(id)arg1;

- (void).cxx_destruct;
- (bool)appIsInstalled;
- (id)appStoreButton;
- (void)buttonPressed;
- (void)setAppIsInstalled:(bool)arg1;
- (void)setAppStoreButton:(id)arg1;
- (id)setupView;
- (bool)shouldTopAlignForAccessibilityContentSizes;
- (unsigned long long)type;
- (void)updateWithRowModel:(id)arg1;

@end
