/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUICombinedCardSectionRowModel : SearchUIRowModel {
    NSArray * _cardSectionRowModels;
}

@property (nonatomic, retain) NSArray *cardSectionRowModels;

- (void).cxx_destruct;
- (id)cardSectionRowModels;
- (Class)cellViewClass;
- (id)dragSubtitle;
- (id)dragText;
- (id)dragTitle;
- (id)dragURL;
- (id)firstRowModel;
- (id)initWithResult:(id)arg1 cardSectionRowModels:(id)arg2;
- (bool)isDraggable;
- (bool)isTappable;
- (id)nextCard;
- (id)punchouts;
- (int)separatorStyle;
- (void)setCardSectionRowModels:(id)arg1;

@end
