/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUICustomCardPresentationCommand : SearchUITapCommand

+ (bool)supportsRowModel:(id)arg1 environment:(id)arg2;

- (unsigned long long)destination;
- (void)performCommandWithCompletion:(id /* block */)arg1;

@end
