/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchUI.framework/SearchUI
 */

@interface SearchUIPunchoutAlertCommand : SearchUITapCommand

+ (id)pickerPunchoutsForRowModel:(id)arg1;
+ (bool)supportsRowModel:(id)arg1 environment:(id)arg2;

- (unsigned long long)destination;
- (bool)prefersModalPresentation;
- (id)setupViewController;

@end
