/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriVideoIntents.framework/SiriVideoIntents
 */

@interface SiriVideoIntents.PlayLiveServiceIntentHandler : NSObject <PlayLiveServiceIntentHandling>

- (void)handlePlayLiveService:(id)arg1 completion:(id /* block */)arg2;
- (id)init;
- (void)resolveLiveServiceForPlayLiveService:(id)arg1 withCompletion:(id /* block */)arg2;

@end
