/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeAutomationInternal.framework/HomeAutomationInternal
 */

@interface HomeAutomationInternal.IntentContext : _TtCs12_SwiftObject {
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  attribute;
    void hasAllQuantifier;
    void isGarageDoorRequest;
    void isRemoteHomeRequest;
    void isRequestToLockOrClose;
    void isSensorTrippedRequest;
    void mockGlobals;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  smallestUserMentionedContainerLayer;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  targetState;
    void userDefinedDuration;
}

@end
