/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsAds.framework/NewsAds
 */

@interface NewsAds.DebugLifecycleMetricsHelper : _TtCs12_SwiftObject <APPCLifecycleMetricsHelping>

- (void)contentLoadFailure;
- (void)discarded;
- (void)missedOpportunity;

@end
