/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AssistantSettingsSupport.framework/AssistantSettingsSupport
 */

@interface AssistantSettingsSignalEmitter : NSObject

- (void)emitDidSelectVoiceSignal;

@end
