/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CMCapture.framework/CMCapture
 */

@interface BWJasperColorStillsExecutorInput : BWStillImageProcessorInput {
    struct opaqueCMSampleBuffer { } * _colorBuffer;
    double  _colorBufferExposureTime;
    struct { 
        long long value; 
        int timescale; 
        unsigned int flags; 
        long long epoch; 
    }  _colorBufferPTS;
    unsigned long long  _colorBufferType;
    <BWJasperColorStillsExecutorInputDelegate> * _delegate;
    int  _maxinimumNumberOfPointCLouds;
    int  _numberOfPointCloudsRequired;
    NSMutableArray * _pointClouds;
}

@property (nonatomic, readonly) struct opaqueCMSampleBuffer { }*colorBuffer;
@property (nonatomic, readonly) unsigned long long colorBufferType;
@property (nonatomic, retain) <BWJasperColorStillsExecutorInputDelegate> *delegate;
@property (nonatomic, readonly) bool needMorePointClouds;
@property (nonatomic, readonly) NSArray *pointClouds;
@property (getter=isReadyToExecute, nonatomic, readonly) bool readyToExecute;

- (void)_trimPointClouds;
- (void)addPointCloud:(struct opaqueCMSampleBuffer { }*)arg1;
- (struct opaqueCMSampleBuffer { }*)colorBuffer;
- (unsigned long long)colorBufferType;
- (void)dealloc;
- (id)delegate;
- (id)initWithSettings:(id)arg1 portType:(id)arg2;
- (bool)isReadyToExecute;
- (id)jasperPointCloudsForColorBuffer;
- (bool)needMorePointClouds;
- (id)pointClouds;
- (void)setColorBuffer:(struct opaqueCMSampleBuffer { }*)arg1 type:(unsigned long long)arg2;
- (void)setColorBufferPTS:(struct { long long x1; int x2; unsigned int x3; long long x4; })arg1 exposureTime:(double)arg2;
- (void)setDelegate:(id)arg1;

@end
