/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
 */

@interface CCUIContentModuleContainerClientDrivenTransition : CCUIContentModuleContainerTransition

- (id)customAnimator;

@end
