/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoverSheet.framework/CoverSheet
 */

@interface CSDismissableModalViewController : CSPresentationViewController <CSModalHomeGestureParticipating, UIGestureRecognizerDelegate> {
    UIScreenEdgePanGestureRecognizer * _bottomEdgeRecognizer;
    <CSDismissableModalViewControllerDelegate> * _delegate;
    <CSModalHomeAffordanceControlling> * _homeAffordanceController;
}

@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <CSDismissableModalViewControllerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) <CSModalHomeAffordanceControlling> *homeAffordanceController;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_addOrRemoveGestureForCurrentSettings;
- (void)_handleBottomEdgeGestureBegan:(id)arg1;
- (void)_handleBottomEdgeGestureChanged:(id)arg1;
- (void)_handleBottomEdgeGestureEnded:(id)arg1;
- (void)_handleBottomEdgeGestureRecognizer:(id)arg1;
- (void)addGrabberView:(id)arg1;
- (id)delegate;
- (bool)handleEvent:(id)arg1;
- (id)homeAffordanceController;
- (void)homeGestureParticipantOwningHomeGestureDidChange:(bool)arg1;
- (bool)presentationCancelsTouches;
- (void)setDelegate:(id)arg1;
- (void)setHomeAffordanceController:(id)arg1;
- (void)viewDidDisappear:(bool)arg1;
- (void)viewWillAppear:(bool)arg1;
- (bool)wouldHandleButtonEvent:(id)arg1;

@end
