/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoverSheet.framework/CoverSheet
 */

@interface CSModalVisualEffect : UIVisualEffect

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)effectConfig;

@end
