/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoverSheet.framework/CoverSheet
 */

@interface CSTeachableMomentsContainerView : CSCoverSheetViewBase <SBUIOptionalLegibility> {
    SBUILegibilityLabel * _callToActionLabel;
    UIView * _callToActionLabelContainerView;
    UIView * _callToActionLabelPositionPlaceholderView;
    UIView * _controlCenterGlyphContainerView;
    UIImageView * _controlCenterGlyphView;
    UIView * _controlCenterGrabberContainerView;
    UIView * _controlCenterGrabberEffectContainerView;
    UIView * _controlCenterGrabberPositionPlaceholderView;
    UIView * _controlCenterGrabberView;
    UIView * _controlCenterTutorsContainerView;
    UIView * _homeAffordanceContainerView;
    UIView * _homeAffordanceView;
    _UILegibilitySettings * _legibilitySettings;
    UIStatusBar * _statusBarToFollow;
}

@property (nonatomic, retain) SBUILegibilityLabel *callToActionLabel;
@property (nonatomic, retain) UIView *callToActionLabelContainerView;
@property (nonatomic, retain) UIView *callToActionLabelPositionPlaceholderView;
@property (nonatomic, retain) UIView *controlCenterGlyphContainerView;
@property (nonatomic, retain) UIImageView *controlCenterGlyphView;
@property (nonatomic, retain) UIView *controlCenterGrabberContainerView;
@property (nonatomic, retain) UIView *controlCenterGrabberEffectContainerView;
@property (nonatomic, retain) UIView *controlCenterGrabberPositionPlaceholderView;
@property (nonatomic, retain) UIView *controlCenterGrabberView;
@property (nonatomic, retain) UIView *controlCenterTutorsContainerView;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) UIView *homeAffordanceContainerView;
@property (nonatomic, retain) UIView *homeAffordanceView;
@property (nonatomic, retain) _UILegibilitySettings *legibilitySettings;
@property (nonatomic) UIStatusBar *statusBarToFollow;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_addCallToActionLabel;
- (void)_addControlCenterTutors;
- (id)_callToActionLabelFont;
- (struct CGPoint { double x1; double x2; })_grabberCenterForCointainerBounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 grabberTop:(double)arg2 grabberSize:(struct CGSize { double x1; double x2; })arg3;
- (void)_layoutCallToActionLabel;
- (void)_layoutControlCenterGrabberAndGlyph;
- (void)_layoutHomeAffordanceContainer;
- (void)_preferredTextSizeChanged:(id)arg1;
- (void)_updateViewsForLegibilitySettings;
- (id)callToActionLabel;
- (id)callToActionLabelContainerView;
- (id)callToActionLabelPositionPlaceholderView;
- (id)controlCenterGlyphContainerView;
- (id)controlCenterGlyphView;
- (id)controlCenterGrabberContainerView;
- (id)controlCenterGrabberEffectContainerView;
- (id)controlCenterGrabberPositionPlaceholderView;
- (id)controlCenterGrabberView;
- (id)controlCenterTutorsContainerView;
- (id)createCallToActionLabel;
- (id)hitTest:(struct CGPoint { double x1; double x2; })arg1 withEvent:(id)arg2;
- (id)homeAffordanceContainerView;
- (id)homeAffordanceView;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)layoutSubviews;
- (id)legibilitySettings;
- (id)presentationRegions;
- (void)setCallToActionLabel:(id)arg1;
- (void)setCallToActionLabelContainerView:(id)arg1;
- (void)setCallToActionLabelPositionPlaceholderView:(id)arg1;
- (void)setControlCenterGlyphContainerView:(id)arg1;
- (void)setControlCenterGlyphView:(id)arg1;
- (void)setControlCenterGrabberContainerView:(id)arg1;
- (void)setControlCenterGrabberEffectContainerView:(id)arg1;
- (void)setControlCenterGrabberPositionPlaceholderView:(id)arg1;
- (void)setControlCenterGrabberView:(id)arg1;
- (void)setControlCenterTutorsContainerView:(id)arg1;
- (void)setHomeAffordanceContainerView:(id)arg1;
- (void)setHomeAffordanceView:(id)arg1;
- (void)setLegibilitySettings:(id)arg1;
- (void)setStatusBarToFollow:(id)arg1;
- (bool)statusBarIsReady;
- (id)statusBarToFollow;

@end
